### ISSUE TITLE
Add information about building 0.2 alpha release on Titan to webpage

### ISSUE THREAD

**Issue by jwillenbring** [xsdk-project/xsdk-issues#1]
Mark B. has agreed to provide information about building the 0.2 alpha release on Titan to @amklinv, who will add the information to the [xSDK 0.2 webpage](https://xsdk.info/release-0-2-0-alpha/).

Done for this story requires transferring the information provided by Mark to the webpage linked to above.

**Comment by amklinv** [comment]
Spack does not work sufficiently well on Titan yet.  I will return to this issue when it does.

**Comment by jwillenbring** [comment]
This was done prior to the release. The issue behind one work around specified by Mark was resolved, so I omitted that information. The other workaround related to openblas was included in the description because that issue was not resolved.
