### ISSUE TITLE
hypre@develop API change breaks build with petsc@develop

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#102]
@ulrikeyang Looks like hypre has a API change that is breaking petsc build.

```
bash-4.2$ nm -Ao hypre-*/lib*/libHYPRE.so |grep hypre_AuxParCSRMatrixInitialize
hypre-2.18.2-5osthlw24mdfqgou7njvrlxuo7y4lyjf/lib/libHYPRE.so:00000000000789ae T hypre_AuxParCSRMatrixInitialize
hypre-develop-cwpmpheza2gjssjewqgcetrq6imhuwyq/lib/libHYPRE.so:000000000007cbba T hypre_AuxParCSRMatrixInitialize_v2
```

we don't have appropriate policies in XSDK wrt API changes that can break compatibilities between packages.

Depricating funciton [i.e not removing them] when API changes usually helps.

 Also version check macros  can help here [so that the dependent package can support both versions - and transition smoothly] - the policy suggestion in this regard is I guess stuck

https://github.com/xsdk-project/xsdk-community-policies/pull/16

**Comment by ulrikeyang** [comment]
Hi Satish,
I thought we did this. I am cc’ing Ruipeng because we discussed this.
Did you use the most recent development branch for hypre?
Thanks
Ulrike

**Comment by balay** [comment]
cc: @liruipeng

@ulrikeyang - yes this is with current hypre/master branch

I see the prototype of hypre_AuxParCSRMatrixInitialize() in include file , and a couple of usages from sources - but not the implementation code for this function

```
balay@sb /home/balay/git-repo/github/hypre (master=)
$ git grep hypre_AuxParCSRMatrixInitialize
src/IJ_mv/IJMatrix_isis.c:   ierr = hypre_AuxParCSRMatrixInitialize(aux_matrix);
src/IJ_mv/IJMatrix_parcsr.c:      hypre_AuxParCSRMatrixInitialize_v2(aux_matrix, memory_location_aux);
src/IJ_mv/IJMatrix_parcsr_device.c:      hypre_AuxParCSRMatrixInitialize_v2(aux_matrix, HYPRE_MEMORY_DEVICE);
src/IJ_mv/IJMatrix_petsc.c:   ierr = hypre_AuxParCSRMatrixInitialize(aux_matrix);
src/IJ_mv/_hypre_IJ_mv.h:HYPRE_Int hypre_AuxParCSRMatrixInitialize ( hypre_AuxParCSRMatrix *matrix );
src/IJ_mv/_hypre_IJ_mv.h:HYPRE_Int hypre_AuxParCSRMatrixInitialize_v2( hypre_AuxParCSRMatrix *matrix, HYPRE_MemoryLocation memory_location );
src/IJ_mv/aux_parcsr_matrix.c: * hypre_AuxParCSRMatrixInitialize_v2
src/IJ_mv/aux_parcsr_matrix.c:hypre_AuxParCSRMatrixInitialize_v2( hypre_AuxParCSRMatrix *matrix, HYPRE_MemoryLocation memory_location )
```

**Comment by liruipeng** [comment]
@balay Does PETSc call `hypre_IJMatrixInitializePETSc` which has `hypre_AuxParCSRMatrixInitialize` inside or call `hypre_AuxParCSRMatrixInitialize` directly?

**Comment by balay** [comment]
PETSc has a call to hypre_AuxParCSRMatrixInitialize()
```
balay@sb /home/balay/petsc (maint=)
$ git grep hypre_AuxParCSRMatrixInitialize
src/mat/impls/hypre/mhypre.c:    PetscStackCallStandard(hypre_AuxParCSRMatrixInitialize,(aux_matrix));
```

**Comment by liruipeng** [comment]
> PETSc has a call to hypre_AuxParCSRMatrixInitialize()
> 
> ```
> balay@sb /home/balay/petsc (maint=)
> $ git grep hypre_AuxParCSRMatrixInitialize
> src/mat/impls/hypre/mhypre.c:    PetscStackCallStandard(hypre_AuxParCSRMatrixInitialize,(aux_matrix));
> ```

@balay  @ulrikeyang does PETSc care about hypre's GPU build at the moment? If no, it is a very easy fix.

**Comment by balay** [comment]
There is a feature branch in petsc with changes fro hypre/gpu support - but my understanding is - its not yet ready for a merge [to petsc/master]

Irrespective of that - I think it would be good if hypre keeps compatibility with the old hypre_AuxParCSRMatrixInitialize() interface [perhaps mark it as deprecated]

**Comment by balay** [comment]
Note: If needed - I can update petsc to work with both versions [assuming version check macros work with development version]

Similar issue with superlu dist - will file this now.

**Comment by liruipeng** [comment]
> Note: If needed - I can update petsc to work with both versions [assuming version check macros work with development version]
> 
> Similar issue with superlu dist - will file this now.

We will add the `hypre_AuxParCSRMatrixInitialize()` back. Also, the _v2 routines are just temporary which will be gone

**Comment by balay** [comment]
This issue affects mfem aswell - so adding this info here.

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/4453168/spack-build-out.txt)

**Comment by balay** [comment]
Ah - should have check closely - its not mfem+hypre issue. its the same petsc+hypre issue - that come up when mfem links with petsc

```
/home/balay/spack.x/opt/spack/linux-centos7-skylake_avx512/gcc-7.4.0/petsc-develop-bkhlotig3vfsz3ji3hz5fyw6bgx7ruil/lib/libpetsc.so: undefined reference to `hypre_AuxParCSRMat\
rixInitialize'
```

**Comment by balay** [comment]
Looks like this issue is resolved [I don't remember how] current petsc+hypre is building fine. so closing this issue.
