### ISSUE TITLE
tasmanian@develop breaks with gcc@4.8.5

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#103]
However tasmanian@7.0 builds fine in this case

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/4452444/spack-build-out.txt)

**Comment by mkstoyanov** [comment]
Tasmanian develop requires C++2014 while Tasmanian 7.0 requires only C++2011. The gcc 4.8.5 does not support C++2014.

Sorry for the inconvenience.

The error message is strange. I would expect that CMake would just stop at configure time and complain about the C++ standard, instead CMake adds a `-std=c++1y` flag and the compiler crashes on missing `std::make_unique` which was added in the 2014 standard.

**Comment by balay** [comment]
Thanks!. Yes - cmake should give the appropriate error message. 

Tasks wrt xsdk:
- add conflict for this C++2014 requirement in Tasmanian package
- somehow selectively enable/disable Tasmanian [within xsdk] - when compiler doesn't satisfy this rquirement [may not be possible]
- add a Tasmanian variant  [to xsdk] so it can be disabled on such systems..

**Comment by mkstoyanov** [comment]
Tasmanian can be de-selected from xSDK but adding a +tasmanian variant would be hard to maintain over the long run. The variants in spack create a chain of dependencies, when our users define their dependence to be "xsdk +tasmanian" then we cannot remove "+tasmanian" from xSDK without breaking compatibility. Basically, we would be stuck with +tasmanian forever.

How about we simply use Tasmanian 7.0 for older compilers and use Tasmanian-develop (or 7.1) for the newer ones. The user can always check for the Tasmanian version when they include the header and older Tasmanian is better than no Tasmanian.

But I have to question whether or not it makes sense to support an old compiler like that. I understand that there are still systems where gcc 4.8 is the default, but I bet that all of those also have gcc 5 or newer easily available.

**Comment by balay** [comment]
I view gcc 4.8 build more of as a debugging exercise - this way we are handling the corner cases.

Wrt variant - I'm not sure I understand the concern. We currently have a bunch of packages listed as variants for xsdk  [default =on] - so that they can be disabled if need. So this shouldn't be a problem. And Its good to have a uniform way of handling such things acorss packages.
```
Variants:
    Name [Default]        Allowed values    Description
    ==================    ==============    ==============================

    butterflypack [on]    True, False       Enable butterflypack package
                                            build
    cuda [off]            True, False       Enable CUDA dependent packages
    dealii [on]           True, False       Enable dealii package build
    debug [off]           True, False       Compile in debug mode
    ginkgo [on]           True, False       Enable ginkgo package build
    libensemble [on]      True, False       Enable py-libensemble package
                                            build
    omega-h [on]          True, False       Enable omega-h package build
    phist [on]            True, False       Enable phist package build
    precice [on]          True, False       Enable precice package build
    strumpack [on]        True, False       Enable strumpack package build
    trilinos [on]         True, False       Enable trilinos package build
```

**Comment by mkstoyanov** [comment]
@balay I had to revert Tasmanian to C++-11, gcc 4.8 should work now.

It turns out that OLCF has full C++14 only with GCC, which is very frustrating when I have users that need PGI.

**Comment by balay** [comment]
This cycle - we are unlikely to test with gcc-4.8 - so closing
