### ISSUE TITLE
alquimia@develop build error

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#109]
cc: @smolins 

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/4453309/spack-build-out.txt)

**Comment by smolins** [comment]
Yes. I am aware. I was working on it recently but clearly I will need the
help from PFLOTRAN developers to understand the re-factoring that took
place in commit
https://bitbucket.org/pflotran/pflotran/commits/2e36d315a879157ee9d81f516f00af7b7e3718eb,
"Refactored transport constraints using classes"

**Comment by balay** [comment]
Thanks!

 Currently just trying to figure out what works and what needs fixes wrt  develop versions of packages. [the first step towards next xsdk release - sometime in october]

**Comment by balay** [comment]
Trying again - I get a successful build with current master branch
