### ISSUE TITLE
MFEM in xSDK Nov 1 release

### ISSUE THREAD

**Issue by tzanio** [xsdk-project/xsdk-issues#11]
The MFEM team intends to participate in the November 2017 release of xSDK.
cc: @acfisher, @v-dobrev, @jamiebramwell

#### Outstanding policy gaps:
- **M1**: xSDK-specific options in CMake, #15 
- **M3**: user-provided MPI communicators, #16 
- **M8**: runtime API for version number, #37 
- **M11**: disable output/redirect stdout, #18  
- **M16**: Spack support, #19

**Comment by acfisher** [comment]
Community policy gap assessment list.

Mandatory policies NOT in compliance:
M1, M3, M8, M11, M16

Mandatory policies in compliance:
M2, M4, M5, M6, M7, M9, M10, M12, M13, M14, M15

**Comment by v-dobrev** [comment]
Are we following the policies from [version 0.3](http://dx.doi.org/10.6084/m9.figshare.4495136) or the [next draft version 0.4](https://docs.google.com/document/d/1DCx2Duijb0COESCuxwEEK1j0BPe2cTIJ-AjtJxt3290)?

**Comment by v-dobrev** [comment]
Note: policy M8 is also not currently supported.

**Comment by acfisher** [comment]
We believe we are up to speed on all the mandatory policies with changes made in the [xsdk-0.3.0-rc2](https://github.com/mfem/mfem/releases/tag/xsdk-0.3.0-rc2) tag of the MFEM GitHub repo.
