### ISSUE TITLE
phist issues with trilinos and -lpthread

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#112]
[I'll have to recheck builds to get logs]

**Comment by balay** [comment]
Updated to use phist@1.9.1 - and I get errors (this is with trilinos@13.0.0): 

```
==> Fetching https://bitbucket.org/essex/phist/get/phist-1.9.1.tar.gz
==> phist: Executing phase: 'cmake'
==> phist: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j64'

4 errors found in build log:
     204       ^~~~~~~
     205    /data/balay/spack-xsdk/spack-stage/spack-stage-phist-1.9.1-i35fdrabqd4go233aslw3bh6nx7w322y/spack-src/src/kernels/tpetra/kernels.cpp:72:33: warning: extra tokens at end of #undef directive
     206     # undef PHIST_TRY_TO_PIN_THREADS`
     207                                     ^
     208    In file included from /data/balay/spack-xsdk/spack-stage/spack-stage-phist-1.9.1-i35fdrabqd4go233aslw3bh6nx7w322y/spack-src/src/kernels/tpetra/kernelsD.cpp:64:0:
     209    /data/balay/spack-xsdk/spack-stage/spack-stage-phist-1.9.1-i35fdrabqd4go233aslw3bh6nx7w322y/spack-src/src/kernels/tpetra/kernels_def.hpp: In function 'void phist_DsdMat_view_block(phist_DsdMat_ptr, 
            phist_DsdMat**, int, int, int, int, int*)':
  >> 210    /data/balay/spack-xsdk/spack-stage/spack-stage-phist-1.9.1-i35fdrabqd4go233aslw3bh6nx7w322y/spack-src/src/kernels/tpetra/kernels_def.hpp:436:20: error: 'using sdMat_t = class Tpetra::MultiVector<dou
            ble, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > {aka class Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >}' has no member na
            med 'getDualView'; did you mean 'getLocalView'?
     211       auto view = mat->getDualView();
     212                        ^~~~~~~~~~~
     213                        getLocalView
  >> 214    make[2]: *** [CMakeFiles/phist_kernels_tpetra.dir/src/kernels/tpetra/kernelsD.cpp.o] Error 1
     215    make[2]: *** Waiting for unfinished jobs....
     216    make[2]: Leaving directory `/data/balay/spack-xsdk/spack-stage/spack-stage-phist-1.9.1-i35fdrabqd4go233aslw3bh6nx7w322y/spack-build'
  >> 217    make[1]: *** [CMakeFiles/phist_kernels_tpetra.dir/all] Error 2
     218    make[1]: Leaving directory `/data/balay/spack-xsdk/spack-stage/spack-stage-phist-1.9.1-i35fdrabqd4go233aslw3bh6nx7w322y/spack-build'
  >> 219    make: *** [all] Error 2
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5240711/spack-build-out.txt)

**Comment by balay** [comment]
BTW: This build is with `~openmp`
```
    depends_on('phist kernel_lib=tpetra', when='+trilinos +phist')
    depends_on('phist@1.9.1 ~fortran ~scamac ~openmp ~host ~int64', when='@0.6.0 +phist')
```

**Comment by jthies** [comment]
there was an API change in Trilinos between 12.x and 13, so right now I can't build with Trilinos 13 and kernel_lib=tpetra. Will fix that first and look at the pthread issue then (if it didn't disappear)

**Comment by jthies** [comment]
@balay could you try using phist@develop? I have a working build with trilinos@develop at least now and would like to see if the problem persists

**Comment by balay** [comment]
I get:
```
/usr/bin/ld: CMakeFiles/phist-1.9.2-kernels-test-RelWithDebInfo.dir/lib/googletest-master-12-2015/gtest/gtest-all.cc.o: undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5243454/spack-build-out.txt)

**Comment by balay** [comment]
Note: this is with trilinos-13.0.0. As far as I can tell - 13.x.x is the trilinos release for xsdk-0.6.0 [so don't really know if it will be from develp branch or a release branch of trilinos - or if it wll stay at 13.0.0]

**Comment by jthies** [comment]
I suspect that the issue occurs because Trilinos uses mpic++ as C++ compiler, whereas phist uses the spack-defined C++ compiler (the default behavior for a CMakePackage). Which spack branch would i have to use to reproduce this?

**Comment by balay** [comment]
Currently working with https://github.com/xsdk-project/spack-xsdk  `xsdk-0.6.0` branch

**Comment by balay** [comment]
I'm still seeing issues with phist@1.9.2 on 2 different linux/gcc builds.
```
/usr/bin/ld: CMakeFiles/phist-1.9.2-kernels-test-RelWithDebInfo.dir/lib/googletest-master-12-2015/gtest/gtest-all.cc.o: undefined reference to symbol 'pthread_getspecific@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5380642/spack-build-out.txt)
[spack-build-out-1.txt](https://github.com/xsdk-project/xsdk-issues/files/5380643/spack-build-out-1.txt)

**Comment by balay** [comment]
enabling openmp on linux builds gets rid of this error - so there might be some openmp/thread code without the appropriate openmp ifdef

**Comment by jthies** [comment]
Thanks @balay! That last hint helped a lot. It turns out that googletest pulls in pthreads. I hope to have fixed it in phist@develop and phist@1.9.3 (added to spack package in this PR: https://github.com/spack/spack/pull/19510). I hope that fixes the problem for you, too. If so, phist@1.9.3 would be the version for the 0.6.0 xSDK release.

**Comment by balay** [comment]
Thanks! will try this update.

BTW:  url in spack is likely incorrect
```
-    git      = "https://bitbucket.org/essex/phist/phist.git"
+    git      = "https://bitbucket.org/essex/phist.git"
```
Also `kernel_lib=builtin` gives errors: `int64 mismatch` [sorry don't have the exact error message] - so reverted this part to petsc

**Comment by jthies** [comment]
right - builtin only works with 64-bit ints. So we'll leave it at petsc as fallback if Trilinos is not available then since that was not the cause of this issue. Thanks for the hint, url has been fixed
