### ISSUE TITLE
pumi build error on macos

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#113]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/742346475

```
413    /Users/xsdk/builds/A57L32nw/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-pumi-2.3.0-xsdk-lgww2haiaexqtmudf2uzdqi7spm7n5ea/spack-src/mds/mdsUgrid.cc:312:35: error: expected expression
     414                                      [upward_dim](const int i) {
     415                                      ^
  >> 416    /Users/xsdk/builds/A57L32nw/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-pumi-2.3.0-xsdk-lgww2haiaexqtmudf2uzdqi7spm7n5ea/spack-src/mds/mdsUgrid.cc:316:34: error: expected expression
     417                                     [upward_id](const int i) {
     418                                     ^
  >> 419    /Users/xsdk/builds/A57L32nw/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-pumi-2.3.0-xsdk-lgww2haiaexqtmudf2uzdqi7spm7n5ea/spack-src/mds/mdsUgrid.cc:340:37: error: expected expression
     420                                        [](const int i){ return i == 1; }))
     421                                        ^
  >> 422    /Users/xsdk/builds/A57L32nw/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-pumi-2.3.0-xsdk-lgww2haiaexqtmudf2uzdqi7spm7n5ea/spack-src/mds/mdsUgrid.cc:352:41: error: expected expression
     423                                            [edge_id](const int i) {
     424                                            ^
     425    4 errors generated.
```

**Comment by balay** [comment]
Hi @cwsmith checking on how to deal with pumi failures with xsdk testing

**Comment by cwsmith** [comment]
@balay This should be fixed in the `develop` branch now (https://github.com/SCOREC/core/commit/53339a11dfd579cab935c6b7a2a6da3d7e333aea) and, if the nightly tests pass, it will be merged into `master` by tomorrow morning.

**Comment by cwsmith** [comment]
https://github.com/SCOREC/core/commit/53339a11dfd579cab935c6b7a2a6da3d7e333aea was merged into master.

It looks like a recent pumi osx clang11 build succeeded: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/766775020#L368

**Comment by balay** [comment]
@cwsmith Thanks! Yes - this build was from last night - so likely used the master snapshot with the above fix.

**Comment by balay** [comment]
@cwsmith  I'm seeing the osx build again [with 2.2.3]. Attaching the log

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5378538/spack-build-out.txt)

**Comment by cwsmith** [comment]
OK. I'll create a new 2.2.4 release that includes fix (https://github.com/SCOREC/core/commit/53339a11dfd579cab935c6b7a2a6da3d7e333aea).  I'm sorry about overlooking this.

The 2.2.4 tag is available (https://github.com/SCOREC/core/issues/324).  I'll add it to spack shortly.

**Comment by cwsmith** [comment]
@balay The spack PR to add pumi 2.2.4 has been created: https://github.com/spack/spack/pull/19325

**Comment by balay** [comment]
@cwsmith I tried 2.2.4 i.e 8439d928afcb95d88652f4812dcb62077ed958f6  - and still get errors

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5386740/spack-build-out.txt)

Looks like the fix mentioned above (53339a11dfd579cab935c6b7a2a6da3d7e333aea )  is not in 2.2.4

```
balay@sb /home/balay/git-repo/github/pumi (master=)
$ git log --oneline --no-merges 53339a11dfd579cab935c6b7a2a6da3d7e333aea..8439d928afcb95d88652f4812dcb62077ed958f6
balay@sb /home/balay/git-repo/github/pumi (master=)
$ git log --oneline --no-merges 8439d928afcb95d88652f4812dcb62077ed958f6..53339a11dfd579cab935c6b7a2a6da3d7e333aea
53339a11 replace c++11 features
balay@sb /home/balay/git-repo/github/pumi (master=)
$ 

```

**Comment by balay** [comment]
I see the MR is using a different commit than the commit corresponding to tag `v2.2.4`. Will check bc34e3f7cfd8ab314968510c71486b140223a68f

**Comment by balay** [comment]
pumi now builds on macos with bc34e3f7cfd8ab314968510c71486b140223a68f

**Comment by balay** [comment]
BTW: you might want to fix the v2.2.4 tag in the repo 

but once someone pulls tags - its hard to change the tag. everyone would  have to manually delete the tag

alternative is to tag a new v2.2.5

**Comment by cwsmith** [comment]
@balay Yeah... I messed this up.    Thanks for sanity checking and finding the mistakes.  

There are two problems:

1. the tag points at the wrong commit - v2.2.4 should point at https://github.com/SCOREC/core/commit/8072fdbafd53e0c9a63248a269f4cce5000a4a8e instead of https://github.com/SCOREC/core/commit/8439d928afcb95d88652f4812dcb62077ed958f6.  After running our test/merge script I think I missed a `git pull` on master before creating the tag.
2. the commit hash in the spack PR was old/wrong.  I've closed the Spack PR.

I've updated the pumi maintainer wiki to hopefully avoid this mess next time.
https://github.com/SCOREC/core/wiki/Maintainer's-Guide

Given that the v2.2.4 tag cannot be moved without causing headaches for users, then I think I'll have to redo the release steps for v2.2.5 and describe what happened with v2.2.4.  Does removing the incorrect v2.2.4 tag make sense?  I don't see any benefit to keeping it.

**Comment by balay** [comment]
Ah - I've been testing with the wrong commit for 2.4.4  Sorry for the messup. :(

I'll update 2.4.4 to use 8072fdbafd53e0c9a63248a269f4cce5000a4a8e - and add in 2.4.5 - when ready

**Comment by cwsmith** [comment]
@balay No worries. 

v2.2.5 is up: https://github.com/SCOREC/core/commit/73c16eae073b179e45ec625a5abe4915bc589af2

The v2.2.4 tag was deleted.

**Comment by balay** [comment]
Thanks! will use v2.2.5 now
