### ISSUE TITLE
Trilinos build failures with Intel compilers.

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#115]
Trilinos build fails with Intel compilers.

Last year we used `intel@18.0.1` - and this worked. However - trilinos fails with `internal compiler error`

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/744279782

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5248941/spack-build-out.txt)

So I tried switching to  intel@19.0.3.199  - it fails again with  `internal compiler error`

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/746246654

[spack-build-out-1.txt](https://github.com/xsdk-project/xsdk-issues/files/5248947/spack-build-out-1.txt)

**Comment by balay** [comment]
@jwillenbring @keitat  How do we deal with the intel build failures [internal compiler errors]?

This is preventing other dependent packages from getting built/tested.

**Comment by jwillenbring** [comment]
@jhux2 Have you encountered anything like this before? Please see the first link, https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/744279782 around line 727 and below.

**Comment by jhux2** [comment]
I haven't.  Can you post a representative cmake configure line (non-spack), and I can try reproducing on some SNL machines.

**Comment by balay** [comment]
As noted - this breaks on 2 different machine build via spack. The first one is the UTK test box - all xsdk project members can get access to - to debug

On the second one [a KNL box] - the following change gets trilinos build working

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/766775021
```
$ python3 ./bin/spack install -j24 xsdk ^suite-sparse@5.3.0 ^boost@1.70.0 ^trilinos target=x86_64
```
Note: spack defaults to `target=mic_knl` on this machine.

 However the same workaround does not work on the UTK machine. I should retry. Its not clear what compiler options spack uses [for its chosen target]

**Comment by jhux2** [comment]
It seems that a good first step then would be to find out the exact compiler options being used, as well as the Trilinos configure options. Otherwise I don’t see how to debug this.

**Comment by keitat** [comment]
Should we try with a small values of -j parameter?  It can be a buffer/memory capacity issue of compiler executions.

**Comment by balay** [comment]
I had previously tried smaller -j

Ok redoing test with `-j16 ^trilinos target=x86_64`

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/769994138

**Comment by balay** [comment]
> It seems that a good first step then would be to find out the exact compiler options being used, as well as the Trilinos configure options. Otherwise I don’t see how to debug this.

The trilinos configure options are listed in spack-build-out-1.txt  file - previously attached to this issue tracker [above]

Wrt compiler options - some should be listed in the log file. However I don't know how to figure out what options spack compiler wrappers internally use. spack-build-env.txt does not list these options.

Perhaps @tgamblin or @adamjstewart can assist.

**Comment by adamjstewart** [comment]
I believe you can run `spack --debug install` to get the actual compiler flags injected to show up in the build log. But I'm not 100% sure.

**Comment by balay** [comment]
Hm - I see bunch of stdout - but not really the compiler flag listing.

And I see the following in spack-build-env.txt

SPACK_TARGET_ARGS='-march=skylake-avx512 -mtune=skylake-avx512'; export SPACK_TARGET_ARGS

So these are added to CFLAGS/CXXFLAGS by the spack compiler wrappers?

@jwillenbring @keitat  - can you attempt a non-spack  build of trilinos with these flags and check?

**Comment by balay** [comment]
> Ok redoing test with -j16 ^trilinos target=x86_64

The build broke again - so this didn't help. The command was:
```
./bin/spack install -j16 xsdk%intel@19.0.3.199 target=skylake_avx512 ^suite-sparse@5.3.0 ^python%gcc@7.4.0 ^py-numpy%gcc@7.4.0 ^cmake%gcc@7.4.0 ^diffutils%gcc@7.4.0 ^trilinos target=x86_64
```
I'll have to extract spack-build-env.txt from this build - to see if the target got changed or not [and why it still fails]

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5319209/spack-build-out.txt)

**Comment by jhux2** [comment]
I was able to build Trilinos successfully on a Sandia machine.  The exact compiler/mpi versions weren't available, so I used `Intel 19.0.3.199` and `Intel MPI Version 2018 Update 4 Build 20180823`.  My configure was very similar to [this one](https://github.com/xsdk-project/xsdk-issues/files/5248947/spack-build-out-1.txt).  I did disable the TPLs `hypre`, `matio`, and `glm`.

**Comment by balay** [comment]
> I'll have to extract spack-build-env.txt from this build - to see if the target got changed or not [and why it still fails]
```
SPACK_TARGET_ARGS='-march=pentium4 -mtune=generic'; export SPACK_TARGET_ARGS
```
[spack-build-env.txt](https://github.com/xsdk-project/xsdk-issues/files/5320226/spack-build-env.txt)

**Comment by balay** [comment]
> The exact compiler/mpi versions weren't available, so I used Intel 19.0.3.199 and Intel MPI Version 2018 Update 4 Build 20180823

My primary build is with the same ` Intel 19.0.3.199` - used in combination with gcc-7.4.0 (as icc relies on gcc underneath)
```
balay@xsdk:/home>icc --version
icc (ICC) 19.0.3.199 20190206
balay@xsdk:/home>gcc --version
gcc (GCC) 7.4.0
```
The MPI/Blas and other dependencies are different in my build

Ok - retried the following: spack develop branch - [get ":: internal error:"]

```
./bin/spack install trilinos%intel@19.0.3.199
```

@keitat  - perhaps you can get an account on xsdk.utk to check/reproduce.

**Comment by balay** [comment]
[spack-build-env.txt](https://github.com/xsdk-project/xsdk-issues/files/5320867/spack-build-env.txt)
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5320868/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/xsdk-project/xsdk-issues/files/5320870/spack-configure-args.txt)

**Comment by balay** [comment]
A build on cori - which defaults to `target=haswell` -  with `intel@19.1.2.254` went through fine.

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5387627/spack-build-out.txt)

**Comment by balay** [comment]
And the knl build on theta  also went through.

```
==> Installing trilinos
==> No binary for trilinos found: installing from source
==> trilinos: Executing phase: 'cmake'
==> trilinos: Executing phase: 'build'
==> trilinos: Executing phase: 'install'
[+] /gpfs/mira-home/balay/spack-xsdk-knl/opt/spack/cray-cnl7-mic_knl/intel-19.1.0.166/trilinos-13.0.1-pugejphrw2cdl5b5coyxfla7en53hppq
````

cc: @ulrikeyang
