### ISSUE TITLE
strumpack build error with intel on knl with MKL

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#116]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/746246655

**Comment by pghysels** [comment]
It looks like the -std=c++11 flag isn't passed to the C++ compiler.
I made the following change in STRUMPACK's CMakeLists.txt (https://github.com/pghysels/STRUMPACK/commit/e27b4abc3712353b536a82a460bc54e10d898a0b):
```
-target_compile_features(strumpack INTERFACE cxx_std_11)
+target_compile_features(strumpack PUBLIC cxx_std_11)
```
I hope this fixes it. I need to figure out a way to test on macos myself.

**Comment by balay** [comment]
I still get failures on OSX

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/751074275

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5268670/spack-build-out.txt)

**Comment by balay** [comment]
And I have a failure with a knl build with intel compilers [using mkl]
```
     91    -- A SCALAPACK library could not be found on the system, checking if
            SCALAPACK is implicitly linked by the compiler(wrapper).
     92    -- Looking for pdgemm_ in
     93    -- Looking for pdgemm_ in  - not found
     94    -- Looking for pdgemm in
     95    -- Looking for pdgemm in  - not found
  >> 96    CMake Error at CMakeLists.txt:309 (message):
     97      Could not find a SCALAPACK library.
     98    
     99       You can specify a SCALAPACK library using -DTPL_SCALAPACK_LIBRARI
           ES="..."
```
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/752293885

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5268692/spack-build-out.txt)

**Comment by balay** [comment]
reattaching current failure logs [with intel on knl - using MKL] - with strumpack-5.0.0

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5378618/spack-build-out.txt)
[CMakeError.log](https://github.com/xsdk-project/xsdk-issues/files/5378622/CMakeError.log)
[CMakeOutput.log](https://github.com/xsdk-project/xsdk-issues/files/5378623/CMakeOutput.log)

**Comment by balay** [comment]
@pghysels - I'm also seeing this issue on cori - where I'm using MKL with Intel compilers. [intel@19.1.2.254]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5388709/spack-build-out.txt)

**Comment by pghysels** [comment]
https://github.com/spack/spack/pull/19336

I tested on cori, using ~balay/.spack/packages.yaml
(Sorry this took so long)

```
pghysels@cori03:~/spack$ spack find --deps strumpack@5.0.0 
==> 1 installed package
-- cray-cnl7-haswell / intel@19.1.2.254 -------------------------
strumpack@5.0.0
    butterflypack@1.2.0
        arpack-ng@3.7.0
            intel-mkl@19.1.2.254
            mpich@7.7.10
    metis@5.1.0
    parmetis@4.0.3
    zfp@0.5.5
```

**Comment by balay** [comment]
Thanks! The build works with this patch on both boxes with KNL failures!
