### ISSUE TITLE
ginkgo build error with intel compilers

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#118]
This is a linux/knl build with intel compilers

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5253082/spack-build-out.txt)

**Comment by hartwiganzt** [comment]
Like Trilinos and Kokkos, we upgraded to C++14. Does the intel compiler version maybe not support this?

**Comment by hartwiganzt** [comment]
@balay maybe you can directly link the failing GitLab runner here?

**Comment by tcojean** [comment]
We have a similar build as part of our CI with Intel 18.0.1 and it works there, see [the raw log of this job](https://gitlab.com/ginkgo-project/ginkgo-public-ci/-/jobs/740695061). Your logs seem to show that the compiler doesn't support C++14 for some reason, maybe it's using an outdated linked GCC compiler/headers?

Is it possible to know which GCC version is tied to this Intel compiler?

**Comment by balay** [comment]
Ah - yes. likely we discussed this issue in the last cycle aswell. [dependency of intel c++11/c++14 on the underlying gcc version]

The default gcc here was centos-7 default 4.8.5. And I see - from last years notes - I had to switch to gcc-7.2.0 to get c++11 features working.

Perhaps there is a way in spack to check on this cxx14 dependency - and flag this as a conflict [instead of a build error?]
cc: @tgamblin 

Well I thought one has to use `self.compiler.cxx14_flag` in the corresponding spack package for the build anyway..
[But I don't see this in in ginkgo/package.py. I was expecting usage similar to self.compiler.cxx11_flag usage in superlu-dist/package.py]

The earlier log was from a manual run. I now have this case in CI [It needs improving - it timed out - so no artifacts/logs available]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/747799660

BTW: Trilinos builds are failing for most of my intel builds[even with newer gcc] - with internal compiler errors but @keitat  hasn't seen such reports from users yet - [likely non-spack usage]. But for some reason - this knl build [with gcc-4.8.5 and icc-18.0.1] went through - If I use `target=x86_64`. This didn't help with the other intel builds. [i.e somehow  icc-18.0.1 with gcc-4.8.5 satisfied trilinos cxx14 requirement?]

**Comment by tcojean** [comment]
Thanks for the report, indeed the issue is most likely due to the host GCC compiler being out of date. Since I was anyway updating our package to support HIP, I also tried to do something about this C++11 / C++14 issue, but I'm not sure if that's the correct way. See the following PR (esp. the `try` portions).
https://github.com/spack/spack/pull/18842

**Comment by balay** [comment]
To update: switching the default gcc on the knl box gets ginkgo built [with intel compiler]

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/752293885
