### ISSUE TITLE
precice build error with intel compilers

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#119]
Adding this issue to the tracker. I understand this is a known issue - and is work in progress

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5253320/spack-build-out.txt)

**Comment by balay** [comment]
BTW: precice was disabled on macos for the last release. Is it still unsupported?

**Comment by fsimonis** [comment]
@balay We just [released a bugfix](https://github.com/precice/precice/releases/tag/v2.1.1)  which fixes the compilation error with the intel compiler.
An update to the Spack package will follow shortly.

> BTW: precice was disabled on macos for the last release. Is it still unsupported?

Mac support is close, but still unsupported.

**Comment by balay** [comment]
@fsimonis - I've started with a build on cori@nersc - and I get a build error. Could you look at this?

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5388715/spack-build-out.txt)

**Comment by balay** [comment]
perhaps its a compatibility issue with boost? [I didn't get errors on other test boxes]. Will try older boost and see how that goes.

**Comment by balay** [comment]
switching from boost@1.74.4 to  boost@1.74.0 gets this build working

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5389180/spack-build-out.txt)

**Comment by fsimonis** [comment]
@balay The [latest release of boost](https://www.boost.org/users/download/#live) is `1.74.0`. I am surprised that requesting `1.74.4` didn't result in an error message. The versions in the [spack package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/boost/package.py#L28) looks fine.

**Comment by balay** [comment]
@fsimonis  Sorry, I meant to say - `switching from boost@1.74.0 to boost@1.70.0 gets this build working`

If you can check why it fails with  `boost@1.74.0` [current spack default] - that would be great!

**Comment by fsimonis** [comment]
I build the preCICE spack package successfully with GCC 10.1.0 prior to opening  https://github.com/spack/spack/pull/19264. This included `boost@1.74.0`.

There seems to be an issue when compiling boost.asio 1.74.0 with the Intel compiler: https://github.com/boostorg/asio/issues/362 

Is preCICE the only package affected by this issue?

**Comment by balay** [comment]
Yes -  I didn't see this issue on other test boxes [where default boost@1.74.0] was used.

And on cori - spack flagged the boost@1.74.0 build  as successful. I'll have to redo this build and check the logs.

**Comment by fsimonis** [comment]
@balay Did the new build succeed?

**Comment by balay** [comment]
Yes - I have a successful build on cori with boost@1.70.0 https://github.com/xsdk-project/xsdk-issues/issues/124
