### ISSUE TITLE
datatransferkit build errors with intel on knl

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#120]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5253478/spack-build-out.txt)

**Comment by balay** [comment]
BTW: I noticed
```
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.5", minimum required is "2.6") 
-- PYTHON_EXECUTABLE='/usr/bin/python'
```
If python is a dependency - then it should be exposed in spack package [and obtained from spack]

**Comment by masterleinad** [comment]
Hmm... I can't reproduce locally and the log shows that the `C++14` flag is passed correctly. https://godbolt.org/z/1nzK8v also shows that `ICC 18` should be fine passing the flag but not when omitting `std=c++14`. Maybe the same issue as in https://github.com/xsdk-project/xsdk-issues/issues/118, i.e. the underlying gcc version is too old?

**Comment by balay** [comment]
Yes - this is likely due to the underlying gcc. I'll try to update this test to use newer gcc.

And I think we need a better way to manage this cxx14 dependency [i.e have an appropriate message from spack about unsatisfied dependency - and not at a broken built time. However I don't know how to do this.]

**Comment by masterleinad** [comment]
PythonInterp is a requirement from TriBITS.

**Comment by balay** [comment]
So the incorrect python getting picked up  is a trilinos issue? cc: @keitat
