### ISSUE TITLE
sundials build failure with intel/knl

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#122]
@balos1 the sundials build is failing with intel compilers on knl.

I see the failure on the pipeline you started..

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/774191026

And it fails with my manual build. Attaching the log.

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5378600/spack-build-out.txt)

**Comment by balay** [comment]
And here is the failure on cori

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5388733/spack-build-out.txt)

**Comment by balos1** [comment]
Built successfully for broadwell on Quartz @ LLNL with intel@19.1.2.254.

**Comment by balay** [comment]
Is this with updated sundials? I don't see this in xsdk-0.6.0 branch. I'm still getting failures with sundials-5.4.0
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5424629/spack-build-out.txt)

**Comment by balos1** [comment]
The successful run was with SUNDIALS 5.4.0. I will login into the utk box and try.

**Comment by balay** [comment]
This failure is on a different box (knl) with MKL for blas. Also fails on cori [MKL is also used here]

**Comment by balos1** [comment]
Ah, OK. I will try with MKL.

**Comment by balay** [comment]
this change gets the build working..
```
--- a/var/spack/repos/builtin/packages/sundials/package.py
+++ b/var/spack/repos/builtin/packages/sundials/package.py
@@ -372,7 +372,7 @@ def on_off(varstr):
                 '-DSUPERLUDIST_LIBRARY_DIR=%s'
                 % spec['superlu-dist'].prefix.lib,
                 '-DSUPERLUDIST_LIBRARIES=%s'
-                % spec['blas'].libs,
+                % spec['blas'].libs.joined(';'),
                 '-DSUPERLUDIST_OpenMP=%s'
                 % on_off('^superlu-dist+openmp')
             ])
```

**Comment by balos1** [comment]
Thanks @balay. I suspected it was related to the list of blas libraries from MKL. When our new release comes out later today, I will make sure this fix still works, and if it does, Ill close the issue.
