### ISSUE TITLE
heffte build failure on cori@nersc

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#123]
I'm seeing this failure on cori. @mkstoyanov - could you check on this?

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5388718/spack-build-out.txt)

**Comment by mkstoyanov** [comment]
That's a compiler issue, for some reason Intel thinks that {0, 1, 2} is a valid initialization list for std::array<int, 2>, even though three entries cannot initialize a list of 2 entries.

I guess I need to add a patch that would explicitly call the correct constructors, but I need a machine to reproduce the problem. I'll work on it.

**Comment by balay** [comment]
This issue comes up on cori @ nersc - with:

```
balay@cori08:~/spack> which icc
/usr/common/software/intel/parallel_studio_xe_2020_update2_cluster_edition/compilers_and_libraries_2020.2.254/linux/bin/intel64/icc
balay@cori08:~/spack> icc --version
icc (ICC) 19.1.2.254 20200623
Copyright (C) 1985-2020 Intel Corporation.  All rights reserved.

```

**Comment by balay** [comment]
Switching to `intel-19.0.3.199` gets this build working

**Comment by mkstoyanov** [comment]
Yes, I have been unable to reproduce on any intel 19.0 or prior compiler. I have been trying to get access to intel 19.1, but my guess is that the problem is a compiler bug.

Given the short timeline, the best solution is probably to just keep heFFTe to Intel 19.0 or earlier.

**Comment by balay** [comment]
Note: its `keep xsdk to Intel 19.0 or earlier` - as all packages are usually built with the same compiler. But then - trilinos has other issues with intel compilers - so this intersection (where things work) is pretty small..

**Comment by mkstoyanov** [comment]
We can check for the compiler and disable heFFTe if using intel 19.1, we do that for one of the other packages already (I think slate could use only gcc 6 for some OpenMP reason).

Disabling trilinos is big since lots of packages use it, but disabling heFFTe is probably OK.

**Comment by balay** [comment]
I think the goal of xsdk should be max portability [this might mean working around compiler bugs]

Sure - disabling could be a quick workaround - but that shouldn't be the default go-to.

Some packages can be disabled using variants [we need to improve on this - add variants to all xsdk pacakges]

Yes - we have packages that have builds disabled due to to such issues . But I think they should improve on this.

cc: @ulrikeyang

**Comment by mkstoyanov** [comment]
I agree with you, but I though that the release was due this week. Even if I manage to get access to a machine with intel 19.1, I would still need to make a patch and then a pull-request into spack.

**Comment by balay** [comment]
For this release I'm attempting to switch to `Intel 19.0` for cori test [for heffte] - Still testing. I don't have a full xsdk build yet. [but heffte part works with this switch]

**Comment by mkstoyanov** [comment]
I think this has been resolved.
