### ISSUE TITLE
mfem failure at utk

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#126]
I'm seeing mfem failure on utk box [this worked before - so don't know what the trigger is]

Attaching log

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5465774/spack-build-out.txt)

**Comment by balay** [comment]
This build is using branch `mfem-4.2-dev`. Switching to an earlier snapshot 732c7c755d3cbd2b58765d6f97cf84496e96dd6f gets it working.

**Comment by tzanio** [comment]
Thanks for reporting this @balay.

Just to clarify: 732c7c7 works, but 97ad695 (two commits later) doesn't?

**Comment by balay** [comment]
This is bizarre. Now the latest 97ad695 is also working [I had done `spack clean` between these switches to various snapshots]

So don't understand the reason for the prior failure. Attaching the successful log [with 97ad695]

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5465892/spack-build-out.txt)

**Comment by tzanio** [comment]
I did not see anything obviously wrong in the previous log. If you can reproduce it again, please let us know.

**Comment by balay** [comment]
Is it possible this is a random error - due to a missing make dependency? [this is a parallel build using `make -j64`]

**Comment by tzanio** [comment]
It will be weird, but I guess it is technically possible: the `joule` code in `miniapps/electromagnetics` requires a library, `mfem-common` in `miniapps/common` and the error is that when `joule` is linked it can't find some of the symbols from `mfem-common`.

**Comment by balay** [comment]
I have another failure now.

i.e I've had 2 initial failures (a clean xsdk build overnight, and then a retry immediately).

And then a bunch of (5/6?) successes [a couple of old snapshot builds - and then a few rebuilds of the latest branch]

And now - I have another failure.

Attaching the new log..

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5466117/spack-build-out.txt)

**Comment by v-dobrev** [comment]
I think this maybe due to a missing dependency in the makefiles. I'll take a look if that dependency is really needed and I'll fix it.

**Comment by v-dobrev** [comment]
@balay, I pushed an update -- can you try it to see if the randomness is gone? Thanks!

**Comment by acfisher** [comment]
Thanks for catching this @balay we were really close to releasing.

**Comment by balay** [comment]
I've attempted a bunch of reinstalls of mfem [about 10 or so] - and none of them failed.

**Comment by v-dobrev** [comment]
@balay, the new MFEM version, v4.2 is out -- let me know if you want me to update the `mfem` and `xsdk` packages in  https://github.com/xsdk-project/spack-xsdk (branch `xsdk-0.6.0`) with the new versions.

**Comment by balay** [comment]
@v-dobrev  Sure - one way is to create the MR for this release to spack. Then we can pull in these changes to `xsdk-0.6.0` branch [likely have to revert current changes to mfem in this branch]

And when the MR gets merged to spack - we can again update the `xsdk-0.6.0` branch accordingly

**Comment by v-dobrev** [comment]
I am planning on making a PR (with updates to the `mfem` package) toward https://github.com/spack/spack (branch `develop`) but that will take a bit longer since I want to test it more and add some new variants.

I thought the plan is to merge `xsdk-0.6.0` into `spack/develop` relatively soon -- that is why I thought it will be faster to push the new mfem version to `xsdk-0.6.0` first. However, if you prefer, I can make a small "add new version" PR to `spack/develop` and do the bigger update in another PR later. Do you have a preference?

**Comment by balay** [comment]
For xsdk-0.6.0 into spack/develop relatively soon - we need the mfem@4.2 entry in spack [either directly or through  xsdk-0.6.0  MR]. I usually make separate MRs for package version updates (after testing in xsdk-0.6.0 branch)

For ex:
https://github.com/spack/spack/pull/19682
https://github.com/spack/spack/pull/19682

So my suggestion is to split your work into 2 parts
- first create  mfem@4.2  MR to spack
- all other changes (wrt variants etc) can go into a future separate MR. Obviously we should test these changes with xsdk@0.6.0 of that time [bfore merging to spack/develop]

**Comment by v-dobrev** [comment]
Here is the first (mfem v4.2) PR: https://github.com/spack/spack/pull/19684.

**Comment by balay** [comment]
Thanks! - will add this to xsd-0.6.0 and test.

BTW:

```
+    depends_on('pumi@2.2.3', when='@4.2.0:+pumi')
```

pumi version in xsdk will be 2.2.5 [however mfem+pumi is not enabled - so this is not tested. I'd rather not enable it this late in the cycle]

**Comment by v-dobrev** [comment]
Yes, I saw that in the xsdk package `mfem` does not have `+pumi` -- right now this will not be possible without changes in mfem, since it looks like there was an interface change between v2.2.3 and v2.2.4 of PUMI.

Another connection we may consider enabling next time is `mfem+strumpack` and the new `mfem+slepc` (no such variant in mfem yet -- I'll probably add it in the bigger update I mentioned above).
