### ISSUE TITLE
deal.II failure on summit  requires Intel's TBB.

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#128]
from @luszczek 
```
Has this been built on IBM POWER9?
```

@luszczek perhaps you can attach logs here.

**Comment by bangerth** [comment]
@luszczek Yes, logs and failure messages would be quite useful.

I'm pretty sure that @tjhei has built on Summit.

**Comment by tjhei** [comment]
> I'm pretty sure that @tjhei has built on Summit.

I have not, but @masterleinad probably has.

**Comment by masterleinad** [comment]
I don't have any problems building a standalone deal.II (release 9.2.0) with gcc 6.4.0 on Summit (default configuration). The bundled TBB is used.

**Comment by luszczek** [comment]
There is no issue with gcc 7.4.0

**Comment by bangerth** [comment]
Thanks for checking, @luszczek . I like it when issues that I'm assigned to are closed without my ado ;-)
