### ISSUE TITLE
sundials-5.5.0 failure with intel at utk

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#130]
Attaching log

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5488253/spack-build-out.txt)

**Comment by balay** [comment]
similar failure with gnu build.

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5488523/spack-build-out.txt)

**Comment by balos1** [comment]
This should be fixed with the commit I just pushed up.

**Comment by balay** [comment]
Thanks! the build is now clean  with the above 2 builds.

 Yet to test on other boxes..

**Comment by balay** [comment]
failure on macos [it doesn't have openmp]

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5489054/spack-build-out.txt)

**Comment by balay** [comment]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5489647/spack-build-out.txt)

build log with:
```
-                '-DOPENMP_ENABLE=ON',
+                '-DOPENMP_ENABLE=%s'
+                % on_off('^superlu-dist+openmp'),
```

**Comment by balos1** [comment]
macos issue resolved.
