### ISSUE TITLE
mfem 4.2 fails to patch away Unicode characters on Summit at ORNL

### ISSUE THREAD

**Issue by luszczek** [xsdk-project/xsdk-issues#131]
Is this an issue between Python 2 and 3?

```
==> Error: UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)

spack-xsdk/var/spack/repos/builtin/packages/mfem/package.py:682, in patch:
        680    def patch(self):
        681        # Remove the byte order mark since it messes with some compilers
  >>    682        filter_file(u'\uFEFF', '', 'fem/gslib.hpp')
        683        filter_file(u'\uFEFF', '', 'fem/gslib.cpp')
        684        filter_file(u'\uFEFF', '', 'linalg/hiop.hpp')
```

**Comment by balay** [comment]
I think the workaround is to use python3 with spack. 

However its best to have a better fix for this. perhaps this can be implemented by using a patch file -  instead of adding these unicode chars to `mfem/package.py`

**Comment by luszczek** [comment]
The `filter_file()` is called to remove BOM which in plain ASCII is `'\xff\xfe'` so I replaced it with that.

**Comment by v-dobrev** [comment]
Actually when python 2 reads these files with `open()` (this is what `filter_file` uses), the read string contains the UTF-8 BOM: `'\xef\xbb\xbf'`. In python 3, the read string contains the UTF-16 BOM: `'\ufeff'`. So, for correct behavior, we need to use something like:
```python
   bom = '\xef\xbb\xbf' if sys.version_info < (3,) else u'\ufeff'
   filter_file(bom, '', ...)
```
Note that these files with BOM only exist in MFEM v4.1.

Was this issue already resolved somehow?

**Comment by luszczek** [comment]
To clarify, the issue is with Python 2.7.5. When running Spack with Python 3, the issue goes away. So that's one way to fix it.

Another solution is to not install MFEM version 4.1 and then the `patch()` method is not necessary.

You could add `@when('@4.1')` decorator to `patch()` method to make it version specific.

Finally, if you look at the error, it is not `open()` function in Python. It's the Spack's importer
at `spack/lib/spack/spack/util/imp/imp_importer.py` that complaints:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 38: ordinal not in range(128)`
So the issue is that the package file does not declare text encoding at the top of the file and the import fails.

I suggest using something like `bytes([0xff, 0xfe])` in the call to `filter_file()` that would work across the versions and does not require non-ASCII characters in the code.

**Comment by v-dobrev** [comment]
Okay, if this is not an issue for the xSDK v0.6 release, I'll fix it separately in https://github.com/spack/spack/pull/19748.

**Comment by luszczek** [comment]
As I mentioned in the title: it was only an issue I encountered it only on Summit with their default Python 2. I don't see it with Python 2 on other Linux distribution so I patched my local `mfem/package.py` and described it above.

**Comment by luszczek** [comment]
I had to change the patching for Unicode BOM in MFEM 4.1 with this (so it works for Python 2 and 3):
```python
import codecs
# Remove the byte order mark since it messes with some compilers
for f in ('fem/gslib.hpp', 'fem/gslib.cpp', 'linalg/hiop.hpp'):
  filter_file('0xef0xbb0xbf', '', f)  # save a copy of original
  d = open(f).read().replace(str(codecs.BOM_UTF8), '')
  open(f, 'w').write(d)
```
