### ISSUE TITLE
SLATE fails on LLNL Lassen when building with CUDA

### ISSUE THREAD

**Issue by balos1** [xsdk-project/xsdk-issues#136]
Spack arch: `linux-rhel7-power9le`
Compiler: `gcc@7.3.1`
Command: 
```
spack install -j40 xsdk+cuda~dealii %gcc@7.3.1 ^spectrum-mpi@10.3.0.01rtm3  ^openblas@0.3.5 ^magma cuda_arch=70
```

Error: `nvcc fatal   : Unknown option 'pthread'`

[slate-spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5532280/slate-spack-build-out.txt)

@mgates3

**Comment by balos1** [comment]
Likely the same issue as in #135, which we suspect is this: https://gitlab.kitware.com/cmake/cmake/-/issues/21108. I will retry the build with a different CMake version.

**Comment by balos1** [comment]
The build goes through fine with CMake@3.18.2 and should also be fine with CMake 3.13.0:3.17.x. Versions 3.18.0 and 3.18.1 seem to be the versions that are effected by the bug. 

See discussion on #135.

**Comment by mgates3** [comment]
I believe this is resolved now with the right CMake version.
