### ISSUE TITLE
CI failure heffte@develop

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#138]
@mkstoyanov 

Could you check on heffte@develop build errors?

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1333912727

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6633437/spack-build-out.txt)

**Comment by mkstoyanov** [comment]
@balay 

Should be fixed in the latest develop, thanks for reporting.

**Comment by balay** [comment]
Thanks! The build works now!

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1337858032
