### ISSUE TITLE
hefte@develop on macos

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#140]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6710427/spack-build-out.txt)

```
ref: balay/xsdk-develop, c945a684b2714c332f2c8db9eac6e554e86cc23c
python3 ./bin/spack install --fail-fast -j6 xsdk@develop+trilinos~butterflypack%apple-clang@12.0.0 fflags=-fallow-argument-mismatch
```

**Comment by mkstoyanov** [comment]
So Apple doesn't support the C11 standard!? That's pretty bad:

https://en.cppreference.com/w/c/memory/aligned_alloc

I can isolate the code behind an option, but that's pretty bad on Apple's side.

**Comment by balay** [comment]
I might not have the latest xcode - but this is reasonably new `clang`, and both cxx11 and cxx14 tests from petsc configure succeed.

```
xsdk@kpro ~ % clang++ --version
Apple clang version 12.0.0 (clang-1200.0.32.2)
```

Looks like we might need a `-std=c++11` flag to enable this feature. I should  try this (with heffte build).

And if cxx11 is a requirement for heffte - I believe this should be encoded in spack. I think superlu_dist has some code for it.

**Comment by mkstoyanov** [comment]
heFFTe already sets in CMake:
```
target_compile_features(Heffte PUBLIC cxx_std_11)
```
The `aligned_alloc()` method is part of the C11 standard and not C++11. Must be something not supported on Apple.

I can hide the code behind an option for heFFTe, we probably need to do that for other reasons too.

I will fix this, thanks for reporting.

**Comment by mkstoyanov** [comment]
@balay I just pushed a hot-fix for the heFFTe problem. Let me know when you get a chance to fix it.

**Comment by balay** [comment]
@mkstoyanov I'm seeing a different issue now. Default xcode compilers don't support openmp

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6712078/spack-build-out.txt)

**Comment by mkstoyanov** [comment]
Ugh! FFTW is almost always build with OpenMP support and it is required on many of the big machines.

I'll figure it out, thanks for reporting.

**Comment by mkstoyanov** [comment]
I pushed another fix. Unfortunately `spec['fftw3'].libs` does not expose all the fftw3 libraries in spack, so I had to add a fix in CMake.

@balay The build should be OK now, let me know otherwise.

**Comment by balay** [comment]
Thanks! my manual build works now.
```
ref: balay/xsdk-develop 919926e24e123070858e275c5622410441f91be5

xsdk@kpro spack-xsdk % python3 ./bin/spack install --fail-fast -j6 xsdk@develop~dealii~datatransferkit~alquimia+trilinos %apple-clang@12.0.0 fflags=-fallow-argument-mismatch
<snip>
==> Installing heffte-develop-j6gp7xjojzyr4qh2ktb2ohkoar3do7aj
==> No binary for heffte-develop-j6gp7xjojzyr4qh2ktb2ohkoar3do7aj found: installing from source
==> Warning: Missing a source id for heffte@develop
/Users/xsdk/spack-xsdk/lib/spack/spack/architecture.py:205: UserWarning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@12.0.0 for further details]
  warnings.warn(msg.format(compiler))
==> No patches needed for heffte
==> heffte: Executing phase: 'cmake'
==> heffte: Executing phase: 'build'
==> heffte: Executing phase: 'install'
==> heffte: Successfully installed heffte-develop-j6gp7xjojzyr4qh2ktb2ohkoar3do7aj
  Fetch: 4.57s.  Build: 3.37s.  Total: 7.94s.
<snip>
```
I've started a CI run with heffte enabled - hopefully that should also work.

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1387189519

**Comment by balay** [comment]
> Unfortunately spec['fftw3'].libs does not expose all the fftw3 libraries in spack

Might want to check 23bedc276c0608650ecf4f1b253a72bdf91342da - there is a way to get different library list from a package based on different attributes.

```
$ git grep fftw: |grep spec |grep libs
var/spack/repos/builtin/packages/quantum-espresso/package.py:                fftw_ld_flags = spec['fftw:openmp'].libs.ld_flags
var/spack/repos/builtin/packages/quantum-espresso/package.py:                fftw_ld_flags = spec['amdfftw:openmp'].libs.ld_flags
```
There is also  `spec['fftw3:f,l,q'].libs`.  libs() in fftw/package.py can be updated to get the appropriate list you need [with the appropriate attributes]

**Comment by mkstoyanov** [comment]
Thanks, I will look into those!
