### ISSUE TITLE
ginkgo@1.3.0 failure with +cuda

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#145]
This is a strange failure - I think this worked before. But don't know what change triggered this. [software stack on this test box shouldn't have changed - so that should't be a trigger - but can't say for sure]

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6712002/spack-build-out.txt)

```
ref: develop b1009b48b98219c89233aa46957d078666418324
./bin/spack install --fail-fast -j24 xsdk-examples+cuda target=skylake_avx512 ^xsdk+trilinos  ^magma cuda_arch=60 ^cuda@10.1.243 ^openblas@0.3.5 ^openmpi+cuda ^boost@1.74.0 ^petsc@3.14.1+cuda

-    depends_on('dealii@9.2.0~assimp~python~doc~gmsh+petsc+slepc+mpi~int64+hdf5~netcdf+metis~sundials~ginkgo~symengine', when='@0.6.0 +dealii')
+    depends_on('dealii@9.2.0~assimp~python~doc~gmsh+petsc+slepc+mpi~int64+hdf5~netcdf+metis~sundials~ginkgo~symengine~simplex~arborx', when='@0.6.0 +dealii')
```

**Comment by balay** [comment]
Ah - using `^ginkgo cuda_arch=60` gets the build working

I previously had to use this option with magma - but not ginkgo. Now ginkgo is needing this option aswell. Likely some change on spack side triggered this.

**Comment by hartwiganzt** [comment]
Thanks, @balay! 
@tcojean this is good to know...
