### ISSUE TITLE
superlu-dist@develop build issue with intel compilers

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#146]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6716838/spack-build-out.txt)

```
ref: balay/xsdk-develop c2a3077a9f0fcfa54b82884b7b0adf59132b1d6f
./bin/spack install --fail-fast -j24 xsdk@develop%intel@19.0.3.199~alquimia~trilinos~dealii target=skylake_avx512  ^python%gcc@7.4.0 ^py-numpy%gcc@7.4.0 ^cmake%gcc@7.4.0 ^diffutils
%gcc@7.4.0 ^boost@1.70.0
```

Note: spack installs openblas for this build but superlu-dist is attempting to acces mkl?

```
[+] /data/balay/spack.x/opt/spack/linux-centos7-skylake_avx512/intel-19.0.3.199/openblas-0.3.15-uexvfeawhgwzrathvrddal3keerfryof

     137    In file included from /data/balay/spack.x/spack-stage/spack-stage-superlu-dist-develop-eqd6kvxtl4zacdhaeln22ofhyx7pro43/spack-src/SRC/superlu_dist_version.c(20):
  >> 138    /data/balay/spack.x/spack-stage/spack-stage-superlu-dist-develop-eqd6kvxtl4zacdhaeln22ofhyx7pro43/spack-src/SRC/superlu_defs.h(98): catastrophic error: cannot open source file "mkl.h"
     139      #include "mkl.h"
     140                      ^
     141    
     142    compilation aborted for /data/balay/spack.x/spack-stage/spack-stage-superlu-dist-develop-eqd6kvxtl4zacdhaeln22ofhyx7pro43/spack-src/SRC/superlu_dist_version.c (code 4)
```

**Comment by balay** [comment]
@xiaoyeli Its not clear to me how MKL is used here. If indeed needed - it should have cmake detect MKL correctly - and *not* use : 

```
#ifdef __INTEL_COMPILER
#include "mkl.h"
#endif
```
This patch works for me for both - this issue and #147
https://github.com/spack/spack/commit/70a7048792e7272011ce751f17fcc1cd835d4aef

Ref:
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1378625779
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1378646502

**Comment by xiaoyeli** [comment]
@balay I updated the Master branch, disabled the inclusion of mkl.h.  Please try again.

**Comment by balay** [comment]
Thanks! Started a test pipeline
https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/327688508

**Comment by balay** [comment]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1379460100

The superlu-dist with intel-19 build is clean now
