### ISSUE TITLE
dealii@master build error with intel-18 on knl

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#148]
ref: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1378646502

```
/home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-dealii-master-5qan6yowprztldwf7khqnk2mt3235uvy/spack-src/include/deal.II/base/geometry_info.h(2613): error: expression must have a constant value
        internal::GeometryInfoHelper::Initializers<dim>::unit_normal_vector();
        ^
Note: too few arguments in function call
          detected during:
            instantiation of class "dealii::GeometryInfo<dim> [with dim=1]" at line 330 of "/home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-dealii-master-5qan6yowprztldwf7khqnk2mt3235uvy/spack-src/source/fe/mapping_cartesian.cc"
            instantiation of "void dealii::MappingCartesian<dim, spacedim>::maybe_update_normal_vectors(unsigned int, const dealii::MappingCartesian<dim, spacedim>::InternalData &, std::vector<dealii::Tensor<1, dim, double>, std::allocator<dealii::Tensor<1, dim, double>>> &) const [with dim=1, spacedim=1]" at line 480 of "/home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-dealii-master-5qan6yowprztldwf7khqnk2mt3235uvy/spack-src/source/fe/mapping_cartesian.cc"
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6720785/spack-build-out.txt)

**Comment by marcfehling** [comment]
The entities in `GeometryInfoHelper` have been made functions since release 9.2.0 (https://github.com/dealii/dealii/pull/8703).
@balay Do newer compilers than `intel-18` have this issue as well? Can you confirm that compilation succeeds with `intel-18` with an older release, say 9.1.0?

---

We access `GeometryInfo::unit_normal_vector` [here](https://github.com/dealii/dealii/blob/779a3a250fc869cf98e03e7689db775d0e7cf554/source/fe/mapping_cartesian.cc#L330). I guess that `intel-18` then has trouble with [this line](https://github.com/dealii/dealii/blob/779a3a250fc869cf98e03e7689db775d0e7cf554/include/deal.II/base/geometry_info.h#L2611-L2613).

I'm confused why it complains that the "`expression must have a constant value`". All functions in `internal::GeometryInfoHelper::Initializers` are `constexpr`...



@masterleinad -- Do you have an idea?

**Comment by balay** [comment]
>  Do newer compilers than intel-18 have this issue as well?

yes -intel-19.0.3.199 also gave this error https://github.com/xsdk-project/xsdk-issues/issues/137#issuecomment-869051164

> Can you confirm that compilation succeeds with intel-18 with an older release, say 9.1.0?

Hm xsdk@0.6.0 uses dealii@9.2.0 - and that succeeds with intel-18 compiler

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1378646652
```
==> Installing dealii-9.2.0-rwxtefmv2nxa2jwul5gamctmd3zjbyxs
==> No binary for dealii-9.2.0-rwxtefmv2nxa2jwul5gamctmd3zjbyxs found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/d0/d05a82fb40f1f1e24407451814b5a6004e39366a44c81208b1ae9d65f3efa43a.tar.gz
==> No patches needed for dealii
==> dealii: Executing phase: 'cmake'
==> dealii: Executing phase: 'build'
==> dealii: Executing phase: 'install'
==> dealii: Successfully installed dealii-9.2.0-rwxtefmv2nxa2jwul5gamctmd3zjbyxs
  Fetch: 2.50s.  Build: 2h 10m 37.04s.  Total: 2h 10m 39.54s.
[+] /home/xsdk/builds/rZPizn2W/1/xsdk-project/spack-xsdk/opt/spack/linux-centos7-mic_knl/intel-18.0.2/dealii-9.2.0-rwxtefmv2nxa2jwul5gamctmd3zjbyxs
```

**Comment by marcfehling** [comment]
Has been fixed by https://github.com/dealii/dealii/pull/12515. Can you try to build it again?

We are preparing a new 9.3.1 release that should fix all compatibility problems.

**Comment by balay** [comment]
Thanks! Started a test pipeline

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1389765748

**Comment by balay** [comment]
I'm getting a different error now.

```
/home/xsdk/builds/rZPizn2W/1/xsdk-project/spack-xsdk/spack-stage/spack-stage-dealii-master-b6gild5gxnw6mo6ivpdi4k3oyfctwdmo/spack-src/examples/step-79/step-79.cc(282): error: no instance of constructor "dealii::FESystem<dim, spacedim>::FESystem [with dim=2, spacedim=2]" matches the argument list
            argument types are: (std::pair<std::unique_ptr<dealii::FiniteElement<2, 2>, std::default_delete<dealii::FiniteElement<2, 2>>>, unsigned int>)
           (FESystem<dim>(FE_Q<dim>(1) ^ dim)),
            ^
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6749596/spack-build-out.txt)

**Comment by marcfehling** [comment]
> I'm getting a different error now.

Thank you for your patience and perseverance! :-)

This particular constructor causes issues with Intel compilers prior to 19.0 as its [documentation](https://www.dealii.org/developer/doxygen/deal.II/classFESystem.html#ab7c8b5322c641b984a63b65145dbe67e) states. We should have avoided using it in our tutorial examples. I'll propose a patch.

**Comment by marcfehling** [comment]
https://github.com/dealii/dealii/pull/12533 has been merged. Can you try to build it again?

**Comment by balay** [comment]
Restarted build at https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1393883327
[this build is slow - takes many hours.]

**Comment by bangerth** [comment]
This still seems to fail, but I haven't figured out how one would find what the error message is. Where do you find it?

**Comment by balay** [comment]
For logs, check `Job artifacts` -> `Browse`

The logs can get deleted after a few days - so I usually download (the primary spack build log) and attach to the issue.

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6755795/spack-build-out.txt)

```
icpc: error #10105: ld.gold: core dumped
icpc: warning #10102: unknown signal(700443120)
icpc: error #10106: Fatal error in ld.gold, terminated by unknown
```
Hm  - not sure why the compiler failed. There another build [from today] that got started - will see if this error persists.

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1394311071

**Comment by marcfehling** [comment]
Looks like this new error is similar to the original one of https://github.com/xsdk-project/xsdk-issues/issues/121#issue-707410699.

**Comment by balay** [comment]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1394311071

This restarted build shows a different error now.
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6757069/spack-build-out.txt)


```
/home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-dealii-master-b6gild5gxnw6mo6ivpdi4k3oyfctwdmo/spack-src/include/deal.II/numerics/vector_tools_evaluate.h(276): internal error: assertion failed at: "shared/cfe/edgcpfe/expr.c", line 32950

                    cache.get_mapping(),
                    ^

compilation aborted for /home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-dealii-master-b6gild5gxnw6mo6ivpdi4k3oyfctwdmo/spack-src/source/numerics/data_out_resample.cc (code 4)
```

**Comment by balay** [comment]
This issue has now come up with the intel-19 build aswell but at a different location?
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1397005374

```
/data/xsdkci/VS1mJQ1K/1/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-dealii-master-cnmi4urtlmvhj6x7okkgnvxymxvmdrnm/spack-src/include/deal.II/numerics/vector_tools_evaluate.h(276): internal error: asse\
rtion failed at: "shared/cfe/edgcpfe/expr.c", line 34444

                    cache.get_mapping(),
                    ^
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6760012/spack-build-out.txt)

**Comment by marcfehling** [comment]
It's the [same lines of code](https://github.com/dealii/dealii/blob/43aab5883598bcba818a7bd708a4294ed3e60566/include/deal.II/numerics/vector_tools_evaluate.h#L271-L281) that trigger the internal compiler error with both compilers.

@peterrum - Do you have an idea? Maybe avoiding the lambda function would solve the problem? Or maybe explicitely expecting a reference here, i.e., `&cache.get_mapping()`?

**Comment by marcfehling** [comment]
@balay - You are using the Intel compilers `18.0.2.20180210` and `19.0.0.20190206`. Do these problems also exist in newer versions of the Intel Compiler, like `19.1` or `20`?

**Comment by peterrum** [comment]
I guess one could write:
```
            if (evaluators[cell->active_fe_index()] == nullptr)
              evaluators[cell->active_fe_index()] =
                std::make_unique<FEPointEvaluation<n_components, dim>>(
                  cache.get_mapping(),
                  cell->get_fe(),
                  update_flags);
              auto &evaluator = *evaluators[cell->active_fe_index()];
```
Do we need this on master or the release branch?

**Comment by balay** [comment]
> @balay - You are using the Intel compilers 18.0.2.20180210 and 19.0.0.20190206. Do these problems also exist in newer versions of the Intel Compiler, like 19.1 or 20?

Sorry - due to the complexity of the setup  (wrt getting compatible gcc, python etc working together and not get random non-xsdk dependent package build errors) - I could not use newer version than 19.0.3 on this test box. Wrt  knl with18.0.2 - that box has an old license that limits upgrading to newer version (19.0.3 might work - but I had  issues with IMPI from that install - so had abandoned using it ) 

> Do we need this on master or the release branch?

right now I'm  testing with master - assuming that a newer dealii version [from master] would be the one that gets into xsdk-0.7.0

If you can provide a diff (against master) - I can manually test.

The above change gives me errors. [with intel-19]
```
  >> 920    /data/xsdkci/VS1mJQ1K/1/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-dealii-master-ah3ueeo6a6jl3yr2ei3ngv5dzcozna23/spack-src/include/deal.II/numerics/vector_tools_evaluate.h(273): error: i
            dentifier "cell" is undefined
     921                  if (evaluators[cell->active_fe_index()] == nullptr)
     922                                 ^
     923              detected during:
     924                instantiation of "std::vector<dealii::FEPointEvaluation<n_components, dim, dim, double>::value_type, std::allocator<dealii::FEPointEvaluation<n_components, dim, dim, double>::value_type>
            > dealii::VectorTools::point_values<n_components,dim,spacedim,VectorType>(const dealii::Utilities::MPI::RemotePointEvaluation<dim, spacedim> &, const dealii::DoFHandler<dim, spacedim> &, const Vecto
            rType &, dealii::VectorTools::EvaluationFlags::EvaluationFlags) [with n_components=1, dim=1, spacedim=1,
     925                          VectorType=dealii::LinearAlgebra::distributed::BlockVector<double>]" at line 160 of "/data/xsdkci/VS1mJQ1K/1/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-dealii-master
            -ah3ueeo6a6jl3yr2ei3ngv5dzcozna23/spack-src/source/numerics/data_out_resample.cc"
     926                instantiation of "void dealii::DataOutResample<dim, patch_dim, spacedim>::build_patches(dealii::DataOut<patch_dim, spacedim>::CurvedCellRegion) [with dim=1, patch_dim=1, spacedim=1]" at 
            line 117 of "/data/xsdkci/VS1mJQ1K/1/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-dealii-master-ah3ueeo6a6jl3yr2ei3ngv5dzcozna23/spack-src/source/numerics/data_out_resample.cc"
     927    
  >> 928    /data/xsdkci/VS1mJQ1K/1/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-dealii-master-ah3ueeo6a6jl3yr2ei3ngv5dzcozna23/spack-src/include/deal.II/numerics/vector_tools_evaluate.h(276): internal
             error: assertion failed at: "shared/cfe/edgcpfe/expr.c", line 34444
     929    
     930                        cache.get_mapping(),
     931                        ^
```

**Comment by marcfehling** [comment]
https://github.com/dealii/dealii/pull/12548 has been merged. Can you try to build it again?

**Comment by balay** [comment]
Thanks! both intel 18 and 19 builds are clean now.

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/332954700
