### ISSUE TITLE
dealii failure: xd_l_g74-xsdk

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#149]
new dealii@develop failure
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1387766453

```
/data/xsdkci/VS1mJQ1K/2/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-dealii-master-fni6mga2bt2jyn4jhnhj2jnmv7knetx6/spack-src/source/particles/particle_handler.cc: In member function 'void dealii::Part\
icles::ParticleHandler<<anonymous>, <anonymous> >::post_mesh_change_action()':
/data/xsdkci/VS1mJQ1K/2/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-dealii-master-fni6mga2bt2jyn4jhnhj2jnmv7knetx6/spack-src/source/particles/particle_handler.cc:1917:36: error: 'local_number_of_parti\
cles' was not declared in this scope
       distributed_triangulation || local_number_of_particles == 0,
                                    ^
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6741809/spack-build-out.txt)

A prior build from yesterday was successful - so some change in the last 14h is triggering this?
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1387202757

cc: @marcfehling

**Comment by marcfehling** [comment]
This has been fixed in the meantime: https://github.com/dealii/dealii/pull/12526 has been merged 5 hours ago.

Can you try to build it again?

**Comment by balay** [comment]
Thanks! Restarted the job - it should use current dealii/master

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1389554261

**Comment by balay** [comment]
The test works now!
