### ISSUE TITLE
ginkgo@develop build failures

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#151]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1414978825
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1414978808
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1414978815
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1414978819
```
==> ginkgo: Executing phase: 'install'
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/data/xsdkci/VS1mJQ1K/2/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-ginkgo-develop-pfitbz7j3yewmodksjjmrid5pkq2wksd/spack-build-pfitbz7/test_install'
/data/xsdkci/VS1mJQ1K/2/xsdk-project/spack-xsdk/var/spack/repos/builtin/packages/ginkgo/package.py:135, in setup_build_tests:
        132        with working_dir(self.build_directory):
        133            make("test_install")
        134        smoke_test_path = join_path(self.build_directory, 'test_install')
  >>    135        with working_dir(smoke_test_path):
        136            make("install")
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6797285/spack-build-out.txt)

Yesterday's build didn't have these errors.
https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/334795789

**Comment by balay** [comment]
ping

**Comment by balay** [comment]
I haven't retried this build in the recent past - will redo - and update.

**Comment by upsj** [comment]
probably related to the directory structure changes in https://github.com/ginkgo-project/ginkgo/pull/733, I wasn't aware we were building `develop` anywhere outside our own infrastructure.

**Comment by balay** [comment]
Thanks! The xsdk builds go through now with this patch.
