### ISSUE TITLE
dealii build failure with intel-18/knl

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#153]
```
/homes/intel/18u2/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpiicpc -DDEBUG -Isource/dofs -Iinclud\
e -I/home/xsdk/spack/spack-stage/spack-stage-dealii-master-bfu77vfit4to344sdhkuxtfk5fbukgjb/spack-src/include -I/\
home/xsdk/spack/spack-stage/spack-stage-dealii-master-bfu77vfit4to344sdhkuxtfk5fbukgjb/spack-src/bundled/tbb-2018\
_U2/include -isystem /homes/intel/18u2/compilers_and_libraries_2018.2.199/linux/mkl/include -isystem /home/xsdk/s\
pack-prebuilt/opt/spack/linux-centos7-mic_knl/intel-18.0.2/zlib-1.2.11-o6ee7ca4i2qzgcqacmzg6c7wuz5oj4wy/include -\
isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/boost-1.70.0-zinjxr7arnyvgaxpbdha2upbmedvxr\
4x/include -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/metis-5.1.0-72jqipp7ohludggyxfx\
zt77e3z3abt5r/include -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/trilinos-develop-yqs\
ictnicecu6zjhzklymccjehewpjgd/include -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/hypr\
e-develop-2g2zkrpyefznlx6uvl3zwgk6lve4hlex/include -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/inte\
l-18.0.2/superlu-dist-develop-xgniwgpsuibk5iprslwgp5pfdkc7gtdy/include -isystem /home/xsdk/spack/opt/spack/linux-\
centos7-mic_knl/intel-18.0.2/hdf5-1.10.7-5niceh5tr4vmftbeirtnxlhqzplxzuxw/include -isystem /home/xsdk/spack/opt/s\
pack/linux-centos7-mic_knl/intel-18.0.2/parmetis-4.0.3-kdofcd74blindzrlo3urgqllzq55jy75/include -isystem /home/xs\
dk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/hwloc-2.5.0-tjoths2spgozbcphtd5nn27wnes24dcq/include -isyst\
em /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/suite-sparse-5.3.0-nibs2zcpoek3ap2cgrouke3yduduj\
fq4/include -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/petsc-main-oyglkh4arth7xklmx5q\
zzf2w2pgr5t2g/include -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/gsl-2.7-povgkibl5zdh\
itqube3vwkqpdlqrutlw/include -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/muparser-2.2.\
6.1-yx37rktu4prznuws5tatd7dj5fagss6y/include -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_knl/intel-18.0\
.2/oce-0.18.3-bsbeaawmce6swsitvyk2ttw5gxomyya7/include/oce -isystem /home/xsdk/spack/opt/spack/linux-centos7-mic_\
knl/intel-18.0.2/p4est-2.3.2-l4jkjlmojanfhnkyyq5ippgtdten7qtn/include -isystem /home/xsdk/spack/opt/spack/linux-c\
entos7-mic_knl/intel-18.0.2/slepc-main-vlqj4spjigawdqsbwm77wpuabiyoxwdp/include -fpic -w2 -diag-disable=remark -w\
d21 -wd68 -wd135 -wd175 -wd177 -wd191 -wd193 -wd279 -wd327 -wd383 -wd854 -wd981 -wd1418 -wd1478 -wd1572 -wd2259 -\
wd2536 -wd2651 -wd3415 -wd15531 -wd15552 -wd111 -wd128 -wd185 -wd186 -wd280 -qopenmp-simd -march=knl -mtune=knl -\
Wno-parentheses -O0 -g -gdwarf-2 -grecord-gcc-switches -MD -MT source/dofs/CMakeFiles/obj_dofs_debug.dir/dof_hand\
ler_policy.cc.o -MF source/dofs/CMakeFiles/obj_dofs_debug.dir/dof_handler_policy.cc.o.d -o source/dofs/CMakeFiles\
/obj_dofs_debug.dir/dof_handler_policy.cc.o -c /home/xsdk/spack/spack-stage/spack-stage-dealii-master-bfu77vfit4t\
o344sdhkuxtfk5fbukgjb/spack-src/source/dofs/dof_handler_policy.cc
/home/xsdk/spack/spack-stage/spack-stage-dealii-master-bfu77vfit4to344sdhkuxtfk5fbukgjb/spack-src/source/dofs/dof\
_handler_policy.cc(3691): error: name followed by "::" must be a class or namespace name
                      Assert((stored_index == (numbers::invalid_dof_index)) ||
                      ^
```
cc: @marcfehling

**Comment by bangerth** [comment]
I think we're just missing a `#include`. Working on it!

**Comment by bangerth** [comment]
Can you try again? We think this might be a compiler bug, but it's hard to tell without access to the compiler :-(

**Comment by balay** [comment]
This failure persists
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6859261/spack-build-out.txt)

**Comment by marcfehling** [comment]
It looks like `Intel 18` does not like our `Assert` macros in nested lambda functions. This issue does not occur on more recent compiler versions. We've wrapped the problematic statement around a conditional. Can you try to build again?

**Comment by balay** [comment]
Thanks! The build goes through now.

**Comment by bangerth** [comment]
Thanks for double-checking, @balay !

On a separate note, we really appreciate you running these tests. It is very useful to see these issues early on in our processes and is going to make release processes a lot easier and safer for us! Thank you!

**Comment by balay** [comment]
[@bangerth  adding to this info closed issue]

spack now defaults to boost@1.77.0 - and this broke  some dealii@develop, dealii@9.2.0 builds

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/363551183

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1554299028

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1554517766

I've switched CI for these failed jobs to use boost@1.76.0

**Comment by marcfehling** [comment]
> spack now defaults to boost@1.77.0 - and this broke some dealii@develop, dealii@9.2.0 builds
> 
> https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/363551183
> 
> https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1554299028
> 
> https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1554517766
> 
> I've switched CI for these failed jobs to use boost@1.76.0

We have issues with the current boost release as documented in https://github.com/dealii/dealii/pull/12732. It seems like some of them are boost internal problems that will hopefully be fixed upstream by them.

It's a good idea to use an older version for release `9.2.0`, or in general until we wait for `boost@1.77.1` :)

**Comment by balay** [comment]
@marcfehling thanks for the additional context! 

Boost has always caused issues with xsdk builds. We've been using boost@1.74.0, boost@1.70.0 for some of the other builds due to prior issues.

**Comment by balay** [comment]
> It's a good idea to use an older version for release 9.2.0, or in general until we wait for boost@1.77.1 :)

For now - I have https://github.com/spack/spack/pull/26709 to address this [automatically by spack]
