### ISSUE TITLE
strumpack@develop failure on macos

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#155]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7139019/spack-build-out.txt)

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1574807340

**Comment by pghysels** [comment]
I didn't mean to close this yet, but I think this commit should fix it:
https://github.com/pghysels/STRUMPACK/commit/0383e41cf7e94b6a95decf5b89ecc2a8f747dc56

I'm trying to figure out how to test on my linux machine with libc++ instead of libstdc++.

**Comment by pghysels** [comment]
Ok, this is indeed fixed by  https://github.com/pghysels/STRUMPACK/commit/0383e41cf7e94b6a95decf5b89ecc2a8f747dc56
I have reproduced the problem with clang++-12 and libc++ on Ubuntu 21.04.

**Comment by balay** [comment]
Thanks! I've restarted one of the failed builds:

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1577881880

**Comment by balay** [comment]
strumpack build is now clean!
