### ISSUE TITLE
dealii@9.3.0 build failure on MacOS

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#156]
Not  an xsdk issue - I was building dealii via spack and got this - so figured - I'd file it here.. (I don't really need a fix for this)

 dealii@9.2.0 build works:
`./bin/spack install --fail-fast dealii@9.2.0~sundials~ginkgo~symengine~nanoflann~simplex~arborx~trilinos~gmsh ^mpich ^netlib-lapack ^boost@1.76.0` 

 However dealii@9.3.0 (default) build fails:
`./bin/spack install --fail-fast dealii~sundials~ginkgo~symengine~nanoflann~simplex~arborx~trilinos~gmsh ^mpich ^netlib-lapack ^boost@1.76.0`

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7154680/spack-build-out.txt)
[compilers.yaml.txt](https://github.com/xsdk-project/xsdk-issues/files/7154694/compilers.yaml.txt)

cc: @marcfehling

**Comment by bangerth** [comment]
If I see this right, the error is this:
```
Undefined symbols for architecture x86_64:
  "void dealii::MGLevelGlobalTransfer<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::copy_to_mg<2, double, 2>(dealii::DoFHandler<2, 2> const&, dealii::MGLevelObject<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&, bool) const", referenced from:
      void dealii::MGTransferMatrixFree<2, float>::interpolate_to_mg<double, 2>(dealii::DoFHandler<2, 2> const&, dealii::MGLevelObject<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const in step-66.cc.o
  "void dealii::MGLevelGlobalTransfer<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::copy_to_mg<3, double, 3>(dealii::DoFHandler<3, 3> const&, dealii::MGLevelObject<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&, bool) const", referenced from:
      void dealii::MGTransferMatrixFree<3, float>::interpolate_to_mg<double, 3>(dealii::DoFHandler<3, 3> const&, dealii::MGLevelObject<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const in step-66.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

@peterrum @kronbichler Does this trigger any thoughts?

**Comment by bangerth** [comment]
I think it is really a compiler bug because the missing `copy_to_mg()` function is defined as a template in the `.h` file. But we could work around this by explicitly instantiating it. (At least that's the case for the current dev version. I don't know whether the situation was a real bug in the 9.3 release. Anyone know?)

**Comment by peterrum** [comment]
As far as I see it, it should be instantiated here: https://github.com/dealii/dealii/blob/26f3da826d4b28a9b8996bb745388ef16555e7e8/source/multigrid/mg_level_global_transfer.inst.in#L57-L62

**Comment by kronbichler** [comment]
But this was fixed only after the 9.3.0 release with https://github.com/dealii/dealii/pull/12505, so you need 9.3.1 for making it succeed. We fixed this following #144.

**Comment by balay** [comment]
Ah thanks! And I see `9.3.1` is the version scheduled for xsdk@0.7.0 anyway. Will give that a try!

**Comment by balay** [comment]
9.3.1 builds for me!

I created a PR to add this version to spack

https://github.com/spack/spack/pull/25915

**Comment by bangerth** [comment]
Yes, great. Thanks @balay for adding the patch to spack!

**Comment by balos1** [comment]
This looks like it has been resolved, so closing it. Feel free to reopen if needed.
