### ISSUE TITLE
alquimia@devel build error [with pflotran@devel]

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#159]
@smolins We are preparing for xsdk release - and having issues with building alquimia

Could you take a look at this?

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7307165/spack-build-out.txt)

Also with prior xsdk releases we've been using snapshots for pflotran and alquimia. If possible would be good to sync with actual releases.

cc: @ghammond86 @ulrikeyang

**Comment by smolins** [comment]
Changes in pflotran have not been incorporated in Alquimia and are
currently not supported.  @ghammond86 <https://github.com/ghammond86> may
be able to summarize these changes and we can see whether it is feasible to
incorporate them as part of this release.

**Comment by balay** [comment]
What version of pflotran does alquimia currently work with?

Note: petsc version here is 3.16.0 - so if the currently compatible versions (of pflotran, alquima) work  with this version - we can try use that. So far pfotran@devel did build fine [for the past few months]

**Comment by balay** [comment]
BTW: so far we've been using snapshots - and giving the xsdk release names. For ex: pflotran@xsdk-0.6.0, alquimia@xsdk-0.6.0.

If would be good if we can update to using real versions in spack.

**Comment by smolins** [comment]
What is the timeframe for this release?
I need to fix a couple of things with Alquimia in the near future.
Unfortunately, I have been swamped with other work and have not been able
to keep up. I can discuss with Glenn to see what he can do vs what I need
to do

**Comment by balay** [comment]
> What is the timeframe for this release?

The release schedule is at 
https://docs.google.com/document/d/1ix_Ez5LCv-l2YuwCqFJMlC3sfuOKUBFcac3JSvIMy_E/

so - sooner the better - but hopefully by oct-15.

Sorry - I should have filed this issue earlier. For some reason we are not coordinating well on these 2 packages (wrt co-ordinated releases - and using snapshots instead of releases etc.).

cc:  @ghammond86

[Ah - don't know how to add Glenn to 'participants' list - without having to cc on each message :(]
