### ISSUE TITLE
datatransferkit@3.1-rc3  build failure on macos

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#160]
build log attached

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7307920/spack-build-out.txt)

**Comment by masterleinad** [comment]
Hmmm... the missing symbols look like
```
  "Tpetra::DistObject<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::doTransfer(Tpetra::SrcDistObject const&, Tpetra::Details::Transfer<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, char const*, Tpetra::DistObject<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::ReverseOption, Tpetra::CombineMode, bool)", referenced from:
      vtable for Tpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >
```
and are thus coming from `Trilinos` not from `DataTransferKit` directly. Is there any chance that the build configuration for `Trilinos` is different on `macOS`?

**Comment by balay** [comment]
> are thus coming from Trilinos not from DataTransferKit directly. Is there any chance that the build configuration for Trilinos is different on macOS?

I don't know if its different on the spack side.

Its the same on xsdk side.

Linux build:
``` 
./bin/spack install --fail-fast -j24 xsdk+cuda~alquimia target=skylake_avx512 ^magma cuda_arch=60 ^heffte cuda_arch=60 ^ginkgo cuda_arch=60 ^sundials cuda_arch=60 ^cuda@10.1.243 ^openblas@0.3.5 ^openmpi+c
uda ^boost@1.76.0
```
MacOS build:
```
python3 ./bin/spack install --fail-fast -j6 xsdk~alquimia %apple-clang@12.0.0 fflags=-fallow-argument-mismatch ^boost@1.76.0
```

Adding trilinos [cmake] build logs here [for both]

[linux-spack-build-01-cmake-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7311976/linux-spack-build-01-cmake-out.txt)
[macos-spack-build-01-cmake-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7311985/macos-spack-build-01-cmake-out.txt)

cc: Keita and Jim to this issue

**Comment by aprokop** [comment]
The failure is only on MacOS, but Linux is fine?

**Comment by balay** [comment]
> The failure is only on MacOS, but Linux is fine?

yes - the above linux log is from a successful build.

**Comment by masterleinad** [comment]
Does datatransferkit@3.1-rc2 work instead?

**Comment by balay** [comment]
yes - datatransferkit@3.1-rc2 builds fine on macos

**Comment by masterleinad** [comment]
We are happy to take datatransferkit@3.1-rc2 for the release if that works better.
