### ISSUE TITLE
dealii@9.3.1 build failure on knl/intel-18

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#161]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7312134/spack-build-out.txt)

cc: @marcfehling

**Comment by masterleinad** [comment]
Yes, the `(FESystem<dim>(FE_Q<dim>(1) ^ dim))` doesn't work for (older) `Intel` compilers. Maybe, we should disable step-79 for `Intel`.

**Comment by bangerth** [comment]
Let's just fix step-79 for now, that would be easier. @masterleinad -- do you want me to write a patch or would you like to?

**Comment by masterleinad** [comment]
I can do that.

**Comment by masterleinad** [comment]
See https://github.com/dealii/dealii/pull/12805.

**Comment by marcfehling** [comment]
See also https://github.com/xsdk-project/xsdk-issues/issues/148#issuecomment-872382060.

Thank you @masterleinad :)

**Comment by masterleinad** [comment]
@balay Can you check if https://github.com/dealii/dealii/tree/dealii-9.3 fixes all errors?

**Comment by bangerth** [comment]
Thanks indeed!

**Comment by balay** [comment]
Yes - branch `dealii-9.3 ` builds fine for me on this box.

**Comment by balay** [comment]
@bangerth [following up here as we switched to using  https://github.com/dealii/dealii/tree/dealii-9.3 here]

Currently I'm using https://github.com/spack/spack/commit/1fc589f85dc5e160068da9ba891c31fc40ad5056 in place for 9.3.2

Perhaps its a good time to tag and release 9.3.2? [so that its usable from xsdk-0.7.0 release?] 

The outstanding issue so far is https://github.com/xsdk-project/xsdk-issues/issues/164 - but then this likely  won't need fixes in dealii sources..

**Comment by bangerth** [comment]
@balay We've been talking about including a couple more patches into 9.3.2, but I have to admit that I'm not entirely up to date. @tamiko and @kronbichler have been doing the release planning lately, and I'd have to let them speak about whether it's a good time to tag the release.

**Comment by marcfehling** [comment]
[deal.II 9.3.2](https://github.com/dealii/dealii/releases/tag/v9.3.2) has been released on Nov 8. @balay -- would you give that version a try?

**Comment by balay** [comment]
> deal.II 9.3.2 has been released on Nov 8. @balay -- would you give that version a try?

yes - we tested (builds)  and used this version with xsdk@0.7.0

```-bash-4.2$ ./bin/spack find dealii
==> 1 installed package
-- linux-centos7-mic_knl / intel@18.0.2 -------------------------
dealii@9.3.2
```
