### ISSUE TITLE
trilinos build fails when cuda is enabled with superlu-dist

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#162]
Ref:
```
diff --git a/var/spack/repos/builtin/packages/xsdk/package.py b/var/spack/repos/builtin/packages/xsdk/package.py
index 3e65663cd8..0c1a52bd63 100644
--- a/var/spack/repos/builtin/packages/xsdk/package.py
+++ b/var/spack/repos/builtin/packages/xsdk/package.py
@@ -119,8 +119,8 @@ def xsdk_depends_on(*args, cuda_var='', rocm_var='', **kwargs):
     xsdk_depends_on('mfem@3.4.0+mpi+superlu-dist+petsc+sundials+examples+miniapps', when='@0.4.0')
     xsdk_depends_on('mfem@3.3.2+mpi+superlu-dist+petsc+sundials+examples+miniapps', when='@0.3.0')
 
-    xsdk_depends_on('superlu-dist@develop', when='@develop')
-    xsdk_depends_on('superlu-dist@7.1.1', when='@0.7.0')
+    xsdk_depends_on('superlu-dist@develop', when='@develop', cuda_var='cuda')
+    xsdk_depends_on('superlu-dist@7.1.1', when='@0.7.0', cuda_var='cuda')
     xsdk_depends_on('superlu-dist@6.4.0', when='@0.6.0')
     xsdk_depends_on('superlu-dist@6.1.1', when='@0.5.0')
     xsdk_depends_on('superlu-dist@6.1.0', when='@0.4.0')
```
`./bin/spack install --fail-fast -j24 xsdk@0.7.0+cuda cuda_arch=60 target=skylake_avx512  ^cuda@10.1.243 ^openblas@0.3.5 ^openmpi+cuda`

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7394214/spack-build-out.txt)

**Comment by balay** [comment]
Ok - tried also enabling trilinos+cuda - but now get build error with phist

ref:
```
-    xsdk_depends_on('trilinos@develop+hypre+superlu-dist+hdf5~mumps+boost~suite-sparse+tpetra+nox+ifpack2+zoltan+zoltan2+amesos2~exodus~dtk+intrepid2+shards+stratimikos gotype=int cxxstd=14',
-                    when='@develop +trilinos')
-    xsdk_depends_on('trilinos@13.2.0+hypre+superlu-dist+hdf5~mumps+boost~suite-sparse+tpetra+nox+ifpack2+zoltan+zoltan2+amesos2~exodus~dtk+intrepid2+shards+stratimikos gotype=int cxxstd=14',
-                    when='@0.7.0 +trilinos')
+    xsdk_depends_on('trilinos@develop+hypre+superlu-dist+hdf5~mumps+boost~suite-sparse+tpetra+nox+ifpack2+zoltan+zoltan2+amesos2~exodus~dtk+intrepid2+shards+stratimikos gotype=int cxxstd=14 ',
+                    when='@develop +trilinos', cuda_var='cuda')
+    xsdk_depends_on('trilinos@13.2.0+hypre+superlu-dist+hdf5~mumps+boost~suite-sparse+tpetra+nox+ifpack2+zoltan+zoltan2+amesos2~exodus~dtk+intrepid2+shards+stratimikos gotype=int cxxstd=14 ',
+                    when='@0.7.0 +trilinos', cuda_var='cuda')
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7394416/spack-build-out.txt)

**Comment by jthies** [comment]
to be honest I have never built phist with trilinos+cuda via spack. Is there an example of a package doing that? I would have to use the nvcc_wrapper included in Trilinos to compile phist, I think, right? But it's not a compiler supported by spack. So I would have to get it's path inside the phist/package.py and explicitly set the CMAKE_CXX_COMPILER. Then again, that one is already set to mpicxx...

**Comment by jthies** [comment]
I found that the nalu-wind package seems to solve this by depends_on('kokkos-nvcc-wrapper'), but I wonder if this is the best way to do it, and how the integration with mpi works (which CMAKE_CXX_COMPILER I have to set).

**Comment by balay** [comment]
Attempted a clean build with superlu_dist+cuda, trilinos+cuda - (with trilinos develop) and  get a dtk buid error now.
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7401999/spack-build-out.txt)

**Comment by masterleinad** [comment]
https://github.com/kokkos/kokkos/issues/3561 is likely related. I don't think we actually support `Cuda` in `DTK`. Also, it's unexpected to not see a CUDA architecture flag in the compile lines.
Which `CUDA` architecture was activated in `Trilinos/Kokkos`?

**Comment by balay** [comment]
> Which CUDA architecture was activated in Trilinos/Kokkos?

Here is the build command
```
balay@xsdk:/data/balay/spack.z>./bin/spack spec xsdk@0.7.0+cuda cuda_arch=60 target=skylake_avx512  ^cuda@10.1.243 ^openblas@0.3.5 ^openmpi+cuda
            ^trilinos@13.2.0%gcc@7.4.0~adios2+amesos+amesos2+anasazi+aztec~basker+belos+boost~chaco~complex+cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~e
xodus+explicit_template_instantiation~float+fortran~gtest+hdf5+hypre+ifpack+ifpack2~intrepid+intrepid2~ipo~isorropia+kokkos~mesquite~minitensor+ml+mpi+muelu~mumps+nox~openmp~phalanx~piro~python~rol~rythmos+sacad
o~scorec+shards+shared~shylu~stk~stokhos+stratimikos~strumpack~suite-sparse~superlu+superlu-dist~teko~tempus+tpetra~trilinoscouplings+wrapper~x11+zoltan+zoltan2 build_type=RelWithDebInfo cuda_arch=60 cxxstd=14 g
otype=int arch=linux-centos7-skylake_avx512

    ^datatransferkit@3.1-rc3%gcc@7.4.0~external-arborx~ipo~openmp+serial+shared build_type=RelWithDebInfo arch=linux-centos7-skylake_avx512
```

**Comment by balay** [comment]
Sundials also fails with trilinos+cuda

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7402241/spack-build-out.txt)

**Comment by jthies** [comment]
I think you should explicitly set cuda_arch, it defaults to 'none' otherwise. Maybe it would help to try to resolve this for one simple package first, I don't think there is any package in spack right now that will build with and use trilinos+cuda, right? So the Trilinos people could maybe provide an example package.py-file (@keitat). For phist I would need to know where the nvcc_wrapper script is located, and how to portably define CMAKE_CXX_COMPILER to be the MPI-wrapper with the nvcc-wrapper underneath.

**Comment by balay** [comment]
> I think you should explicitly set cuda_arch, it defaults to 'none' otherwise

`cuda_arch=60` got set above

` I don't think there is any package in spack right now that will build with and use trilinos+cuda, right? `

yes. Dealii also failed similarly cc: @bangerth.

This started off with superlu_dist+cuda - and I tried trilinos+cuda to get that working. And that triggered dtk, sundials, phist and dealii failures.

Won't enable this for xsdk-0.7.0 - so hopefully we can resolve this before the next release.

Wrt superlu-dist - @xiaoyeli - perhaps superlu_dist is exposing cuda  its public includes. So the fix could be to avoid that (if possible) to get `superlu-dist+cuda trilinos~cuda` working.

**Comment by bangerth** [comment]
I have no experience with CUDA. Let me tag @masterleinad and @Rombur .

**Comment by masterleinad** [comment]
For the `DTK` build, I'm surprised not to see `arch=sm_60` (this flag should be exported/used by `Trilinos`/`Kokkos` if building for `cuda_arch=60`). Also, we need to make sure that all flles containing `Kokkos` files need to be compiled with `nvcc_wrapper` (unless `clang` is used). I guess `mpicxx` is pointing to that.

**Comment by Rombur** [comment]
I've never tried `dealii` with `trilinos+cuda`. You might need to use `dealii+cuda` but there is no guarantee it will work.

**Comment by keitat** [comment]
@masterleinad Does DTK import Kokkos' make_config?

**Comment by masterleinad** [comment]
It basically uses `Trilinos` as TPL using `TriBITS` and imports `KokkosConfig.cmake`, see https://github.com/ORNL-CEES/DataTransferKit/blob/691d5a1540f7cd42141a3b3d2a7c8370cbc3560a/CMakeLists.txt#L60-L88.

**Comment by bartlettroscoe** [comment]
I suspect that updating the version of Trilinos with updated TriBITS will INTERFACE_COMPILER_OPTIONS through the targets now that PUBLIC was added to target_link_libraries() propagation.

Also, an updated version of TriBITS will be merged to 'master' and snapshoted to Trilinos 'develop' that will completely switch over to modern CMake targets but that should not be needed to propagate all of the INTERFACE properties set on Kokkos library targets.

**Comment by keitat** [comment]
With the current version of TriBITS, we need a workaround to get nvcc_wrapper information.

**Comment by jthies** [comment]
@balay could you try it again now with phist@develop?
I added the corresponding patch to spack in this PR: https://github.com/spack/spack/pull/27278

**Comment by balay** [comment]
> @balay could you try it again now with phist@develop?

I retried this build with ` phist@develop` (and trilinos+cuda) and this builds fine for me.

`./bin/spack install -j24 xsdk+cuda target=skylake_avx512 cuda_arch=60 ^cuda@10.1.243 ^openmpi ^hwloc@2.5.0`

```
==> Installing phist-develop-7lxruecspuxvf4xs3up6g7nvl4py5434
==> No binary for phist-develop-7lxruecspuxvf4xs3up6g7nvl4py5434 found: installing from source
==> Warning: Missing a source id for dealii@9.3.2
==> Warning: Missing a source id for phist@develop
==> Warning: Missing a source id for xsdk@0.7.0
==> Ran patch() for phist
==> phist: Executing phase: 'cmake'
==> phist: Executing phase: 'build'
==> phist: Executing phase: 'install'
==> phist: Successfully installed phist-develop-7lxruecspuxvf4xs3up6g7nvl4py5434
  Fetch: 6.42s.  Build: 2m 13.96s.  Total: 2m 20.38s.
[+] /data/balay/spack.y/opt/spack/linux-centos7-skylake_avx512/gcc-7.4.0/phist-develop-7lxruecspuxvf4xs3up6g7nvl4py5434
```

**Comment by balay** [comment]
BTW: when I switch from cuda@10.1.243 tocuda@11.2.0 [also switch from gcc-7.4.0 to gcc-9.2.0 - with this change] - `trilinos+cuda` build breaks (when` superlu-dist+cuda` is enabled)

`./bin/spack install -j24 xsdk+cuda target=skylake_avx512 cuda_arch=70 ^cuda@11.2.0 ^openmpi`

```
/data/balay/spack.zz/spack-stage/spack-stage-trilinos-13.2.0-ysen3tttorg3k5t5fghcn2gto3xlmxay/spack-src/packages/amesos2/src/Amesos2_SolverCore_def.hpp(153): here

/nfs/apps/spacks/2021-02-09/opt/spack/linux-centos7-x86_64/gcc-7.3.0/cuda-11.2.0-ikruu5mo6dtt3avvmwsejouqhxu4btdm/bin/../targets/x86_64-linux/include/cuda_bf16.hpp(238): error: more than one instance of overloaded function "SLUD::operator++" has "C" linkage
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7501843/spack-build-out.txt)
