### ISSUE TITLE
dealii 9.3.2 package relocation overflow for POWER9 with GCC 8.3.1 with or without CUDA

### ISSUE THREAD

**Issue by luszczek** [xsdk-project/xsdk-issues#164]
I get the message `relocation overflow try relinking with a smaller --stub-group-size` for the source and header files. Using CUDA makes no differenc
[spack-build-out_dealii.txt.gz](https://github.com/xsdk-project/xsdk-issues/files/7461675/spack-build-out_dealii.txt.gz)
e.

**Comment by balay** [comment]
@luszczek 
```
/tmp/luszczek/spack-stage/spack-stage-dealii-9.3.2-xe2q3bsmrbgdym2mxscnytnsc4g2ruio/spack-src/include/deal.II/matrix_free/shape_info.h:113: error: relocation overflow
try relinking with a smaller --stub-group-size
```
Perhaps summit admins have seen this error before - and know the appropriate `--stub-group-size` option to use here?

Presumably that can be used with something like:

`spack install xsdk ^dealii ldflags="-Wl,--stub-group-size=-1"`

**Comment by bangerth** [comment]
Oh, I have no idea how to address this. @tamiko: Does cmake have ways to address this?

**Comment by masterleinad** [comment]
Possibly, it's an issue with `ld.gold`(see https://sourceware.org/bugzilla/show_bug.cgi?id=20878). Can you try building with the `CMake` flag `DEAL_II_COMPILER_HAS_FUSE_LD_GOLD=OFF`?

**Comment by luszczek** [comment]
After building with `DEAL_II_COMPILER_HAS_FUSE_LD_GOLD=OFF` I get new relocation message: `relocation truncated to fit: R_PPC64_REL24 (stub) against symbol ...` I wonder if it is related to a specific build of the linker on POWER9 Linux
[spack-build-out_dealii.txt.gz](https://github.com/xsdk-project/xsdk-issues/files/7470859/spack-build-out_dealii.txt.gz)

**Comment by tamiko** [comment]
The deal.II build system should pick up `LDFLAGS` environment variables automatically. Alternatively, one can set linker flags via `-DDEAL_II_LINKER_FLAGS="..."`. In order to switch between ld.gold and ld.bdf one can do pretty much what @masterleinad suggested.

@luszczek Did you try setting a different stubs size?
