### ISSUE TITLE
slate build error with intel@18 on knl.

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#165]
Attempting to enable strumpack+cuda - for this - attempted to remove slate restriction to 'when =%gcc@6.0'

this gives a build error with intel@18

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/7523564/spack-build-out.txt)

ref: https://github.com/spack/spack/commit/b4a53791cd169b3829d4b1de8fece5aff08bfc0a

**Comment by pghysels** [comment]
This
https://www.intel.com/content/www/us/en/developer/articles/news/c17-features-supported-by-c-compiler.html
shows that Intel@18 is missing several c++17 features. 
I think you would need at least Intel@19.1.0, or an older version of libstdc++?
But there is a 
`conflicts('%intel@19:', msg='Does not currently build with icpc >= 2019')`
in slate's spack.
Probably the best solution would be to figure out how to make it compile with icpc >= 2019?
Are there other xsdk packages that require c++17 (and work with Intel@18)?

**Comment by mgates3** [comment]
I think the last release of SLATE probably doesn't work with icpc. We've fixed some issues, but I haven't really tested with icpc to see if it works. We have been testing with Cray compilers on Spock. We'll work on it, but don't expected fixes for the xSDK release.

**Comment by balos1** [comment]
Closing issue as stale.
