### ISSUE TITLE
alquimia@develop build failure

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#170]
ref: ./bin/spack install --fail-fast -j16 xsdk@develop%gcc@9.2.0~trilinos

[with sundials, plasma commented out]

```
/data/balay/spack.x/spack-stage/spack-stage-alquimia-develop-psq4h7royt3hcy7esvvlshiccjy23gdi/spack-src/alquimia/pflotran_alquimia_interface.F90:67:6:

   67 |   use Material_Aux_class, only : material_auxvar_type
      |      1
Fatal Error: Cannot open module file 'material_aux_class.mod' for reading at (1): No such file or directory
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/8963193/spack-build-out.txt)

cc: @smolins

**Comment by smolins** [comment]
What version of pflotran is being used for this?
Thanks

@balay

**Comment by balay** [comment]
@smolins , updating this issue to whats' currently observed.

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3161006120
```
/data/xsdkci/VS1mJQ1K/0/xsdk-project/spack-xsdk/var/spack/repos/builtin/packages/alquimia/package.py:54, in cmake_args:
         51            "-DXSDK_WITH_PFLOTRAN:BOOL=ON",
         52            # This is not good.
         53            # It assumes that the .a file exists and is not a .so
  >>     54            "-DTPL_PFLOTRAN_LIBRARIES=%s" % (spec["pflotran"].prefix.lib + "/libpflotranchem.a"),
         55            "-DTPL_PFLOTRAN_INCLUDE_DIRS=%s" % (spec["pflotran"].prefix.include),
         56            "-DTPL_ENABLE_PETSC:BOOL=ON",
         57            "-DPETSC_EXECUTABLE_RUNS=ON",
See build log for details:
```

This is `alquimia@1.0.10`  with `pflotran@4.0.1`

cc: @ghammond86

**Comment by balay** [comment]
Ah..
> Error: KeyError: 'No spec with name pflotran in alquimia@1.0.10%gcc@9.2.0~ipo+shared

Its an issue with spack spec change I had  for  alquimia@1.0.10.

Its fixed now and the build goes through [at-least on this  one test box]

**Comment by balos1** [comment]
Closing as the build is going through now.
