### ISSUE TITLE
plasma@develop build failure

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#171]
ref: ./bin/spack install --fail-fast -j16 xsdk@develop%gcc@9.2.0~trilinos

```
CMake Error at CMakeLists.txt:135 (add_library):
  Cannot find source file:

    compute/scamax.c

...
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/8963324/spack-build-out.txt)

**Comment by luszczek** [comment]
It seems it was a build out of the repo so it needs to run `tools/generate_precisions.py` first before running CMake.

**Comment by luszczek** [comment]
Submitted upstream: https://github.com/spack/spack/pull/31668

**Comment by balos1** [comment]
This seems to be working now with the patch, so I am closing.
