### ISSUE TITLE
mfem@develop does not build with sundials@develop

### ISSUE THREAD

**Issue by balos1** [xsdk-project/xsdk-issues#173]
Will be fixed with https://github.com/mfem/mfem/pull/3170. This is not currently causing a build failure as the xsdk CI is using sundials@5.8.0 instead.

**Comment by balos1** [comment]
Testing again now that mfem/mfem#3170 is merged. See https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/666264944.

**Comment by v-dobrev** [comment]
Currently, `mfem` has `~sundials` variant in https://gitlab.com/xsdk-project/spack-xsdk/-/tree/xsdk. I'll update that in a moment. I may also need to update the `mfem` package to allow the newer `sundials` versions.

**Comment by balos1** [comment]
@v-dobrev I have done it now https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/666277653.

**Comment by balos1** [comment]
Passing now https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/667123763
