### ISSUE TITLE
 sundials-6.4.0 build error -> trilinos?

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#177]
```
  >> 334    CMake Error at cmake/macros/SundialsCMakeMacros.cmake:89 (message):
     335      ************************************************************************
     336
     337      ERROR: SUNDIALS interface to Trilinos is not functional.
     338
     339      ************************************************************************
     340    Call Stack (most recent call first):
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/9675880/spack-build-out.txt)

ref: xsdk@utk: ./bin/spack install -j24 xsdk@0.8.0+cuda cuda_arch=70 ^cuda@11.6.0 ^openmpi

**Comment by balos1** [comment]
@jwillenbring Is Trilinos for sure going with v14 for xSDK? Also, do you know what the status of Kokkos 4.0 is?

**Comment by masterleinad** [comment]
We are trying to create a release candidate for the Kokkos 4.0 release within the next few weeks.

**Comment by jwillenbring** [comment]
@balos1 Trilinos is not for sure goign with v14 for xSDK. There are some serious blockers for that release that remain. That said, I thought some other xSDK packages were in a place where they needed at least the master branch version of Trilinos for the next release, so I thought we couldn't go back to the previous releases due to some interface changes.

**Comment by masterleinad** [comment]
Not updating would certainly help `DataTransferKit` in #175.

**Comment by balos1** [comment]
@jwillenbring SUNDIALS breaks with trilinos@master. I believe the updated interface from Trilinos to SuperLU_DIST v8 is what you are remembering w.r.t. some packages needing changes in the Trilinos master branch. Not updating to v14 right now would be much better for SUNDIALS.

**Comment by jwillenbring** [comment]
So perhaps we should look at using the old release, but backporting the support for SuperLU_DIST 8?

**Comment by balay** [comment]
I'll switch over to `trilinos@13.4.0` and see how that goes.

**Comment by jwillenbring** [comment]
@balay 

I put up a PR that would add the SuperLU_DIST 8 support to the 13.4 release branch. It might be worth pullling in the associated branch and seeing if that looks better than the current release branch, depending on what you run into.

PR: https://github.com/trilinos/Trilinos/pull/11134

Branch: jwillenbring:trilinos-13-4-superlu-dist-8-patch

**Comment by balos1** [comment]
This seems to no longer be an issue with Trilinos going back to 13.4.0. Closing, but we can reopen or open a new issue if it does persist.
