### ISSUE TITLE
dealii-9.4.0 build error -> trilinos?

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#178]
```
     672    --   TRILINOS_LIBRARIES: *** Required variable "TRILINOS_LIBRARY_TeuchosCore::teuchoscore" set to NOTFOUND ***
     673    --   TRILINOS_LIBRARIES: *** Required variable "TRILINOS_LIBRARY_KokkosAlgorithms::kokkosalgorithms" set to NOTFOUND ***
     674    --   TRILINOS_LIBRARIES: *** Required variable "TRILINOS_LIBRARY_KokkosContainers::kokkoscontainers" set to NOTFOUND ***
     675    --   TRILINOS_LIBRARIES: *** Required variable "TRILINOS_LIBRARY_KokkosCore::kokkoscore" set to NOTFOUND ***
     676    -- Could NOT find TRILINOS
     677    -- DEAL_II_WITH_TRILINOS has unmet external dependencies.
  >> 678    CMake Error at cmake/macros/macro_configure_feature.cmake:112 (MESSAGE):
     679
     680
     681      Could not find the trilinos library!
     682
     683      Please ensure that a suitable trilinos library is installed on your
     684      computer.
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/9675913/spack-build-out.txt)

ref: xsdk@utk: ./bin/spack install -j24 xsdk@0.8.0+cuda cuda_arch=70 ^cuda@11.6.0 ^openmpi

**Comment by bangerth** [comment]
@tamiko Can you help?

**Comment by bangerth** [comment]
@balay  Do you still have the two files listed at the bottom,
```
See also "/data/balay/spack/spack-stage/spack-stage-dealii-9.4.0-tozsg5fq2epkfddqd7lnimxjdvhi2vvf/spack-build-tozsg5f/CMakeFiles/CMakeOutput.log".
See also "/data/balay/spack/spack-stage/spack-stage-dealii-9.4.0-tozsg5fq2epkfddqd7lnimxjdvhi2vvf/spack-build-tozsg5f/CMakeFiles/CMakeError.log".
```
?

**Comment by balay** [comment]
[CMakeError.log](https://github.com/xsdk-project/xsdk-issues/files/9676444/CMakeError.log)
[CMakeOutput.log](https://github.com/xsdk-project/xsdk-issues/files/9676445/CMakeOutput.log)

Note: this is with trilinos master branch - [i.e upcoming 14.0.0 release]

**Comment by tamiko** [comment]
Trilinos switched to a new import target layout for the upcoming 14.0.0 release that deal.II currently doesn't support. I hope to get around fixing this within the next couple of weeks.

**Comment by balay** [comment]
Due to build issues with various trilinos dependent pkgs (wiht 14.0.0)  - we are trying out trilinos@13.4.0 - as per https://github.com/xsdk-project/xsdk-issues/issues/177 - so that should resolve this dealii issue as well.

**Comment by balos1** [comment]
This is building with trilinos@13.4.0, so I am closing https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3175131930#L827.
