### ISSUE TITLE
hiop-0.6.2 build failure on Mac

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#181]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3108965071

```
>> 50     CMake Error at src/CMakeLists.txt:21 (add_library):
     51       Target "hiop_static" links to target "OpenMP::OpenMP_CXX" but the
             target
     52       was not found.  Perhaps a find_package() call is missing for an I
            MPORTED
     53       target, or an ALIAS target is missing?
...
```

[spack-build-out(6).txt](https://github.com/xsdk-project/xsdk-issues/files/9685872/spack-build-out.6.txt)

BTW: I'm not sure if this is the release to use for xsdk@0.8.0 - or something newer..

**Comment by cnpetra** [comment]
@balay can you please also assign @CameronRutherford ?

We'll take a look. That is a good release. We release HiOp 0.7.0 today and should use it with the latest xsdk release.

**Comment by balay** [comment]
Ok - will update to testing with 0.7.0 

github only allows 'project members' to be assignees :( . 

I guess I should add  @CameronRutherford to xsdk project.

**Comment by cameronrutherford** [comment]
https://github.com/LLNL/hiop/blob/develop/CMakeLists.txt#L184 - the logic for including OpenMP is probably flawed here. I imagine that we should instead check to see if we are using RAJA, and if the exported RAJA configuration includes the RAJA OpenMP target, and then run `find_package(OpenMP)` based on that.

See https://github.com/LLNL/camp/issues/110#issuecomment-1238620247 for some more discussion. Seems like this is an issue when building on HIP and on MacOS...

**Comment by cnpetra** [comment]
Satish (@balay), could you please take a look at https://github.com/LLNL/hiop/pull/562 and comment? Hopefully it (partially) fixes the issue you reported? We had some quite long internal debate on OpenMP and Apple (Clang-related issues) and that is "a" solution. Better solutions may exist and let us know of any suggestions.

**Comment by balay** [comment]
@cnpetra yes - the macos build does succeed with this fix. Thanks!
