### ISSUE TITLE
trilinos-14.0.0 build error on MacOS -> hypre

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#182]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3108965071

```
 >> 3310    Undefined symbols for architecture x86_64:
     3311      "_HYPRE_MGRSetFLevelRelaxType", referenced from:
     3312          __GLOBAL__sub_I_Ifpack_Hypre.cpp in Ifpack_Hypre.cpp.o
     3313      "_HYPRE_MGRSetLevelSmoothOrder", referenced from:
     3314          ___cxx_global_var_init.1 in Ifpack_Hypre.cpp.o
     3315    ld: symbol(s) not found for architecture x86_64
  >> 3316    clang: error: linker command failed with exit code 1 (use -v to se
             e invocation)
```

[spack-build-out(8).txt](https://github.com/xsdk-project/xsdk-issues/files/9685907/spack-build-out.8.txt)

**Comment by jwillenbring** [comment]
Was this known to work previously? Has anything changed related to these symbols in Hypre?

**Comment by ulrikeyang** [comment]
I am including Daniel here, so he can answer or communicate regarding this.

**Comment by ulrikeyang** [comment]
Hi Jim,
I took a look and it appears those symbols were prototypes that were either removed or renamed in hypre a while back. It has been in there for sometime, so I am surprised it is just showing up now. In any case, I have cleaned these up in a recent commit to master (PR #745<https://github.com/hypre-space/hypre/pull/745>). Hopefully that fixes the issue encountered by trilinos.

-Daniel




Daniel Osei-Kuffuor

Center for Applied Scientific Computing

Lawrence Livermore National Laboratory

Livermore, CA 94550

Mail Code: L-561

Phone: 925-422-7683

Email: ***@***.******@***.***>

________________________________
From: Yang, Ulrike Meier ***@***.***>
Sent: Monday, October 10, 2022 5:22 PM
To: xsdk-project/xsdk-issues ***@***.***>; xsdk-project/xsdk-issues ***@***.***>
Cc: Assign ***@***.***>; Osei-Kuffuor, Daniel ***@***.***>
Subject: RE: [xsdk-project/xsdk-issues] trilinos-14.0.0 build error on MacOS -> hypre (Issue #182)


I am including Daniel here, so he can answer or communicate regarding this.

**Comment by balay** [comment]
Perhaps unrelated - but its a similar trilinos build error with hypre.

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3205220924
```
/data/xsdkci/VS1mJQ1K/1/xsdk-project/spack-xsdk/spack-stage/balay/
             spack-stage-trilinos-13.4.0-cwbkemkw7vzwsjyf2lzvk66jijup3cia/spack
             -build-cwbkemk/packages/ifpack2/src/Ifpack2_HypreParameterMap.hpp:
             273:1: error: expected primary-expression before 'const'
     4120      273 | const std::map<std::string, double_func> FunctionParameter
             ::hypreMapDoubleFunc_ = {
     4121          | ^~~~~
```
A rerun of the same build is successful

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3205737782

I think I saw similar random build failure before aswell [don't remember if its the same build or a different build]
