### ISSUE TITLE
dealii-9.4.0 failure with cgal

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#183]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3161006120
```
    546    -- Include /data/xsdkci/VS1mJQ1K/0/xsdk-project/spack-xsdk/spack-st
            age/balay/spack-stage-dealii-9.4.0-gdqarxbgjnqtqqb2ymkbhjkbjvb373pb
            /spack-src/cmake/configure/configure_50_cgal.cmake
     547    -- CGAL wrappers require C++17. Disabling CGAL Support.
     548    --   CGAL_INCLUDE_DIRS: *** Required variable "CGAL_INCLUDE_DIRS" s
            et to NOTFOUND ***
     549    --   CGAL_USER_INCLUDE_DIRS: *** Required variable "CGAL_INCLUDE_DI
            RS" set to NOTFOUND ***
     550    -- Could NOT find CGAL
     551    -- DEAL_II_WITH_CGAL has unmet external dependencies.
  >> 552    CMake Error at cmake/macros/macro_configure_feature.cmake:112 (MESS
            AGE):
     553    
     554    
     555      Could not find the cgal library!
     556    
     557      Please ensure that a suitable cgal library is installed on your c
            omputer.
     558    
See build log for details:
```
I also see this with dealii@develop build - looks like this was added recently by @balos1 

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3161230241

No such issue with xsdk@0.7.0

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/664725820

Will try using `dealii~cgal` for now

**Comment by bangerth** [comment]
@tamiko @luca-heltai: Can you help?

**Comment by balos1** [comment]
deall@9.4.0 is building with `~cgal` https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3175131930#L779

**Comment by luca-heltai** [comment]
The error states this: `CGAL wrappers require C++17. Disabling CGAL Support.`. This implies that deal.II +cgal is not automatically setting c++17.  For compilers that do not set C++17 by default, you need to specify also `cxxstd=17` when setting cgal. I had put this by default in the package when `dealii +cgal` was called, but JP asked me to remove it. 

Could you try seeing if `dealii +cgal cxxstd=17` works for you?

**Comment by luca-heltai** [comment]
> The error states this: `CGAL wrappers require C++17. Disabling CGAL Support.`. This implies that deal.II +cgal is not automatically setting c++17. For compilers that do not set C++17 by default, you need to specify also `cxxstd=17` when setting cgal. I had put this by default in the package when `dealii +cgal` was called, but JP asked me to remove it.
> 
> Could you try seeing if `dealii +cgal cxxstd=17` works for you?

Also, @tamiko, can you remind me again why we do not set the standard to the highest possible by default in deal.II? This behaviour changed at some point, but I don't recall why...
