### ISSUE TITLE
Phist cannot find lapack.h on Perlmutter, using cray-libsci

### ISSUE THREAD

**Issue by pghysels** [xsdk-project/xsdk-issues#189]
```
==> Installing phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq
==> No binary for phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq found: installing from source
==> Using cached archive: /global/u1/p/pghysels/xsdk/spack-xsdk/var/spack/cache/_source-cache/archive/3e/3ec660c85d37818ee219edc80e977140dfb062bdca1f38623c94a45d13634bd1.tar.gz
==> Applied patch /global/u1/p/pghysels/xsdk/spack-xsdk/var/spack/repos/builtin/packages/phist/lapack-fixes-pre-1.11.patch
==> Ran patch() for phist
==> phist: Executing phase: 'cmake'
==> phist: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

6 errors found in build log:
     154    cd /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-build-kzouxoc/cxx_bindings && /usr/bin/python3 /tmp/pghysels/spack-stage/spack-stage
            -phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-build-kzouxoc/cxx_bindings/make_cxx_bindings.py
     155    make[2]: Leaving directory '/tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-build-kzouxoc'
     156    [  1%] Built target cxx_headers
     157    In file included from /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-src/src/tools/phist_ScalarTraits.hpp:31,
     158                     from /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-src/src/tools/phist_tools.h:22,
     159                     from /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-src/src/tools/phist_tools.cpp:14:
  >> 160    /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-src/src/tools/phist_lapack.h:32:11: fatal error: lapack.h: No such file or directory
     161       32 | # include "lapack.h"
     162          |           ^~~~~~~~~~
     163    compilation terminated.
  >> 164    make[2]: *** [CMakeFiles/phist_tools.dir/build.make:79: CMakeFiles/phist_tools.dir/src/tools/phist_tools.cpp.o] Error 1
     165    make[2]: *** Waiting for unfinished jobs....
     166    In file included from /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-src/src/tools/phist_ScalarTraits.hpp:31,
     167                     from /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-src/src/tools/phist_tools.h:22,
     168                     from /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-src/src/tools/phist_perfcheck.cpp:16:
  >> 169    /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-src/src/tools/phist_lapack.h:32:11: fatal error: lapack.h: No such file or directory
     170       32 | # include "lapack.h"
     171          |           ^~~~~~~~~~
     172    compilation terminated.
  >> 173    make[2]: *** [CMakeFiles/phist_tools.dir/build.make:121: CMakeFiles/phist_tools.dir/src/tools/phist_perfcheck.cpp.o] Error 1
     174    make[2]: Leaving directory '/tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-build-kzouxoc'
  >> 175    make[1]: *** [CMakeFiles/Makefile2:209: CMakeFiles/phist_tools.dir/all] Error 2
     176    make[1]: Leaving directory '/tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-build-kzouxoc'
  >> 177    make: *** [Makefile:169: all] Error 2

See build log for details:
  /tmp/pghysels/spack-stage/spack-stage-phist-1.10.0-kzouxocoko7tjkxoukbpvuttkw4hpvvq/spack-build-out.txt
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/9791173/spack-build-out.txt)

**Comment by jthies** [comment]
Hi @pghysels, I don't have access to a Cray for trying this out -- could you send me the lapack.h and/or lapacke.h files (or whatever they call them)? I recently fixed a couple of lapack-related issues and added a patch in spack, is this build error something that sneaked in now, or was it the first time you tried to build phist on this system/with these libraries?
Thanks,
Jonas

**Comment by pghysels** [comment]
Cray-libsci does not provide lapack.h, but it does have lapacke.h.
Openblas has both lapack.h and lapacke.h, but lapacke.h includes lapack.h. So I think you are supposed to include lapacke.h.

The netlib reference implementation refers only to lapacke.h https://netlib.org/lapack/lapacke.html

**Comment by jthies** [comment]
I re-opened an issue [here](https://bitbucket.org/essex/phist/issues/245/does-not-compile-with-reference-lapack-391) to address this. Unfortunately I previously found the lapacke.h header to be incomplete both in Intel MKL and OpenBLAS, so I'm afraid there may not be a quick fix. It would help to have the blas and lapack header files provided by libsci.

**Comment by jthies** [comment]
Hi @pghysels, I hopefully fixed this now in phist@develop, maybe you could try to install that before I create a new version in spack? There is one lapack call in phist (zlartg) that is not included in lapacke, I manually define the interface and call the Fortran routine there. If that causes problems with libsci you'll see "undefined reference to zlartg_" or something, but it will not happen if you have ^trilinos~complex, which is probably the default in the xSDK.

**Comment by pghysels** [comment]
Thank!
I'm getting some different errors, please see the attached log.
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/9805090/spack-build-out.txt)

**Comment by jthies** [comment]
Hi Pieter, this is bit unexpected because it's GCC 11.2, which I use routinely to build phist.
I suspect that there is a conflict between a macro in phist and a Cray header. Any chance of building it with another BLAS/LAPACK library (like intel-mkl) to narrow down the problem? The other suspect would be mpich, but that typically works fine.

**Comment by pghysels** [comment]
I will look into it. I'll first try to build with OpenBLAS.
I had tried to build on my Fedora machine, with OpenBLAS, and that works.

**Comment by pghysels** [comment]
Works fine with OpenBLAS on Perlmutter.
It must be a cray-libsci issue.

**Comment by jthies** [comment]
If you have the build directory (with cray-libsci), could ``cd`` there and type (after loading the appropriate modules):
```bash
make src/core/phist_orthogrr.i
```
`nd upload the file
```
 CMakeFiles/phist_core.dir/src/core/phist_orthogrr.cpp.i
```
Hopefully that will give me a clue as to what's going on.

**Comment by pghysels** [comment]
[phist_orthogrr.cpp.i.txt](https://github.com/xsdk-project/xsdk-issues/files/9833436/phist_orthogrr.cpp.i.txt)

**Comment by jthies** [comment]
Thanks! Apparantly they define "I" as a macro, and I used it as a variable name somewhere.
It should be fixed in phist@develop now. Let me know if there are more things popping up.
I do think that this is very bad style from Cray, perhaps we should ask them to fix it :)

**Comment by pghysels** [comment]
Thanks! I will try again.
Perhaps this `I` macro comes from the `complex.h` header which gets included through `lapacke.h`?
https://en.cppreference.com/w/c/numeric/complex/I
