### ISSUE TITLE
The SuperLU_DIST Spack package ignores +rocm

### ISSUE THREAD

**Issue by v-dobrev** [xsdk-project/xsdk-issues#198]
To enable `+rocm`, the package also requires version `@amd` which no longer exists. See https://github.com/spack/spack/blob/fb4be98f263be83591af09fb284405314370a564/var/spack/repos/builtin/packages/superlu-dist/package.py#L125

**Comment by liuyangzhuan** [comment]
Can you see if this PR fixes the problem?
https://github.com/spack/spack/pull/33624

**Comment by v-dobrev** [comment]
> Can you see if this PR fixes the problem? [spack/spack#33624](https://github.com/spack/spack/pull/33624)

Yes, that fixes the problem. Thanks!

**Comment by v-dobrev** [comment]
The Spack PR is now merged. Closing this.
