### ISSUE TITLE
decrease spack Trilinos build time

### ISSUE THREAD

**Issue by amklinv** [xsdk-project/xsdk-issues#2]
@jwillenbring @maherou 

Spack enables virtually all of Trilinos by default, and therefore takes an unreasonably long time to build.  Most of this time is spent in the Tpetra stack, which none of our xSDK applications even use.  I will modify the spack Trilinos package to have two variants: one that includes Tpetra, and one that excludes it.  Initially, Tpetra should be enabled by default to avoid disrupting anyone's workflow; the xSDK package will explicitly disable it.  We should find out which packages (in addition to dealii) depend on Trilinos before changing the default behavior.

This is a temporary measure, as we eventually want to make Trilinos a spack meta-package.

I will time the two variants, with and without Tpetra and report them.

**Comment by amklinv** [comment]
See https://github.com/LLNL/spack/commit/385e8fe09e61edf6cd51e846a67bf12c0fd57594

On my personal workstation, disabling the Tpetra stack took the Trilinos build time from 25 m to 9 m.  For reference, it takes 7 minutes to build PETSc.

I am currently timing the build on NERSC's edison, and I will add the build times when it completes.

**Comment by BarrySmith** [comment]
Yikes, I better improve the PETSc build time :-)

**Comment by amklinv** [comment]
Update: on edison, Trilinos build time went from 1h33m to 25m.  It takes 8m to install PETSc.

**Comment by maherou** [comment]
Please record the exact CMake invocation used to produce both build time results.

**Comment by amklinv** [comment]
In all cases, I ran "spack install xsdk@xsdk-0.2.0", using the barry/xsdk branch.  The slower times used this commit (before the removal of Tpetra):

> commit f64ab9c54b6d996f6c7d58f080cf92f96450d092
Author: Alicia Klinvex <amklinv@sandia.gov>
Date:   Mon Mar 27 11:03:17 2017 -0600
>
>   Re-added patch to alquimia

The faster times used this commit (after the removal of Tpetra):

> commit 385e8fe09e61edf6cd51e846a67bf12c0fd57594
Author: Alicia Klinvex <amklinv@sandia.gov>
Date:   Tue Mar 28 11:07:12 2017 -0600
>
>    Added Tpetra-free option to Trilinos

The only difference between the two is that the faster times included "-DTrilinos_ENABLE_Tpetra:BOOL=OFF" in the CMake invocation.

If you would like the exact CMake invocation used by spack, I'll have to ask Todd how to capture that information.
