### ISSUE TITLE
PHIST 1.11.2 build errors with Cray's Fortran compiler

### ISSUE THREAD

**Issue by v-dobrev** [xsdk-project/xsdk-issues#205]
The Spack spec of the failing build is
```
phist@1.11.2%cce@14.0.4~fortran~host~int64~ipo+mpi~openmp~parmetis~scamac+shared~trilinos build_system=cmake build_type=RelWithDebInfo kernel_lib=tpetra outlev=2 arch=linux-rhel8-zen3/3t5lomm
```
The build errors look like this:
```
ftn-78 ftn: ERROR in command line
  The -f option has an invalid argument, "no-math-errno".
ftn-78 ftn: ERROR in command line
  The -f option has an invalid argument, "finite-math-only".
ftn-78 ftn: ERROR in command line
  The -f option has an invalid argument, "no-signed-zeros".
ftn-78 ftn: ERROR in command line
  The -f option has an invalid argument, "no-trapping-math".
make[2]: *** [CMakeFiles/phist_kernels_tpetra.dir/build.make:188: CMakeFiles/phist_kernels_tpetra.dir/drivers/matfuncs/tritoeplitz.F90.o] Error 1
```
Basically, it looks like the Cray Fortran compiler is given options that it does not support.

**Comment by jthies** [comment]
Does the Cray compiler identify as CLANG? We only set this flag for GCC and CLANG, so I'm wondering. 
What is also curious is that this configuration should not have to compile any Fortran code (note the ~fortran variant).
Could you attach the complete CMake output and error logs?

**Comment by v-dobrev** [comment]
As far as I know, the newer versions of the C and C++ Cray compilers are Clang-based, however the Fortran compiler is not.

Here is the full Spack build log: [phist--spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/10006424/phist--spack-build-out.txt)

**Comment by jthies** [comment]
I see, thanks.
Our CMake sees clang as the C/C++ compiler and sets Fortran flags based on that, but th Fortran compiler is Cray. I'll have to fix that.

**Comment by jthies** [comment]
Hi @v-dobrev, could you try to build phist@develop now? I added a workaround, if it works for you I'll patch the 1.11.2 version.

**Comment by v-dobrev** [comment]
Hi @jthies,

I tried `phist@develop` and still hit some errors. Here is the Spack build log: [phist-develop--spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/10165323/phist-develop--spack-build-out.txt)
