### ISSUE TITLE
Hiop CUDA error on Summit with gcc8.3.1

### ISSUE THREAD

**Issue by shuds13** [xsdk-project/xsdk-issues#206]
Spack:
git clone https://gitlab.com/xsdk-project/spack-xsdk
git checkout xsdk
Most recent commit: 40e4884e8b32a1fb949c1031e3f432aa68459e58

Spec:
xsdk~dealii@0.8.0+cuda cuda_arch=70 ^netlib-lapack ^spectrum-mpi@10.4.0.3 ^python@3.8

```bash

     427    /sw/summit/cuda/11.4.2/lib64/libcurand_static.a(curand.o): In funct
            ion `curandCreateGenerator':
  >> 428    curand.compute_86.cudafe1.cpp:(.text+0xdee4): undefined reference t
            o `culibosEnterCriticalSection'

```

[build_log_hiop_error.txt](https://github.com/xsdk-project/xsdk-issues/files/10024663/build_log_hiop_error.txt)
[spack.yaml.txt](https://github.com/xsdk-project/xsdk-issues/files/10024674/spack.yaml.txt)

**Comment by shuds13** [comment]
Currently bypassing by disabling raja.

**Comment by v-dobrev** [comment]
This was reported here: https://github.com/LLNL/hiop/pull/567 and fixed upstream here: https://github.com/LLNL/hiop/pull/568.

As workaround, I use `^hiop+shared` for xSDK v0.8.0.

**Comment by shuds13** [comment]
`^hiop+shared` worked for me.
