### ISSUE TITLE
strumpack, superlu-dist build failure with clang@15.0.4 [on fedroa37] with mpich

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#209]
```
  >> 100    clang-15: error: unknown argument: '-fallow-argument-mismatch'
```

So gfortran compiler options is getting passed to clang - so perhaps a bug in cmake build code?

Both pkgs have similar failures [and no other xsdk pkgs have this failure]
[spack-build-out-strmpk-mpich.txt](https://github.com/xsdk-project/xsdk-issues/files/10072657/spack-build-out-strmpk-mpich.txt)
[spack-build-out-slu-mpich.txt](https://github.com/xsdk-project/xsdk-issues/files/10072658/spack-build-out-slu-mpich.txt)

Ref: [glci@pj01 spack.x]$ ./bin/spack install xsdk@0.8.0%clang@15.0.4 ^alquimia%gcc@12.2.1 ^exago~python ^mpich

a build with opempi doesn't show this issue - but then - it triggers internal compiler error with strumpack build

[spack-build-out-strmpk-ompi.txt](https://github.com/xsdk-project/xsdk-issues/files/10072660/spack-build-out-strmpk-ompi.txt)

Ref: [glci@pj01 spack]$ ./bin/spack install xsdk@0.8.0%clang@15.0.4  ^alquimia%gcc@12.2.1 ^exago~python

**Comment by pghysels** [comment]
I can reproduce this on my fedora machine. 
I'm looking into it. I don't think superlu-dist or strumpack explicitly add this `-fallow-argument-mismatch` flag, so it must be coming from one of the dependencies?

**Comment by balay** [comment]
```
[glci@pj01 spack.x]$ /home/glci/spack.x/opt/spack/linux-fedora37-skylake/clang-15.0.4/mpich-4.0.2-qcjk7vahw35ldfwbee5vxk7ky2ouziuo/bin/mpif90 -show
/usr/bin/gfortran -fallow-argument-mismatch -I/home/glci/spack.x/opt/spack/linux-fedora37-skylake/clang-15.0.4/mpich-4.0.2-qcjk7vahw35ldfwbee5vxk7ky2ouziuo/include -I/home/glci/spack.x/opt/spack/linux-fedora37-skylake/clang-15.0.4/mpich-4.0.2-qcjk7vahw35ldfwbee5vxk7ky2ouziuo/include -L/home/glci/spack.x/opt/spack/linux-fedora37-skylake/clang-15.0.4/mpich-4.0.2-qcjk7vahw35ldfwbee5vxk7ky2ouziuo/lib -lmpifort -Wl,-rpath -Wl,/home/glci/spack.x/opt/spack/linux-fedora37-skylake/clang-15.0.4/mpich-4.0.2-qcjk7vahw35ldfwbee5vxk7ky2ouziuo/lib -lmpi
```

mpif90 from mpich adds in this option - but somehow the superlu-dist build process [aka cmake?] grabs this option somehow and uses it with mpicc?

Likely there is some code that attempts to detect and use some MPI stuff with both C and Fotran compilers..

But then - this occurs only with superlu-dist and strumpack - so I'm guessing there is some common cmake-code that they both use..

**Comment by pghysels** [comment]
Basically all I do is:
```
find_package(MPI)
...
target_link_libraries(strumpack PUBLIC MPI::MPI_CXX MPI::MPI_C MPI::MPI_Fortran)
```

**Comment by balay** [comment]
Yeah - I don't know how to debug cmake. Perhaps @balos1 has suggestions for this weird issue.

I attempted a petsc build with `--download-superlu-dist` - and couldn't reproduce this issue. The cmake options here are a bit different - but couldn't narrow down to the cmake option that's making the difference.

**Comment by balay** [comment]
So the following gets the superlu_dist build working for me:
```diff
diff --git a/var/spack/repos/builtin/packages/superlu-dist/package.py b/var/spack/repos/builtin/packages/superlu-dist/package.py
index 138a923029..fb4dd83116 100644
--- a/var/spack/repos/builtin/packages/superlu-dist/package.py
+++ b/var/spack/repos/builtin/packages/superlu-dist/package.py
@@ -87,6 +87,7 @@ def append_from_variant(*args):
 
         append_define("CMAKE_C_COMPILER", spec["mpi"].mpicc)
         append_define("CMAKE_CXX_COMPILER", spec["mpi"].mpicxx)
+        append_define("CMAKE_Fortran_COMPILER", spec["mpi"].mpifc)
         append_define("CMAKE_INSTALL_LIBDIR", self.prefix.lib)
         append_define("CMAKE_INSTALL_BINDIR", self.prefix.bin)
         append_define("TPL_BLAS_LIBRARIES", spec["blas"].libs)
```

[this probably just masks the buggy code path]

but then - strumpack already has this flag set - so the trigger here  must be  different.

**Comment by pghysels** [comment]
I think for strumpack the flag enters through ButterflyPACK.

**Comment by balay** [comment]
Ah - strumpack is not passing in these options. I'm not sure how strumpack cmake would pick up stuff from ButterflyPACK [without doing the extra mpi detecton - thats the buggy code path]

So the following gets this going [ to the next issue - internal compiler error]

```diff
diff --git a/var/spack/repos/builtin/packages/strumpack/package.py b/var/spack/repos/builtin/packages/strumpack/package.py
index 9bc99b4737..c00d19a54a 100644
--- a/var/spack/repos/builtin/packages/strumpack/package.py
+++ b/var/spack/repos/builtin/packages/strumpack/package.py
@@ -119,7 +119,7 @@ def cmake_args(self):
         if "+mpi" in spec:
             args.append("-DTPL_SCALAPACK_LIBRARIES=%s" % spec["scalapack"].libs.joined(";"))
 
-        if spec.satisfies("@:3.9"):
+        if spec.satisfies("@:"):
             if "+mpi" in spec:
                 args.extend(
                     [
```

**Comment by pghysels** [comment]
In this commit https://github.com/pghysels/STRUMPACK/commit/632458936a750b6ff2db1a3f5eba64e82513ba76
I rewrote some loops, and this seems to fix the clang internal compiler error.

There was a reason for this
```
if spec.satisfies("@:3.9"):
```
strumpack's CMake handling of MPI changed, and I think it's also because if you set the compilers to the Cray wrappers, CMake doesn't search for MPI, and then the cuda compiler doesn't have the MPI include paths etc. But this might not be a problem anymore because I think I made the GPU code not depend on any MPI code.

**Comment by sebastiangrimberg** [comment]
Hi @balay @pghysels , sorry for intruding but I just ran into this same issue and spent some time debugging. Maybe what I found out can be useful.

This seems to be the result of some MPI distributions including `-fallow-argument-mismatch` by default. In my case, from MPICH on Ubuntu:

```
$ mpif90 -show
gfortran -O2 -ffile-prefix-map=/build/mpich-TA889o/mpich-3.4.1=. -fstack-protector-strong -fallow-invalid-boz -fallow-argument-mismatch -Wl,-z,relro -I/usr/include/x86_64-linux-gnu/mpich -I/usr/include/x86_64-linux-gnu/mpich -L/usr/lib/x86_64-linux-gnu -lmpichfort -lmpich
```

When using CMake's FindMPI.cmake, I believe what is happening is that the imported `MPI::MPI_Fortran` target includes these flags and thus lines like `target_link_libraries(strumpack PUBLIC MPI::MPI_CXX MPI::MPI_C MPI::MPI_Fortran)` will cause problems as the flags from the Fortran target are added for all compilers (like `clang` in the problematic case). I'm fairly certain in this explanation, and indeed building STRUMPACK without ButterflyPACK you still run into the same issues which is further evidence that the erroneous flags are not from ButterflyPACK.

One way around this that was noted above is supplying the MPI compiler wrappers, in which case `FindMPI` is kind of a no-op so the unwanted Fortran flags aren't passed to the C/C++ compilers. Another solution I have tried is to just change your link line to not use the imported target:

```
@@ -586,7 +583,8 @@ endif()

 if(STRUMPACK_USE_MPI)
   target_link_libraries(strumpack PUBLIC
-    MPI::MPI_CXX MPI::MPI_C MPI::MPI_Fortran)
+    MPI::MPI_CXX MPI::MPI_C ${MPI_Fortran_LIBRARIES})
+  ## adding the MPI::MPI_Fortran target risks adding unwanted compile flags
 endif()

 if(OpenMP_FOUND)
@@ -654,11 +652,7 @@ if(ButterflyPACK_FOUND)
     ButterflyPACK::sbutterflypack
     ButterflyPACK::dbutterflypack
     ButterflyPACK::cbutterflypack
-    ButterflyPACK::zbutterflypack
-    MPI::MPI_Fortran ${MPI_Fortran_LIBRARIES})
-  ## for some reason just adding the MPI::MPI_Fortran target only
-  ## links with the f08 module, not with the regular fortran MPI
-  ## library
+    ButterflyPACK::zbutterflypack)
 endif()

 if(slate_FOUND)
```

This also seems to work in the case of STRUMPACK, with and without ButterflyPACK. Hopefully this can be of some help in coming up with a fix for the issue in STRUMPACK/SuperLU_DIST.

**Comment by pghysels** [comment]
Thanks. I applied your suggested CMake fix here: https://github.com/pghysels/STRUMPACK/commit/e4b110b2d823c51a90575b77ec1531c699097a9f
