### ISSUE TITLE
sundials@develop failure in CI

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#210]
Likely due to API change in MAGMA

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3742414534

```
/data/xsdkci/VS1mJQ1K/0/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-sundials-develop-5qlv6tvvsea54fdocjpsn2a5if247v7j/spack-src/src/sunmatrix/magmadense/sunmatrix_magmadense.cpp: In function 'int SUNM\
atMatvec_MagmaDense(SUNMatrix, N_Vector, N_Vector)':
/data/xsdkci/VS1mJQ1K/0/xsdk-project/spack-xsdk/spack-stage/balay/spack-stage-sundials-develop-5qlv6tvvsea54fdocjpsn2a5if247v7j/spack-src/src/sunmatrix/magmadense/sunmatrix_magmadense.cpp:554:58: error: invalid\
 conversion from 'realtype**' {aka 'double**'} to 'const double**' [-fpermissive]
  554 |     xgemv_batched(
      |                                                          ^
      |                                                          |
      |                                                          realtype** {aka double**}
```
[spack-build-02-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/10700509/spack-build-02-build-out.txt)

**Comment by luszczek** [comment]
This is a recent change requested by ECP CEED to align MAGMA API with vendor batched API but there are issues how to spell `const`ness: `const double **` is not the same as `double const * const *` (the latter is what is meant to express `const`ness)

**Comment by luszczek** [comment]
More on placement of `const`: https://cplusplus.com/forum/general/44166/ and `const` correctness: https://isocpp.org/wiki/faq/const-correctness#constptrptr-conversion

**Comment by luszczek** [comment]
The commit reverting this change (and hopefully fixing the error) is this one https://bitbucket.org/icl/magma/commits/1814c2518a76b81d75e5987d35797305ef2c9f4d

**Comment by balay** [comment]
@luszczek closing this issue as the pipeline is clean now. Thanks!

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/775804310
