### ISSUE TITLE
trilinos@develop failure with hypre@develop changes

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#213]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/4085960918

```
>> 3473    /data/xsdkci/VS1mJQ1K/3/xsdk-project/spack-xsdk/spack-stage/balay/
             spack-stage-trilinos-develop-jrq6qsomvzbgg3b74bysrozberg5hmvm/spac
             k-build-jrq6qso/packages/ifpack/src/Ifpack_HypreParameterMap.h:364
             :76: error: could not convert '{{"HYPRE_ADSSetChebySmoothingOption
             s", HYPRE_ADSSetChebySmoothingOptions}}' from '<brace-enclosed ini
             tializer list>' to 'const std::map<std::__cxx11::basic_string<char
             >, int (*)(hypre_Solver_struct*, double, int)>'
```

**Comment by victorapm** [comment]
Hi all,

this is probably related to a bug fix I merged into hypre recently, see https://github.com/hypre-space/hypre/pull/859

The function prototype for `HYPRE_ADSSetChebySmoothingOptions` has changed to 
```
HYPRE_Int 
HYPRE_ADSSetChebySmoothingOptions(HYPRE_Solver solver, HYPRE_Int cheby_order, HYPRE_Real cheby_fraction);
```
Previously we had `HYPRE_Int cheby_fraction` as the last argument. Trilinos would need to be updated for this change.

**Comment by jwillenbring** [comment]
@cgcgcg Could you make the changes necessary to account for this modification? Are you familiar with this part of the code?

**Comment by cgcgcg** [comment]
Yeah, I can have a look. @balay Is this only affecting Ifpack, not Ifpack2?

**Comment by balay** [comment]
The build stops here - before ifpack2 sources get built - so don't know if Ifpack2 is affected or not.

If you have a fix  for ifpack (as a patch or a branch) - I can test to see if there are any other issues.

**Comment by balay** [comment]
@cgcgcg , the xsdk CI build is clean now. Thanks for the fix!

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/4099444617

Closing this issue now.
