### ISSUE TITLE
hiop+cuda build failure

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#218]
ref:  ./bin/spack install -j24 xsdk@1.0.0+cuda cuda_arch=70 ^cuda@11.7.1 ^openmpi |& tee build11.log

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12371829/spack-build-out.txt)

**Comment by cameronrutherford** [comment]
Still haven't had a chance to look at this but cc @nychiang as we discussed offline

**Comment by cameronrutherford** [comment]
#220 was related were hiop@develop and exago@develop should be used. We are still working on `spack test` support, but this configuration builds just fine.

https://github.com/spack/spack/pull/35751

**Comment by balay** [comment]
Ok - using hiop 'develop' branch gets the build going.

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/4987095717

**Comment by cameronrutherford** [comment]
Closing as this has been resolve as far as I can tell
