### ISSUE TITLE
alquimia build failure

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#219]
This build is with alquimia/master, pflotran/master, petsc/main

```
     99     /data/balay/spack.x/spack-stage/spack-stage-alquimia-1.1.0-ij5qqajodsvwlocluzkworzsahi6hqqo/spack-src/alquimia/pflotran_alquimia_interface.F90:67:7:
     100
     101       67 |   use Material_Aux_class, only : material_auxvar_type
     102          |       1
  >> 103    Fatal Error: Cannot open module file 'material_aux_class.mod' for reading at (1): No such file or directory
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12431610/spack-build-out.txt)

also cc: @ghammond86

**Comment by balay** [comment]
@smolins @ghammond86 

The following patch (to alquimia) gets the build going for me - but its likely buggy.

[pflotran.patch.txt](https://github.com/xsdk-project/xsdk-issues/files/12488603/pflotran.patch.txt)

Let me know how we should proceed wrt xsdk

**Comment by ghammond86** [comment]
How do I go about testing specific branches of alquimia and pflotran against a target branch in xSDK? Is this documented somewhere?

**Comment by balay** [comment]
The spack changes are at https://gitlab.com/xsdk-project/spack-xsdk branch `xsdk-1.0.0` - so you can do:

```
spack install xsdk@1.0.0
```
or the following might just build the subset:
```
spack install alquimia@1.1.0 ^pflotran@5.0.0 ^petsc@3.20.0
```

Note: I've added the above alquimia patch in this spack build. [this can be removed/updated - as needed]

To test manually,  you can build petsc/main with pflotran/master and alquimia/master

**Comment by ghammond86** [comment]
My goal is to update alquimia without patches (already complete) and verify that the updated branches build through spack. I want to build alquimia (through spack) using the following repo/branch combinations for testing purposes.

**https://github.com/ghammond86/alquimia-dev glenn/pflotran-master2**
https://gitlab.com/petsc/petsc main
https://bitbucket.org/pflotran/pflotran master

Can I do this directly through spack? I don't believe so as my alquimia repo and branch are not available through spack. Can I add repo@branch combo as a spack "Remote version"?

Do I branch xsdk-project/spack-xsdk? I don't believe that I have permissions. I could fork the repo.

Or something else?

**Comment by balay** [comment]
We can change spack spec and add in the needed changes to test. [i.e local changes to test out, but won't be pushed to spack proper as a PR]

I've added this change to https://gitlab.com/xsdk-project/spack-xsdk branch "xsdk-1.0.0-test" (my current changes,with your suggested change) - you can give that a try.

Edit: Also you don't need to create new branches or push stuff - to test such changes. [can make local edits/commits to spack local clone - and test out..]. But I can provide write access to this repo - if that helps.

**Comment by balay** [comment]
I just tried a build - and get:
```
/data/balay/spack.z/spack-stage/spack-stage-alquimia-1.1.0-m342pmpearhvqz7fliki66ttwhysiqrx/spack-src/alquimia/pflotran_alquimia_interface.F90:548:57:

  548 |        reaction, natural_id, engine_state%option, ierror)
      |                                                         1
Error: Type mismatch in argument 'num_iterations' at (1); passed CLASS(reaction_rt_type) to INTEGER(4)
/data/balay/spack.z/spack-stage/spack-stage-alquimia-1.1.0-m342pmpearhvqz7fliki66ttwhysiqrx/spack-src/alquimia/pflotran_alquimia_interface.F90:555:83:

  555 |           engine_state%material_auxvar, engine_state%reaction, engine_state%option)
      |                                                                                   1
Error: Type mismatch in argument 'kinetic_state_updated' at (1); passed TYPE(option_type) to LOGICAL(4)
```

**Comment by ghammond86** [comment]
alquimia@1.1.0 should now be fixed (as long as one uses "https://github.com/ghammond86/alquimia-dev glenn/pflotran-master2"). 

I plan to discuss my updates to the alquimia-ats interface with Sergi on Monday. Assuming that there are no major issues, we should have this issue resolved by the end of next week..

Thanks for the help!

**Comment by ghammond86** [comment]
Satish,

Will you please try "https://github.com/LBL-EESA/alquimia-dev master"? It should be up to date with PETSc main (upcoming v3.20.0) and PFLOTRAN master (upcoming v5.0.0).

**Comment by balay** [comment]
Thanks! reverted to using aquimia-dev repo now!

[builds look good]

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1006553912
