### ISSUE TITLE
AMReX build failure in xSDK CI

### ISSUE THREAD

**Issue by v-dobrev** [xsdk-project/xsdk-issues#223]
See https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5195411633

ping: @asalmgren

**Comment by balay** [comment]
@v-dobrev this is triggered by

https://github.com/spack/spack/pull/37695

I couldn't add this extra requirement to `xsdk/package.py` [don't know why that wasn't working] - so pushed this change to CI

https://gitlab.com/xsdk-project/spack-xsdk-ci/-/commit/d56f92bed1d8e6ee40a2bbb29a3d432b324b3574

**Comment by v-dobrev** [comment]
@balay, your solution (adding explicitly the constraint `^amrex dimnensions=3` to the `xsdk` spec) is okay but ideally this type of requirement will be in the AMReX spack package.

Maybe the AMReX team can find a way to fix this the AMReX spack package.

cc: @ax3l
