### ISSUE TITLE
heffte build failure with xsdk+hip

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#228]
ref: `./bin/spack spec xsdk+rocm amdgpu_target=gfx90a`

```
balay@petsc-gpu-02:/scratch/balay/spack$ ./bin/spack spec xsdk+rocm amdgpu_target=gfx90a |grep heffte@
 -       ^heffte@2.4.0%gcc@11.4.0~cuda+fftw~fortran~ipo+magma~mkl~python+rocm+shared amdgpu_target=gfx90a build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen4
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12884856/spack-build-out.txt)

**Comment by mkstoyanov** [comment]
the issue is with spack mishandling the transitive dependencies

https://github.com/spack/spack/pull/40514

**Comment by balay** [comment]
Thanks! The build goes through for me now

**Comment by mkstoyanov** [comment]
Great! Thanks for your help!
