### ISSUE TITLE
DTK failure with gcc1321

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#233]
xr_l_g132-xsdk-100-linux-gcc1321 

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299104

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12885365/spack-build-out.txt)

**Comment by balay** [comment]
xr_l_i23-xsdk-100-linux-oneapi2023-2-0

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299105

Log in the artifacts above

**Comment by masterleinad** [comment]
The error looks like
```
/home/xsdk/builds/cYLkqamb/1/xsdk-project/spa
            ck-xsdk/spack-stage/spack-stage-datatransferkit-3.2-u2fqa65lja3k4mi
            xlp4ybcpfargo6szp/spack-src/packages/Utils/src/DTK_Types.h:19:
  >> 270    /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/cstd
            int:56:9: error: no member named 'int_fast8_t' in the global namesp
            ace; did you mean '::DataTransferKit::int_fast8_t'?
     271      using ::int_fast8_t;
     272            ^~
     273    /usr/include/stdint.h:58:22: note: '::DataTransferKit::int_fast8_t'
             declared here
     274    typedef signed char             int_fast8_t;
     275                                    ^
```
which seems more like a toolchain issue (or possibly a missing include header).

**Comment by masterleinad** [comment]
It looks very similar to the `MFEM` failures
```
 fem/../general/kdtree.hpp:317:12: error: no type named 'uint8_t' in
             namespace 'std'
     329          std::uint8_t dim;
     330          ~~~~~^
```

**Comment by balay** [comment]
> It looks very similar to the MFEM failures

The fix in MFEM now gets the builds working

https://github.com/xsdk-project/xsdk-issues/issues/234

cc: @v-dobrev

**Comment by masterleinad** [comment]
https://github.com/ORNL-CEES/DataTransferKit/pull/606 hopefully fixes it.

**Comment by masterleinad** [comment]
@balay Can you confirm that https://github.com/ORNL-CEES/DataTransferKit/pull/606 fixed the issue? In that case, we would create a new release.

**Comment by balay** [comment]
I've started a pipeline to test at https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1036580048

[its using master branch]

**Comment by balay** [comment]
So the builds are good now. Thanks!

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5292585778

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5292585775

Note: some builds have trilinos failures - i.e they skipped testing DTK..
