### ISSUE TITLE
mfem build with gcc1321 

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#234]
xr_l_g132-xsdk-100-linux-gcc1321 
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12885398/spack-build-out.txt)

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299104

**Comment by balay** [comment]
` xr_l_i23-xsdk-100-linux-oneapi2023-2-0` 

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5276299105

Log in the `artifacts` above

**Comment by v-dobrev** [comment]
This is being addressed after the mfem-4.6 release in https://github.com/mfem/mfem/pull/3903.

I'll make a patch with it for spack.

**Comment by v-dobrev** [comment]
The second issue with oneapi seems to be the same as the first one with gcc.

**Comment by v-dobrev** [comment]
Here's the spack PR with the patch: https://github.com/spack/spack/pull/40495.

**Comment by balay** [comment]
@v-dobrev the fix works

xr_l_g132-xsdk-100-linux-gcc1321


https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5285288802

 xr_l_i23-xsdk-100-linux-oneapi2023-2-0

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5285007527

**Comment by v-dobrev** [comment]
I think this is resolved. Closing.
