### ISSUE TITLE
strumpack failure with intel 1911

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#237]
` xr_l_i19-xsdk-100-linux-intel1911`

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5291324286

```
ld: /data/xsdkci/VS1mJQ1K/3/xsdk-project/spack-xsdk/opt/spack/linux-rocky9-cascadelake/gcc-11.3.1/slate-2023.08.25-abvqrzvckext2b5b5m2k6asdx5vabr4y/lib64/libslate.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.\
4.29'
make[2]: *** [test/CMakeFiles/test_BLR_mpi.dir/build.make:122: test/test_BLR_mpi] Error 1
```

This is an old intel compiler though [via gcc/8.5.0/  but all other  pkgs appear to build with it]

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12902388/spack-build-out.txt)

**Comment by balay** [comment]
So the issue could be: eventhough this is a intel compiler build - for some reason slate gets built with `gcc` [and an incompatible version of gcc with this intel compiler]
```
-- linux-rocky9-cascadelake / gcc@11.3.1 ------------------------
gmake@4.3~guile build_system=autotools patches=599f134
slate@2023.08.25~cuda~ipo+mpi+openmp~rocm+shared~sycl build_system=cmake build_type=Release generator=make
```

I'm not sure why..

**Comment by balay** [comment]
```
balay@xsdk:/data/balay/spack.y>./bin/spack spec xsdk@1.0.0 %intel@19.1.1.217 ^py-libensemble%intel@19.1.1.217 ^netlib-lapack@3.9.1 ^boost@1.70.0 ^trilinos cxxflags=-no-ipo ^netlib-scalapack@2.1.0 ^py-numpy@1.22.4 ^openmpi~rsh ^texinfo@6.8 ^hdf5@1.12.2 ^slate %intel@19.1.1.217
==> Error: concretization failed for the following reasons:

   1. slate: Does not currently build with icpc >= 2019
```

**Comment by balay** [comment]
Using compatible gcc [with slate] gets this build working.

```
./bin/spack install xsdk@1.0.0 %intel@19.1.1.217 ^py-libensemble%intel@19.1.1.217 ^netlib-lapack@3.9.1 ^boost@1.70.0 ^trilinos cxxflags=-no-ipo ^netlib-scalapack@2.1.0 ^py-numpy@1.22.4 ^openmpi~rsh ^texinfo@6.8 ^hdf5@1.12.2 ^slate%gcc@8.5.0
```

**Comment by mgates3** [comment]
> slate: Does not currently build with icpc >= 2019

[SLATE's Spack script](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/slate/package.py#L101C5-L101C78) has an out-dated restriction. We can use icpx 2023. (I get an error with icpc 2023, but that compiler is deprecated, and I assume `intel` now refers to `icpx`.) I'll see about getting that fixed in Spack, probably removing the restriction for SLATE >= v2023.08.25. It may have been fixed before v2023.08.25, but we don't have the cycles to determine exactly where it was fixed.

**Comment by balay** [comment]
>  I assume intel now refers to icpx

Yeah - this build is with old intel compilers.

The builds with newer `OneAPI` compilers goes through fine

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1037533752

**Comment by balay** [comment]
I can continue to use ` ^slate%gcc@8.5.0` for this (old) Intel build in CI.
