### ISSUE TITLE
MFEM on Perlmutter

### ISSUE THREAD

**Issue by pghysels** [xsdk-project/xsdk-issues#245]
ld: cannot find -lcublas: No such file or directory
ld: cannot find -lcusparse: No such file or directory

[spack-build-out_MFEM.txt](https://github.com/xsdk-project/xsdk-issues/files/13123980/spack-build-out_MFEM.txt)

cublas and cusparse are at `/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/math_libs/11.7/lib64` on Perlmutter.

@v-dobrev

**Comment by v-dobrev** [comment]
@pghysels, can you please post the Spack config files `compilers.yaml` and `packages.yaml` that you used?

I'm trying to figure out how Spack can tell me where `cublas`, `cusparse`, etc are installed -- it looks like in the setup you have on Perlmutter, `nvcc` does not add these directories automatically (at least not when linking).

**Comment by pghysels** [comment]
[packages.yaml.txt](https://github.com/xsdk-project/xsdk-issues/files/13200465/packages.yaml.txt)
[compilers.yaml.txt](https://github.com/xsdk-project/xsdk-issues/files/13200467/compilers.yaml.txt)

I tried adding 
```
    flags:
      ldflags: -L/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/math_libs/11.7/lib64
```
in `compilers.yaml`, then it worked. 
But that made umpire fail, since it uses `ar` to build a `.a` library, and it doesn't recognize the `-L...` option.

Using CMake and linking with the `CUDA::cublas` target from `find_package(CUDAToolkit)` does work.

**Comment by v-dobrev** [comment]
MFEM's Spack package uses MFEM's GNU make build system, so I need to figure out the path to `cusparse` et al in `mfem/package.py`. In the log file I see that `nvcc` is here: `/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/cuda/11.7/bin/nvcc`, so I guess I can use some logic to search relative to that path. I'm trying to figure out if Spack has some functionality for that before I write the search logic myself.

**Comment by v-dobrev** [comment]
Hi @pghysels, can you try your build on Perlmutter with the additions in https://github.com/spack/spack/pull/40815?

**Comment by pghysels** [comment]
Hi @v-dobrev , yes that works!

**Comment by v-dobrev** [comment]
Excellent! Thanks @pghysels!
