### ISSUE TITLE
institutional logos on website has broken links

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#250]
https://xsdk.info/ has

![Screenshot from 2023-11-10 10-05-15](https://github.com/xsdk-project/xsdk-issues/assets/5642668/f49e357d-ff66-4fd8-9e0f-e163c7aee34d)

Reported-by: @bernhold

**Comment by balay** [comment]
I'm not sure how this was setup.

One of the image URL points to `http://ideas-productivity.org/wordpress/wp-content/uploads/2014/10/ANL-logo-square-300x267.jpg` - so presumably IDEAS migrated away from this wordpress website - so these images are no longer accessible.

**Comment by jwillenbring** [comment]
I'll take a look at this and report back.

**Comment by jwillenbring** [comment]
I'm not sure what happened here. The logos did not get deleted. The page source just had the alt text and no link to the logos. In any case, I think this looks better now. If someone could please confirm it looks good for them too, I would appreciate it. I checked it on both a desktop and phone and I thought both renderings were reasonable.

**Comment by bernhold** [comment]
Looks like you've fixed it.  FYI, We just put a new IDEAS site into production and the logos are not at the same location as they were.  I didn't look deeper to notice that you were linking to our website.  From looking at the new page source, it looks like you now have these logos on your own site, which I think is the better solution.  Sorry about that.
