### ISSUE TITLE
sundials@develop breaks amrex, mfem

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#252]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5541203644

```
  >> 158    /data/xsdkci/VS1mJQ1K/1/xsdk-project/spack-xsdk/spack-stage/balay/s
            pack-stage-amrex-develop-jspywd4i3cho3nq2ku5urbqy2hj6gjn7/spack-src
            /Src/Extern/SUNDIALS/AMReX_Sundials.H:9:40: error: 'realtype' was n
            ot declared in this scope; did you mean 'decltype'?
     159        9 | static_assert(std::is_same<amrex::Real,realtype>::value,
     160          |                                        ^~~~~~~~
     161          |                                        decltype
```

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5541203560

```
>> 169    linalg/sundials.hpp(393): error: identifier "realtype" is undefined
```

**Comment by WeiqunZhang** [comment]
https://github.com/AMReX-Codes/amrex/pull/3632 should fix it.

**Comment by asalmgren** [comment]
This amrex PR has just been merged

**Comment by balay** [comment]
Thanks for the fix!

BTW: Does this fix work with current sundials release (i.e 6.6.2)?

**Comment by WeiqunZhang** [comment]
Yes, I think so. It appears that `sunrealtype` was introduced in 2021-12-14.

**Comment by balay** [comment]
dealii is also affected

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/13369716/spack-build-out.txt)

cc: @masterleinad

**Comment by masterleinad** [comment]
> dealii is also affected

https://github.com/dealii/dealii/pull/16271
