### ISSUE TITLE
sundials@develop build failure perhaps due to ginkgo dependency changes?

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#257]
```
Tue Jul  9 08:09:27 AM CDT 2024
```
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7295710112

```
==> No binary for sundials-develop-slbcvsbu6s5fau7l2kffb4qgdg7jd3xd found: installing from source
==> No patches needed for sundials
==> sundials: Executing phase: 'cmake'
==> sundials: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
<snip>
>> 3168    /scratch/svcpetsc/xsdk-builds/VS1mJQ1K/0/xsdk-project/spack-xsdk/o
             pt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/ginkgo-develop-6yp2kl
             vzn2wgekc3pn5o4w4bjniroq7e/include/ginkgo/core/base/utils_helper.h
             pp(101): error: namespace "std" has no member "void_t"
...
```

The prior day build is successful
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7285125326

And latest failure:
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7351601385

**Comment by pratikvn** [comment]
@balos1, I believe this is because Ginkgo develop now uses C++ 17 standard. Would it be possible to set the default standard when using the develop branch of Ginkgo to C++-17 ? For Ginkgo version 1.8.0 and before, C++ 14 should work.

**Comment by balay** [comment]
@tcojean suggests using @1.8.0 for now. So I've switched this test over to it. [And the same is targeted for xsdk@1.1.0]

I'll note - the non-cuda variant of this test did go through..

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7361731184

**Comment by balay** [comment]
https://github.com/spack/spack/pull/44923

Looks like the 1.8.0 PR to spack is stuck
