### ISSUE TITLE
mfem:  +sundials needs updated dependencies.

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#258]
For now using `mfem~sundials` as the dependencies wrt `sundials > 6.7.0` are missing from `mfem/package.py`

ref: https://gitlab.com/xsdk-project/spack-xsdk/-/commit/feb950c647c4b82883ab5b0284dd1de3b7a34ce0

**Comment by balay** [comment]
Here is the error I get (with `mfem+sundials`):
```
balay@pj02:~/spack$ ./bin/spack spec xsdk@1.1.0%gcc@14.2.1
==> Error: failed to concretize `xsdk@1.1.0%gcc@14.2.1` for the following reasons:
     1. xsdk: 'amdgpu_target=none' conflicts with '+rocm'
     2. xsdk: '%gcc@14:' conflicts with '+cuda ^cuda@:12.5~allow-unsupported-compilers'
     3. xsdk: 'amdgpu_target=none' conflicts with '+rocm'
        required because conflict is triggered when amdgpu_target=none 
          required because xsdk@1.1.0%gcc@14.2.1 requested explicitly 
        required because conflict constraint +rocm 
          required because xsdk@1.1.0%gcc@14.2.1 requested explicitly 
     4. xsdk: '%gcc@14:' conflicts with '+cuda ^cuda@:12.5~allow-unsupported-compilers'
        required because conflict is triggered when %gcc@14: 
          required because xsdk@1.1.0%gcc@14.2.1 requested explicitly 
        required because conflict constraint +cuda ^cuda@:12.5~allow-unsupported-compilers 
          required because xsdk@1.1.0%gcc@14.2.1 requested explicitly 
balay@pj02:~/spack$ ./bin/spack spec xsdk@1.1.0%gcc@14.2.1~cuda~rocm
==> Error: failed to concretize `xsdk@1.1.0%gcc@14.2.1~cuda~rocm` for the following reasons:
     1. Cannot select a single "version" for package "sundials"
     2. Cannot satisfy 'sundials@:6.7.0'
     3. Cannot satisfy 'sundials@7.2.0'
     4. Cannot satisfy 'sundials@6.2.0:6.7.0'
     5. Cannot satisfy 'sundials@5:6.7'
     6. Cannot satisfy 'sundials@5.0.0:6.7.0'
     7. Cannot satisfy 'sundials@7.2.0'
        required because xsdk depends on sundials@7.2.0+hypre~int64+petsc~rocm+superlu-dist when @1.1.0~rocm 
          required because xsdk@1.1.0%gcc@14.2.1~cuda~rocm requested explicitly 
<snip>
    22. Cannot satisfy 'sundials@2.7.0:' and 'sundials@7.2.0
<snip>
```

**Comment by v-dobrev** [comment]
SUNDIALS 7+ is not supported in MFEM as of 09/05/2024. I've been planning to work on this for some time now, however I haven't found time to do it yet.

**Comment by v-dobrev** [comment]
Here's the MFEM PR that adds SUNDIALS v7 support to MFEM: https://github.com/mfem/mfem/pull/4528.

**Comment by balay** [comment]
@v-dobrev how do I try this fix in xsdk?

currently xsdk@1.1.0 is set to use mfem@4.7 - but this patch doesn't apply cleanly to it.

**Comment by balay** [comment]
@v-dobrev, @balos1  I ran a CI build directly on `sundials-v7-support` branch - and got a failure [with `+cuda`]

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7970294507
```
  >> 175    linalg/sundials.cpp(263): error: too few arguments in function call
     176
```

**Comment by balay** [comment]
@v-dobrev , @balos1  - sundials-v7-support also has a build failure with `+hip` - at the same location.

```
linalg/sundials.cpp:263:23: error: no matching function for call to 'SUNMemoryNewEmpty'
  263 |    SUNMemory sunmem = SUNMemoryNewEmpty();
      |                       ^~~~~~~~~~~~~~~~~
/scratch/svcpetsc/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/sundials-7.2.0-2jmi4tg4iuu5sdfwuowtem5mcqb35moj/include/sundials/sundials_memory.h:53:27: note: candidate function not viable: requires single argument 'sunctx', but no arguments were provided
   53 | SUNDIALS_EXPORT SUNMemory SUNMemoryNewEmpty(SUNContext sunctx);
      |                           ^                 ~~~~~~~~~~~~~~~~~
```

**Comment by v-dobrev** [comment]
Thank you for testing the branch, @balay!

I pushed a fix for the issue you encountered in https://github.com/mfem/mfem/pull/4528.

When testing in Spack, I also had to patch the `sundials` package with this:
```diff
diff --git a/var/spack/repos/builtin/packages/sundials/package.py b/var/spack/repos/builtin/packages/sundials/package.py
index 5be35b6bb0..3732aed103 100644
--- a/var/spack/repos/builtin/packages/sundials/package.py
+++ b/var/spack/repos/builtin/packages/sundials/package.py
@@ -733,6 +733,8 @@ def libs(self):
             # Q: should the result be ordered by dependency?
         else:
             sun_libs = ["libsundials_" + p for p in query_parameters]
+            if self.spec.satisfies("@7:"):
+                sun_libs += ["libsundials_core"]
         is_shared = "+shared" in self.spec
 
         libs = find_libraries(sun_libs, root=self.prefix, shared=is_shared, recursive=True)
```

**Comment by balay** [comment]
I'm now seeing (for +rocm):
```
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: hipblasCreate
>>> referenced by ../libmfem.so
```
[spack-build-out.txt](https://github.com/user-attachments/files/17249951/spack-build-out.txt)

**Comment by balay** [comment]
The cuda build ran fine.

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1480929224

**Comment by v-dobrev** [comment]
Hi @balay, yes, I forgot that now `mfem+rocm` depends on `hipblas`. Can you try a patch like this:
```diff
diff --git a/var/spack/repos/builtin/packages/mfem/package.py b/var/spack/repos/builtin/packages/mfem/package.py
index df419c1423..77924f2014 100644
--- a/var/spack/repos/builtin/packages/mfem/package.py
+++ b/var/spack/repos/builtin/packages/mfem/package.py
@@ -282,6 +282,7 @@ class Mfem(Package, CudaPackage, ROCmPackage):
 
     depends_on("mpi", when="+mpi")
     depends_on("hipsparse", when="@4.4.0:+rocm")
+    depends_on("hipblas", when="@4.7.1:+rocm")
 
     with when("+mpi"):
         depends_on("hypre")
@@ -976,9 +977,12 @@ def find_optional_library(name, prefix):
             if "^rocprim" in spec and not spec["hip"].external:
                 # rocthrust [via petsc+rocm] has a dependency on rocprim
                 hip_headers += spec["rocprim"].headers
-            if "^hipblas" in spec and not spec["hip"].external:
-                # superlu-dist+rocm needs the hipblas header path
-                hip_headers += spec["hipblas"].headers
+            if "^hipblas" in spec:
+                if not spec["hip"].external:
+                    # superlu-dist+rocm needs the hipblas header path
+                    hip_headers += spec["hipblas"].headers
+                if spec.satisfies("@4.7.1:"):
+                    hip_libs += spec["hipblas"].libs
             if "%cce" in spec:
                 # We assume the proper Cray CCE module (cce) is loaded:
                 proc = str(spec.target.family)
```

**Comment by balay** [comment]
Thanks! The build goes through now.

BTW: Would there be a mfem@4.7.1 release - with these updates?

**Comment by v-dobrev** [comment]
> BTW: Would there be a mfem@4.7.1 release - with these updates?

We have not started the discussion about the next MFEM release yet, so the plan is to use mfem v4.7 for xsdk v1.1.0, possibly with a minimal patch to support sundials v7.x -- I can work on preparing this patch when the above mfem PR is merged.

**Comment by balay** [comment]
> I can work on preparing this patch when the above mfem PR is merged.

That would be great! For now - will use this branch [with the corresponding changes in spack]

**Comment by v-dobrev** [comment]
Update: the MFEM PR (https://github.com/mfem/mfem/pull/4528) that adds support for SUNDIALS v7 is now merged in MFEM's `master` branch.

I'll try to create a patch for Spack for MFEM v4.7 + SUNDIALS v7 -- I'll post here when I have a branch in Spack for this addition.

**Comment by v-dobrev** [comment]
@balay, @balos1, here is the Spack PR: https://github.com/spack/spack/pull/47591.

**Comment by balay** [comment]
Thanks @v-dobrev! Testing  at https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1541726225

BTW: I have one additional diff in my branch from https://github.com/xsdk-project/xsdk-issues/issues/258#issuecomment-2392924327

[I guess I should recheck - if its needed for 4.7.0 or not]

**Comment by v-dobrev** [comment]
> BTW: I have one additional diff in my branch from [#258 (comment)](https://github.com/xsdk-project/xsdk-issues/issues/258#issuecomment-2392924327)
> 
> [I guess I should recheck - if its needed for 4.7.0 or not]

The patch from https://github.com/xsdk-project/xsdk-issues/issues/258#issuecomment-2392924327 is needed for `mfem@develop`, i.e. mfem's `master` branch -- it should not be necessary for `mfem@4.7.0` (with or without the sundials v7 patch).

**Comment by v-dobrev** [comment]
With this issue addressed, we should be able to switch back to using `^sundials@develop` with `mfem@develop` in the GitLab pipelines, here:

https://gitlab.com/xsdk-project/spack-xsdk-ci/-/blob/master/gitlab-xsdk-ci.yml?ref_type=heads#L70-71

and here

https://gitlab.com/xsdk-project/spack-xsdk-ci/-/blob/master/gitlab-xsdk-ci.yml?ref_type=heads#L82-83

**Comment by balay** [comment]
Thanks! pushed this change
