### ISSUE TITLE
slate (master branch) build errors.

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#259]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7608758587

```
  >> 606    /home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stage/sp
            ack-stage-slate-2024.08.31-44xqg6rii3zk36bvxo7ma2o5kr72tnjj/spack-s
            rc/src/steqr_impl.cc:101:67: error: 'Pivot' has not been declared i
            n 'lapack'
     607      101 |     using lapack::MatrixType, lapack::Norm, lapack::Side, l
            apack::Pivot,
     608          |                                                            
                   ^~~~~
...
```

**Comment by balay** [comment]
slate@2024.05.31 build goes through though [in this build]

**Comment by mgates3** [comment]
slate@master should depend on lapackpp@master, per [SLATE's Spack recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/slate/package.py):
```
    depends_on("lapackpp@master", when="@master")
```

git ID `0e6f2d7` is the current master.
But then the log you provide (https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7608758587) references an ~older~ _nonexistent_ SLATE: `spack-stage-slate-2024.08.31-...`
and an older LAPACK++: `-isystem /home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/gcc-14.2.1/lapackpp-2024.05.31-...`
Any idea why? If that is updated to lapackpp master, it should work.

```
/home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/lib/spack/env/
            gcc/g++ -DSLATE_ID=\"0e6f2d7\" -Dslate_EXPORTS -I/home/xsdk/builds/   # 0e6f2d7 is master
            rZPizn2W/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-slate-20
            24.08.31-44xqg6rii3zk36bvxo7ma2o5kr72tnjj/spack-src/include -I/home
            /xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/spack-stage/spack-s
            tage-slate-2024.08.31-44xqg6rii3zk36bvxo7ma2o5kr72tnjj/spack-src/sr  # references ~older~ nonexistent version
            c -isystem /home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/opt
            /spack/linux-fedora40-skylake/gcc-14.2.1/mpich-4.2.2-q3pghvzq3pazma
            fdlrqsogjau7z7xqca/include -isystem /home/xsdk/builds/rZPizn2W/0/xs
            dk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/gcc-14.2.1/b
            laspp-2024.05.31-pzzsjsicesavh5n464lsuemabu5vj2va/include -isystem 
            /home/xsdk/builds/rZPizn2W/0/xsdk-project/spack-xsdk/opt/spack/linu
            x-fedora40-skylake/gcc-14.2.1/lapackpp-2024.05.31-yughoeuoey74rnjm4  # references older version of LAPACK++
            mf5m6c3dtmwdpmi/include
```

**Comment by balay** [comment]
Thanks @mgates3 !  using lapackpp@master works.

Wrt the inconsistencies here - this is work towards xsdk@1.1.0 where I'm using `2024.08.31`' a future (non-existent)  version number here.
```
    version("2024.08.31", branch="master")
```

Stepping back a bit - what version of slate were you intending for xsdk-1.1.0 release? [my current assumption is - there would be a new slate release - and wrt this issue a new lapackpp release -  by sept-end/oct-begin - that would go into this xsdk release. If this is not the case - I'll update xsdk-1.1.0 sources accordingly]

**Comment by mgates3** [comment]
Yes, I can do a September release. That placeholder version is fine for now.
