### ISSUE TITLE
phist build error with clang

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#260]
This is with:
```
    version("1.13.0", branch="devel")
```

- https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7693518429
```
>> 3002    /home/xsdk/builds/cYLkqamb/1/xsdk-project/spack-xsdk/spack-stage/s
             pack-stage-phist-1.13.0-ckwxof42tssolae3ukb4pu5krtviup7y/spack-src
             /src/kernels/tpetra/kernels_def.hpp:734:32: error: non-constant-ex
             pression cannot be narrowed from type 'int' to 'double' in initial
             izer list [-Wc++11-narrowing]
...
```

Also failures (with Intel compilers) at:
- https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7693518458
- https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7693518414
-  https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7693518373

**Comment by jthies** [comment]
Hi @balay, thanks for reporting. From the CI output I only see part of the actual build log, and because the list of include paths is so long with spack I don't see the compiler command. Which compiler and version are used? Is it icpc or icpx?

**Comment by balay** [comment]
@jthies you can browse the 'artifacts' from the CI pipeline webpage.

For ex:  https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7693518414

has:

```
$ nice ./bin/spack install xsdk@1.1.0%oneapi@2024.2.1 ^intel-oneapi-mkl ^intel-oneapi-mpi ^petsc%oneapi@2024.2.1 ^boost@1.84.0%gcc@14.2.1
```
Clicking 'Browse' under 'Job artifacts' in the above pipeline URL  - we can locate phists build logs at:

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7693518414/artifacts/browse/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/
```
/software/intel/oneapi/mpi/2021.13/bin/mpiicpx -DKOKKOS_DEPENDENCE -Dphist_kernels_tpetra_EXPORTS -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/drivers/matfuncs -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-build-qhu3jdu -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/kernels -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/kernels/tpetra -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/kernels/trilinos_interface -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/tools -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/core -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/krylov -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/jada -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/precon -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/drivers -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-build-qhu3jdu/cxx_bindings -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/lib/googletest-master-12-2015 -I/home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src -isystem /software/intel/oneapi/mkl/2024.2/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/oneapi-2024.2.1/trilinos-16.0.0-mlltpijfyna7mqwzn25fnzor4cx35z42/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/oneapi-2024.2.1/hwloc-2.11.1-3iqvugbqu6wu4xfbka63nfgpx54pe43e/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/gcc-14.2.1/boost-1.84.0-ltcvy55er5n4c5y64plzfr7zo6rmjxpd/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/oneapi-2024.2.1/metis-5.1.0-jrvkexdowzcx2q2s2jiuwcaeqa4wiq2z/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/oneapi-2024.2.1/hdf5-1.14.3-stub6vhxa6vtwg75jwtfoowv2mzk3d7t/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/oneapi-2024.2.1/hypre-2.32.0-oyj7w2cumlrdyd7idghdefruqa5yp4kl/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/oneapi-2024.2.1/parmetis-4.0.3-ww5e5tvfamisx5istkq52eoyqg3p5igm/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/oneapi-2024.2.1/zlib-ng-2.2.1-zw7psgn7hjqi64e35jyfhkoqvlw2a22o/include -isystem /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/opt/spack/linux-fedora40-skylake/oneapi-2024.2.1/superlu-dist-8.3.0-zimjl24o2clalxdvyd5z75hrale5rxxt/include -O3 -DNDEBUG -std=c++17 -fPIC -march=core-avx2 -mtune=core-avx2 -mrtm -MD -MT CMakeFiles/phist_kernels_tpetra.dir/src/kernels/tpetra/kernelsD.cpp.o -MF CMakeFiles/phist_kernels_tpetra.dir/src/kernels/tpetra/kernelsD.cpp.o.d -o CMakeFiles/phist_kernels_tpetra.dir/src/kernels/tpetra/kernelsD.cpp.o -c /home/xsdk/builds/cYLkqamb/0/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-qhu3jdukassh5cjrfqqo7pyny2ywaquh/spack-src/src/kernels/tpetra/kernelsD.cpp
```

**Comment by balay** [comment]
I reran the test - the errors persist [in clang, oneapi tests]

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1475733478

**Comment by jthies** [comment]
Hi @balay Sorry this is taking so long. I still can't access the build logs, I get to the CI pipeline page, but when I click on a specific build, I get "500: We're sorry, something went wrong on our end". At the same time, on my own system I can't ven build Trilinos with the oneapi compilers. I will try something with clang, but as it doesn't properly support Fortran, I'm not too optimistic that I get the whole stack to build. Any chance that you could send me a (few) build log(s), respectively attach them here?

**Comment by balay** [comment]
> but when I click on a specific build, I get "500: We're sorry, something went wrong on our end"

This is strange

Attaching a couple of build logs here.

From: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7956101043/artifacts/browse/spack-stage/spack-stage-phist-1.13.0-zo7pe2onggmf4jsp3n6vec72b7hok3gb/

[spack-build-out-clang-18.txt](https://github.com/user-attachments/files/17259993/spack-build-out-clang-18.txt)

From: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/7956101034/artifacts/browse/spack-stage/spack-stage-phist-1.13.0-sot52iswwtqmk3kph6pt44qbnhanw6bf/

[spack-build-out-oneapi-2024-2-1.txt](https://github.com/user-attachments/files/17260017/spack-build-out-oneapi-2024-2-1.txt)


Let me know if you need different set of logs [from the build dir] - I can run the builds manually - and attach such logs]

**Comment by balay** [comment]
> I will try something with clang, but as it doesn't properly support Fortran, I'm not too optimistic that I get the whole stack to build

I use gfortran with clang/clang++ - in my builds.
```- compiler:
    spec: clang@=18.1.6
    paths:
      cc: /usr/lib64/ccache/clang
      cxx: /usr/lib64/ccache/clang++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: fedora40
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

**Comment by balay** [comment]
```
/home/xsdk/builds/cYLkqamb/1/xsdk-project/spack-xsdk/spack-stage/spack-stage-phist-1.13.0-sot52iswwtqmk3kph6pt44qbnhanw6bf/spack-src/src/kernels/tpetra/kernels_def.hpp:734:32: error: non-constant-expression cannot be narrowed from type 'int' to 'double' in initializer list [-Wc++11-narrowing]
  734 |   Teuchos::Array<_ST_> scaling{nvec};
      |                                ^~~~
```
So this error can be suppressed with `cxxflags=-Wno-c++11-narrowing` - but perhaps there is a code change this is more appropriate.

**Comment by jthies** [comment]
Hi @sbalay, thanks a lot. I can't reproduce the issue but I think I understand whatt's happening. I attempted a fix in phist@develop, could you try running the CI with that version, and if it works I add a patch to spack for phist@1.12.

**Comment by balay** [comment]
> I attempted a fix in phist@develop, could you try running the CI with that version

Thanks! the (manual) clang build goes through now! Will start a CI build aswell.

>  and if it works I add a patch to spack for phist@1.12.

Ah ok - will switch xsdk to use this version. So far I assumed there would be a new release - so was using @develop.

**Comment by balay** [comment]
Started a pipeline here

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1482300999

**Comment by jthies** [comment]
that seems to work, I created a phist-1.12.1 tag and opened a PR to spack: https://github.com/spack/spack/pull/46802

**Comment by balay** [comment]
Thanks! testing this PR change (with xsdk) at https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/1482978926
