### ISSUE TITLE
hiop: raja (dep) build error on +cuda

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#268]
Not directly hiop issue - well raja is a dependency of hiop  (also camp - that is triggering raja build failure) - so tagging hiop here.
```

 -       ^hiop@1.1.0%gcc@11.4.0+cuda~cusolver_lu~deepchecking~ginkgo~ipo~jsrun~kron+mpi+raja~rocm~shared~sparse build_system=cmake build_type=Release cuda_arch=70 generator=make arch=linux-ubuntu22.04-x86_64
 -           ^camp@0.2.3%gcc@11.4.0+cuda~ipo~omptarget~openmp~rocm~sycl~tests build_system=cmake build_type=Release cuda_arch=70 generator=make patches=cb9e25b arch=linux-ubuntu22.04-x86_64
[+]              ^blt@0.4.1%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64
[+]              ^cub@2.1.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64
 -           ^raja@0.14.0%gcc@11.4.0+cuda~desul+examples+exercises~ipo~omptarget~omptask~openmp~plugins~rocm~run-all-tests~shared~sycl~tests~vectorization build_system=cmake build_type=Release cuda_arch=70 generator=make arch=linux-ubuntu22.04-x86_64
```
And the trigger is the change from https://github.com/spack/spack/pull/47720

Log from prior to change: 
[spack-build-out-good.txt](https://github.com/user-attachments/files/17942424/spack-build-out-good.txt)

Notice:
```
-- Found CUB: /scratch/svcpetsc/spack.a/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/cuda-11.7.1-nnyolmrglspl7fm2exxhwlhzplopqeuf/include
```
Log from after the above change: 
[spack-build-out-bad.txt](https://github.com/user-attachments/files/17942427/spack-build-out-bad.txt)

Notice:
```
-- Found CUB: /scratch/svcpetsc/spack.a/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/cub-2.1.0-jeuemk56wefipunpzgxndxhqusj7ybfj/include
```

So "reordering" dependencies - reorders the "include" path search - so a different version of cub is found - breaking build.

Perhaps the fix for this issue is to not have such duplicate copies of cub [when both cuda and cub are in dependency graph] - not sure how this can be added to spack.

For now - will work-around with `^raja~cuda`

**Comment by cnpetra** [comment]
cc-ing @nychiang

**Comment by balay** [comment]
(updated) fix at https://github.com/spack/spack/pull/48008

**Comment by balay** [comment]
The fix is merged to spack - so closing this issue
