### ISSUE TITLE
a small mistake on the websit

### ISSUE THREAD

**Issue by FENGSim** [xsdk-project/xsdk-issues#269]
hello, there is a small mistake on the website

During 2.17-2023, the xSDK was supported by the [Exascale Computing Projec](https://www.exascaleproject.org/)[t](https://www.exascaleproject.org/) (17-SC-20-SC), a collaborative effort of the U.S. Department of Energy Office of Science and the National Nuclear Security Administration.

it is 2017-2023, please change it, thanks

**Comment by balay** [comment]
fixed now. Thanks for the report!
