### ISSUE TITLE
Albany inclusion in xSDK October 2018 release

### ISSUE THREAD

**Issue by ibaned** [xsdk-project/xsdk-issues#50]
Albany team intends to participate in the October 2018 release of xSDK.

Checklist version 1/2018

**Comment by balos1** [comment]
@ibaned 

Does Albany still plan to be apart of the xsdk 0.4.0 release? If so, could you please open a pull request to add a policy compatibility document for Albany here: https://github.com/xsdk-project/xsdk-policy-compatibility.

**Comment by ibaned** [comment]
@balos1  I'm not sure I'll have time to go through with this, unless someone else pitches in then we may not have Albany be part of the release.
