### ISSUE TITLE
Omega_h inclusion in xSDK October 2018 release

### ISSUE THREAD

**Issue by ibaned** [xsdk-project/xsdk-issues#51]
Omega_h team intends to participate in the October 2018 release of xSDK.

Checklist version 1/2018

**Comment by ibaned** [comment]
Omega_h is compatible with xSDK policies:
 - M1
 - M2
 - M3
 - M4
 - M5
 - M6
 - M7
 - M8
 - M9
 - M10
 - M11
 - M12
 - M13
 - M14
 - M15
 - M16
 - R1
 - R2
 - R4

Omega_h is *incompatible* with xSDK policies:
 - [ ] R3: Omega_h currently aborts on error, but all error handling goes through one function. It should be straightforward to provide an option whereby that function throws a C++ exception instead.
 - [ ] R5: This can be done, we're awaiting consensus on what the format of this output should be

Edit: latest compatibility report [here](https://github.com/ibaned/omega_h/blob/master/doc/xsdk-compatibility.md)

Edit: Declaring compatibility with M16, since there is a Spack package for Omega_h

**Comment by balos1** [comment]
@ibaned Please, if you can, upload your policy compatibility document to the policy compatibility repository here: https://github.com/xsdk-project/xsdk-policy-compatibility

**Comment by ibaned** [comment]
@balos1 I just opened https://github.com/xsdk-project/xsdk-policy-compatibility/pull/9
