### ISSUE TITLE
Chombo inclusion in xSDK for October 2018

### ISSUE THREAD

**Issue by dtgraves** [xsdk-project/xsdk-issues#52]
The Chombo team intends to participate in the October 2018 release of xSDK.

Checklist version 1/2018.

**Comment by balos1** [comment]
@dtgraves Does Chombo still plan to participate in the xSDK 0.4.0 release? If so, could you please open a pull request with a policy compatibility document  (see the template in the linked repository) here: https://github.com/xsdk-project/xsdk-policy-compatibility.
