### ISSUE TITLE
DataTransferKit inclusion in xSDK October 2018 release

### ISSUE THREAD

**Issue by sslattery** [xsdk-project/xsdk-issues#53]
The DTK team intends to participate in the October 2018 release of the xSDK per version 1/2018 of the release checklist.

**Comment by balos1** [comment]
@sslattery We are in need of a policy compatibility document for DTK. Could you please add one here: https://github.com/xsdk-project/xsdk-policy-compatibility. You may open a pull request to have it merged and there is a template to work with.
