### ISSUE TITLE
CrunchFlow/CrunchTope inclusion in the October 2018 release

### ISSUE THREAD

**Issue by smolins** [xsdk-project/xsdk-issues#57]
The CrunchFlow/CrunchTope team intends to participate in the October 2018 release of the xSDK per version 1/2018 of the release checklist.

**Comment by balos1** [comment]
@smolins Does CrunFlow/CrunchTope still plan to participate in the xSDK 0.4.0 release? If so, could you please add a policy compatibility document for CrunchFlow/CrunchTope here (see the template in the linked repository): https://github.com/xsdk-project/xsdk-policy-compatibility

**Comment by smolins** [comment]
Unfortunately, no. No time.
