### ISSUE TITLE
DTK Compliance with Policy M4 and M16

### ISSUE THREAD

**Issue by sslattery** [xsdk-project/xsdk-issues#63]
DTK is potentially non-compliant with M4 and the related M16 as of 6/19/18. In detail:

- **M4**: Is having a working Spack install sufficient to satisfy _Each package should document the versions of dependent packages with which it can work, preferably in a machine-readable form._?

- **M16**: DTK is essentially considered an external Trilinos package which is intended to build simultaneously with the rest of Trilinos. To achieve this in Spack, we added a DTK variant of Trilinos in Spack which currently installs via the syntax `spack install trilinos+dtk`. However, this variant does not exist in the `xsdktrilinos` package.

If Spack compatibility satisfies the language in M4 and we add DTK to the xSDK Trilinos build then this should also satisfy M16.

**CONCERNS**
- Apparently, to speed up build times the type-2 stack in Trilinos has been disabled: https://github.com/spack/spack/blob/eac8cf83bd0b4891c9bcb7d07b0ae48d6dc203e6/var/spack/repos/builtin/packages/xsdk/package.py#L60
- The type-2 stack, in particular Tpetra, is required for building DTK. Therefore, the Spack xSDK Trilinos build will need to be modified.
- Even if DTK were to be changed to build as a package outside of Trilinos, the xSDK Trilinos build would still require packages such as Tpetra to build DTK.

**Comment by sslattery** [comment]
Should coordinate with @balay on testing type-2 Trilinos stack with spack.

**Comment by balay** [comment]
I don't completely understand the reference 'type-2 Trilinos
stack'. If its about enabling `tpetra` in xsdk install of trilinos - I
have the following change in my xsdk/trilions patches. I'm waiting on
`superlu-dist@develop` compatibility fix in trilinos - before doing a
PR on this change.

All the outstanding xsdk pataches are in branch `balay/xsdk-develop`

cc: @keitat

```
-    depends_on('trilinos@12.12.1+hypre+superlu-dist+metis+hdf5~mumps+boost~suite-sparse~tpetra+nox~ifpack2~zoltan2~amesos2~exodus',
+    depends_on('trilinos@develop+hypre+superlu-dist+metis+hdf5~mumps+boost~suite-sparse+tpetra+nox+ifpack2+zoltan2+amesos2~exodus',

```

**Comment by balay** [comment]
I tried enabling dtk

```
-    depends_on('trilinos@develop+hypre+superlu-dist+metis+hdf5~mumps+boost~suite-sparse+tpetra+nox+ifpack2+zoltan2+amesos2~exodus',
+    depends_on('trilinos@develop+hypre+superlu-dist+metis+hdf5~mumps+boost~suite-sparse+tpetra+nox+ifpack2+zoltan2+amesos2+dtk~exodus',
```

But get:

```
1 error found in build log:
     135    -- Setting Trilinos_ENABLE_STKSearchUtil=OFF because STKSearchUtil has a required library dependence on disabled package STKMesh
     136    -- Setting Trilinos_ENABLE_STKTools=OFF because STKTools has a required library dependence on disabled package STKMesh
     137    -- Setting Trilinos_ENABLE_PanzerAdaptersSTK=OFF because PanzerAdaptersSTK has a required library dependence on disabled package STKMesh
     138    -- Setting Trilinos_ENABLE_STKUnit_test_utils=OFF because STKUnit_test_utils has a required library dependence on disabled package STKIO
     139    -- Setting STKSearch_ENABLE_TESTS=OFF because STKSearch has a required test/example dependence on disabled package STKUnit_test_utils
     140    -- Setting STKSearch_ENABLE_EXAMPLES=OFF because STKSearch has a required test/example dependence on disabled package STKUnit_test_utils
  >> 141    CMake Error at cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1098 (MESSAGE):
     142       ***
     143       *** ERROR: Setting Trilinos_ENABLE_DataTransferKit=OFF which was 'ON' because DataTransferKit has a required library dependence on disabled package D
            ataTransferKitDiscretization!
     144       ***
     145    
     146    Call Stack (most recent call first):
     147      cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1181 (TRIBITS_PRIVATE_PRINT_DISABLE)
```

**Comment by keitat** [comment]
I will try adding Trilinos_ENABLE_DataTransferKitDiscretization:BOOL=ON in package.py of Trilinos.
Let's see if it works.  (Which one is your latest branch, Satish? )

**Comment by balay** [comment]
I mentioned this before:

All the outstanding xsdk pataches are in branch `balay/xsdk-develop`

**Comment by keitat** [comment]
There is a discussion in [here](https://github.com/spack/spack/pull/8660).  We are still working on Trillions package for Spack.
