### ISSUE TITLE
Proposed update of Community Installation Policy 10

### ISSUE THREAD

**Issue by balos1** [xsdk-project/xsdk-issues#79]
I am proposing a policy update based on the discussion in #71.

**Summary**

Currently the community installation policies require packages to provide options `TPL_<package>_INCLUDE_DIRS` and `TPL_<package>_LIBRARIES` to provide a list of include directories and a linkable list of libraries respectively. The proposed update removes this restriction, and places the guideline from the discussion section of the policies, which states that a package must use a specified installation of a TPL if it is given or  throw an error.  

**Current Policy**

The current policy reads:

>10. Determine other package libraries and include directories.
>
>`--with-<package>  --with-<package>-lib=”linkable list of libraries” --with-package-include=”-I list of include directories”`
>
> `TPL_ENABLE_<package>=[YES,NO], TPL_<package>_LIBRARIES=”linkable list of libraries”` (Should not use -L or -l flags), `TPL_<package>_INCLUDE_DIRS=”/path/to/includes1;/path/to/includes1;...”`  (Cannot include -I flags)

And then in the discussion section: 

> 10. ./configure --with-x --with-metis-lib=/usr/local/lib/libmetis.a 
> --with-metis-include=-I/usr/local/include 
> cmake -DTPL_Metis_LIBRARIES=/usr/local/lib/libmetis.a -DTPL_Metis_INCLUDE_DIRS=/usr/local/include ...
>
> MPI is never considered a `<package>`, and xSDK packages do not need to support `--with-mpi-lib` and `--with-mpi-include`. In fact, we recommend against it. 
>
> We also do not recommend support `--with-<package>-dir=directory` because that is difficult to implement robustly.
>
> Packages are free to locate a package on the file system if none is specifically provided by the user. If the user does provide one, however, it must be used; if it is not able to be used, then an error must be generated. A package cannot silently substitute a different installation.
>
>There does not exist any CMake standard allowing an external user to set what external package dependencies should be enabled or disabled when configuring.   Therefore, this is a TriBITS/Trilinos standard is which calls external packages “TPL”s and therefore the name `“TPL_ENABLE_<package>”`.

**Proposed Update**

The updated policy proposal:

>10. Determine other package libraries and include directories.
>
> `TPL_ENABLE_<package>=[YES,NO]`
>
> Packages must provide a way for a user to specify a package to use. Packages are free to locate a package on the file system if none is specifically provided by the user. If the user does provide one, however, it must be used; if it is not able to be used, then an error must be generated. A package cannot silently substitute a different installation.

And then in the discussion section: 

> 10.  ./configure --with-x --with-metis-lib=/usr/local/lib/libmetis.a 
> --with-metis-include=-I/usr/local/include 
> cmake -DTPL_Metis_ENABLE=ON -DTPL_Metis_LIBRARIES=/usr/local/lib/libmetis.a -DTPL_Metis_INCLUDE_DIRS=/usr/local/include ...
>
> Alternatively:
> `cmake -DTPL_Trilinos_ENABLE=ON -DTrilinos_DIR=/usr/local/lib/cmake/Trilinos`
>
> MPI is never considered a `<package>`, and xSDK packages do not need to support `--with-mpi-lib` and `--with-mpi-include`. In fact, we recommend against it. 
>
>There does not exist any CMake standard allowing an external user to set what external package dependencies should be enabled or disabled when configuring. Therefore, this is a TriBITS/Trilinos standard is which calls external packages “TPL”s and therefore the name `“TPL_ENABLE_<package>”`.
>
>In the second CMake example, a package could use CMake's `find_package()` to locate Trilinos as long as the package guarantees that the specified Trilinos installation provided in `Trilinos_DIR` is used. This could be done, for example, by using the `find_package()` NO_DEFAULT_PATH option. 

Pinging @bartlettroscoe @mkstoyanov @tgamblin @jthies.

Relevant issues: #71, #78.

**Comment by bartlettroscoe** [comment]
@balos1, looks good to me.  I edited the text above to fix things in `<something>` disappearing.

I actually have no idea how to update the current xSDK community policies document.  Is this in Markdown somewhere that we can propose a PR for?

**Comment by balos1** [comment]
@bartlettroscoe Thanks for the formatting fixes. The policies are just in this [google doc](https://docs.google.com/document/d/18028D6nsuhIrCvJnX6c07r8m_Np4SH-aGXMX4svMs1w/edit#heading=h.3hcywq83w3x0). FYI, this policy change would be slated for the next xSDK release (discussed in today's - 10/25 - xSDK meeting), because we are so close the 0.4.0 release more time is needed for the full xSDK policy proposal and review process to take place. CC @curfman.

**Comment by bartlettroscoe** [comment]
> The policies are just in this [google doc](https://docs.google.com/document/d/18028D6nsuhIrCvJnX6c07r8m_Np4SH-aGXMX4svMs1w). FYI, this policy change would be slated for the next xSDK release (discussed in today's - 10/25 - xSDK meeting), because we are so close the 0.4.0 release more time is needed for the full xSDK policy proposal and review process to take place. 

@balos1, so we can't make the changes now?  We are just weakening the CMake requirements so it should be fine to change this right now since any package that satisfied the old requirements will automatically satisfy the new requirements.

Can you make suggested changes to that Google Doc and then I can review and accept?  I think I can still directly edit that document.

Just to be clear, it was not my idea to constrain the CMake requirements like this.  Others in the old IDEAS/xSDK project argued for that so that we could have a standard that would work without a meta-build tool like SPACK.

**Comment by mkstoyanov** [comment]
@bartlettroscoe the point discussed on the call was that policy changes should be considered over a period of time and accepted with a great majority. This discussion so far has been primarily between the three of us here. The point is not to have a quick PR review or whether packages can adapt on time for the release.

I do agree that the CMake policies are too strict and in some points even contradictory to the SPACK design approach, but I would defer to others that are reluctant to bypass policy change procedures.

**Comment by bartlettroscoe** [comment]
@mkstoyanov,

Wait, is the official xSDK community standards still being maintained and displayed as a Google Doc?  Has no-one converted this to a Markdown file in a github repo and then displayed that through a GitHub Pages site yet?  That way people can proposed changes and fixes as PRs and make this so much more organized.

**Comment by mkstoyanov** [comment]
I agree that the proposed changes are an improvement to the current policy wording. But I think the change should go a step further and make the `TPL_` convention optional and allow for alternative convention:
```
<package>_ENABLE_<module/feature/language/TPL>
// for example
<package>_ENABLE_BLAS (enable a TPL)
<package>_ENABLE_CUDA (enable a language)
<package>_ENABLE_TESTING (enable a feature within the package)
```
Currently both languages and TPLs must be specified in a way different, which is not deal because:

1. If everyone is using the same naming convention, we may run into conflicts when using `#cmakedefine` in the headers. For example, one package enables OpenMP and the other does not because it requires higher minimum version, then the package with the disabled feature will see the wrong `#define` directive included from the headers of the other package. If all options are prefixed with the package name, there will be no conflicts much as if we were using namespaces.

2. The original policies were made from the point of view of a unified CMake/Autotool build system, now we have spack and spack variants, the way a variant is propagated to the individual packages is irrelevant so long as there are no conflicts (see point 1).

3. There is no need to explicitly differentiate between an internal module/feature and a TPL in the build system. Having a unified syntax to enable/disable options is preferable as it does not require users to check which option is a TPL and which internal module. Note that spack does not make such distinction either.

Just my thoughts.

PS: @bartlettroscoe the xSDK policies are here: https://xsdk.info/policies/ I don't think those exist on github.

**Comment by bartlettroscoe** [comment]
@mkstoyanov, as the CMake build systems are independent namespaces, we should not dictate the names of CMake cache vars.  We should only mandate certain behaviors.  Giving examples and recommendations for variable names is fine.

**Comment by mkstoyanov** [comment]
@bartlettroscoe, you want to relax it all the way? I'm OK with that. I think we should still have a guidance clause: "options should be enabled/disabled with expressive names, e.g., ...", but the behavior is more important.
* must provide a way to specify the external dependencies, e.g., specific BLAS library
* if a specific file/version is set, it cannot be automatically substituted
* automatic search is allowed when no file/version is explicitly given

**Comment by bartlettroscoe** [comment]
@mkstoyanov said

> *  must provide a way to specify the external dependencies, e.g., specific BLAS library
> * if a specific file/version is set, it cannot be automatically substituted
> * automatic search is allowed when no file/version is explicitly given

That is basically it but that also applies to include directories as well.   And need to allow passing in the abs paths to all the libs that satisfy a given external package.  Just supplying `<Package>_ROOT` as an env var is not enough in some cases.

**Comment by mkstoyanov** [comment]
> @bartlettroscoe 
> Just supplying `<Package>_ROOT` as an env var is not enough in some cases.

True statement, especially fit the package or some of the transitive dependencies don't export a proper CMake package-config. The unfortunate thing is that spack uses the CMake environment variables and I don't know if there is a way to query install paths and include dirs from spack dependencies. So, even if we add CMake way to select include dirs, then that may not work within spack.

How about the following:
* if a TPL comes with native CMake find_package(), e.g., BLAS, OpenMP, CUDA, then use those as they already provide pretty robust set of options
* if the TPL exports it's own package-config, then use the package-config, e.g., providing Tasmanian_ROOT and calling find_package(Tasmanian <version>) is sufficient and there is no reason to demand that people implement `Tasmanian_INCLUDE_DIRS`
* if the TLP doesn't fall in the above cases, then have a way to specify libraries and include paths

**Comment by balos1** [comment]
@mkstoyanov 

> 3. There is no need to explicitly differentiate between an internal module/feature and a TPL in the build system. Having a unified syntax to enable/disable options is preferable as it does not require users to check which option is a TPL and which internal module. Note that spack does not make such distinction either.

I agree with removing the TPL name-spacing, although I don't think it is absolutely necessary to tackle this in this specific update if others disagree. I'll note, we would also need to update bullet 9 in the installation policies.

> * if a TPL comes with native CMake find_package(), e.g., BLAS, OpenMP, CUDA, then use those as they already provide pretty robust set of options
> * if the TPL exports it's own package-config, then use the package-config, e.g., providing Tasmanian_ROOT and calling find_package(Tasmanian ) is sufficient and there is no reason to demand that people implement `Tasmanian_INCLUDE_DIRS`
> * if the TLP doesn't fall in the above cases, then have a way to specify libraries and include paths

I think the proposed update covers all three points, but in a less-specific way.

> 10. Determine other packages to use and their libraries and include directories.
>
> TPL_ENABLE_\<package\>=[YES,NO]
>
> Packages must provide a way for a user to specify a package to use. Packages are free to locate a package on the file system if none is specifically provided by the user. If the user does provide one, however, it must be used; if it is not able to be used, then an error must be generated. A package cannot silently substitute a different installation.

Perhaps we incorporate the more specific bullets in the example section?

**Comment by bartlettroscoe** [comment]
I agree with the more general description:

> Packages must provide a way for a user to specify a package to use. Packages are free to locate a package on the file system if none is specifically provided by the user. If the user does provide one, however, it must be used; if it is not able to be used, then an error must be generated. A package cannot silently substitute a different installation.

I think it is fine to provide examples of how packages can accomplish this and even to mention how Spack uses `<ExternalPackage>_ROOT` env vars to try to glue packages together.   I don't think just providing `<ExternalPackage>_ROOT`  is really good enough in some cases and the default `Find<Package>.cmake` modules don't always work well on some systems.  (But client packages can override the default `Find<Package>.cmake` module and that is how SEACAS, for example, makes things work). 

It would be much better if every package just provided an installed `<Package>Config.cmake` file to take all of the guess work out of using an installed package.  In fact, the xSDK community standards should make the generation of a standard `<Package>Config.cmake` for CMake-based packages a recommended practice (if not required at some point).

NOTE: One problem with:

* https://cmake.org/cmake/help/v3.10/module/CMakePackageConfigHelpers.html

is that it is not consistent with the [Semantic Versioning Standard](https://semver.org).  (That is, version `X.(Y+i)` will be considered to be compatible to the requested version `X.Y` for all `i >= 0`.)  We should work with Kitware to put in a SemVer mode or define a standard way to write `<Package>ConfigVersion.cmake` files that does.  (Would take some work to write a SemVer comparison function in CMake but it can be done.)

**Comment by luszczek** [comment]
The equivalent to find_package() in CMake is the autoconf-archive repository https://www.gnu.org/software/autoconf-archive/The-Macros.html

**Comment by mkstoyanov** [comment]
@luszczek find_package() has two sides, one is the existing database of CMake "known" common packages, which includes things like BLAS, LAPACK, OpenMP ...

A package outside of that list can still provide their own package-config files during install. Tasmanian does that (for example). The advantage of a proper the package-config is that it takes very little hint from the user or the environment to find Tasmanian and to include all transitive dependencies:
```
find_package(Tasmanian 6.0) # spack does not need additional hits
target_link_libraries(Foo Tasmanian) # handles all transitive dependencies, flags, includes, etc.
```

**Comment by jthies** [comment]
Hi,

there is a third ‚side‘ to find_package: if my package A needs package B, but there is now<B>-config.cmake, A can have a Find<A>.cmake describing how to search for B.

Jonas

Von: Miroslav Stoyanov [mailto:notifications@github.com]
Gesendet: Freitag, 3. Mai 2019 17:59
An: xsdk-project/xsdk-issues
Cc: Thies, Jonas; Mention
Betreff: Re: [xsdk-project/xsdk-issues] Proposed update of Community Installation Policy 10 (#79)


@luszczek<https://github.com/luszczek> find_package() has two sides, one is the existing database of CMake "known" common packages, which includes things like BLAS, LAPACK, OpenMP ...

A package outside of that list can still provide their own package-config files during install. Tasmanian does that (for example). The advantage of a proper the package-config is that it takes very little hint from the user or the environment to find Tasmanian and to include all transitive dependencies:

find_package(Tasmanian 6.0) # spack does not need additional hits

target_link_libraries(Foo Tasmanian) # handles all transitive dependencies, flags, includes, etc.

**Comment by bartlettroscoe** [comment]
@jthies said:

> there is a third ‚side‘ to find_package: if my package A needs package B, but there is now `<B>-config.cmake`, A can have a `Find<A>.cmake` describing how to search for B.

Do you mean that package `A` can have a `Find<B>.cmake`?  What is the behavior of `find_package(<B> ...)` when both `Find<B>.cmake` and `<B>Config.cmake` (or `<B>-config.cmake`) both exist?  From looking at the documentation at:

*  https://cmake.org/cmake/help/v3.14/command/find_package.html

it seems that the basic command `find_package(<B>)` command will first look for `Find<B>.cmake` and use it if it exists.  We would likely need to ask Brad King at Kitware for clarification.

**Comment by jthies** [comment]
As far as I know, the default (find_package(<B>)) would use the Find<B>.cmake included in <A>, to overrule that one can use find_package(<B> CONFIG)

Von: Roscoe A. Bartlett [mailto:notifications@github.com]
Gesendet: Samstag, 4. Mai 2019 15:28
An: xsdk-project/xsdk-issues
Cc: Thies, Jonas; Mention
Betreff: Re: [xsdk-project/xsdk-issues] Proposed update of Community Installation Policy 10 (#79)


@jthies<https://github.com/jthies> said:

there is a third ‚side‘ to find_package: if my package A needs package B, but there is now <B>-config.cmake, A can have a Find<A>.cmake describing how to search for B.

Do you mean that package A can have a Find<B>.cmake? What is the behavior of find_package(<B> ...) when both Find<B>.cmake and <B>Config.cmake (or <B>-config.cmake) both exist? From looking at the documentation at:

  *   https://cmake.org/cmake/help/v3.14/command/find_package.html

it seems that the basic command find_package(<B>) command will first look for Find<B>.cmake and use it if it exists. We would likely need to ask Brad King at Kitware for clarification.

**Comment by bartlettroscoe** [comment]
@jthies said:

> As far as I know, the default (`find_package(<B>)`) would use the `Find<B>.cmake` included in `<A>`, to overrule that one can use `find_package(<B> CONFIG)`

That is not a great solution and may lead to different downstream packages finding different upstream packages.  For example, consider 4 packages where package B depends on package A, package C depends on package A, and package D depends on packages B and C (the classic diamond).  If package B defines its own custom `FindA.cmake` to call `find_package(A CONFIG)` but package C does not and just has `find_package(A)`, then package B and C could find different package A's (i.e. package B would find the one with `AConfig.config` where package C may find one somewhere else on the system because it is using some other `FindA.cmake` module).  This would likely cause link or runtime problems in package C since it was linking in two different implementation of packages A. 

Even if `A_ROOT` is set and the same package A is used, the way the the parts of package A are pulled in with `FindA.cmake` and `AConfig.cmake` may be different and may cause problems.

This pair way matching of packages is just asking for problems when trying to compose larger stacks of interdependent package builds.  Just setting `<Package>_ROOT` does not guarantee consistency.  Passing in an explicit set of include dirs and libraries does.

**Comment by balos1** [comment]
Closed by https://github.com/xsdk-project/xsdk-community-policies/pull/1.
