### ISSUE TITLE
precice: build issue on linux-centos7-mic_knl / intel@18.0.2

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#81]
bash-4.2$ hostname
isdp001.cels.anl.gov

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/3715370/spack-build-out.txt)
 1027  spack install -j48 xsdk ^py-numpy%gcc@4.8.5

**Comment by fsimonis** [comment]
preCICE requires C++11 for time formatting.
As intel uses the gcc libstdc++ as standard library, it requires version 5.0 of gcc.

Source: https://en.cppreference.com/w/cpp/compiler_support

**Comment by balay** [comment]
Currently using:
```
export PATH=/opt/gcc-7.2.0/bin/:$PATH
export LD_LIBRARY_PATH=/opt/gcc-7.2.0/lib64:$LD_LIBRARY_PATH

(date; spack install -j48 xsdk; date) |& tee spack-build.log
```
