### ISSUE TITLE
GCC compilers on Summit run out of memory

### ISSUE THREAD

**Issue by luszczek** [xsdk-project/xsdk-issues#89]
I get "cannot allocate memory" error for GCC 6, 7, and 8 on Summit with either Boost or Trilinos. This may be related to the recent policy change that limits cores and memory for the login node processes. I'm trying to verify this with a different POWER9 system.

**Comment by balay** [comment]
suggest `spack install -j <val> xsdk` with <val> smaller than  spack default value [usually nproc]
