### ISSUE TITLE
Chombo in xSDK Nov 1 release

### ISSUE THREAD

**Issue by drhansj** [xsdk-project/xsdk-issues#9]
Chombo team intends to complete the package release checklist for Nov 1 release. Terry Ligocki will be the primary point of contact.

**Comment by tjligocki-lbl** [comment]
List of community policies for which Chombo is compatible:
M2, M3, M4, M5, M6, M7, M8, M9, M10, M11, M12, M13, M14, M16

List of community policies for which Chombo is not compatible:
M1, M15

**Comment by tjligocki-lbl** [comment]
Since Chombo can't be compatible with both M1 and M15 by the current release date, we will work toward being compatible by the next release date.
