### ISSUE TITLE
ginkgo@1.1.0 build failure on linux-centos7-haswell / gcc@4.8.5

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#92]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/3821921/spack-build-out.txt)

Perhaps the compiler is too old - so we need to add a conflict.

cc: @hartwiganzt

**Comment by hartwiganzt** [comment]
@balay that is correct - Ginkgo needs gcc 5.3+ see https://github.com/ginkgo-project/ginkgo prerequisites.

**Comment by balay** [comment]
Thanks! will add this change [can go directly to spack@develop as a PR]

```
diff --git a/var/spack/repos/builtin/packages/ginkgo/package.py b/var/spack/repos/builtin/packages/ginkgo/package.py
index b63fe773e..a0de875a5 100644
--- a/var/spack/repos/builtin/packages/ginkgo/package.py
+++ b/var/spack/repos/builtin/packages/ginkgo/package.py
@@ -32,6 +32,8 @@ class Ginkgo(CMakePackage, CudaPackage):
     depends_on('cmake@3.9:', type='build')
     depends_on('cuda@9:',    when='+cuda')
 
+    conflicts('%gcc@:5.2.9')
+
     def cmake_args(self):
         spec = self.spec
         return [
```

**Comment by balay** [comment]
closing this issue as we added the necessary conflict on older gcc.

And installing [for this compiler] with:

`spack install xsdk~ginkgo~phist~precice+cuda ^suite-sparse@5.1.0 `
