### ISSUE TITLE
superlu-dist@6.1.1 fails build with xl compiler

### ISSUE THREAD

**Issue by acfisher** [xsdk-project/xsdk-issues#93]
Many errors along the lines of:
 >> 1134    ../SRC/libsuperlu_dist.so.6.1.1: undefined reference to `dger_'
  >> 1135    ../SRC/libsuperlu_dist.so.6.1.1: undefined reference to `ztrsv_'
  >> 1136    ../SRC/libsuperlu_dist.so.6.1.1: undefined reference to `zgeru_'
  >> 1137    ../SRC/libsuperlu_dist.so.6.1.1: undefined reference to `dtrtri_'
  >> 1138    ../SRC/libsuperlu_dist.so.6.1.1: undefined reference to `ztrsm_'

I believe the fortran name mangling is not set up to detect which style to use for the xl compiler and is causing these problems.

**Comment by xiaoyeli** [comment]
I have a fix to use cmake FortranCInterface module to do the name mangling.
I plan to package a release 6.1.2 tomorrow.  Will this be able to get into
the upcoming xSDK release ?

Sherry

**Comment by balay** [comment]
Pehaps the following work-around for 6.1.1?

```
diff --git a/var/spack/repos/builtin/packages/superlu-dist/package.py b/var/spack/repos/builtin/packages/superlu-dist/package.py
index c49a624b1..bb4f9f864 100644
--- a/var/spack/repos/builtin/packages/superlu-dist/package.py
+++ b/var/spack/repos/builtin/packages/superlu-dist/package.py
@@ -53,6 +53,8 @@ class SuperluDist(CMakePackage):
             ';' + spec['metis'].libs.ld_flags,
             '-DTPL_PARMETIS_INCLUDE_DIRS=%s' % spec['parmetis'].prefix.include
         ]
+        if '%xl' in spec or '%xl_r' in spec:
+            args.append('-DCMAKE_C_FLAGS="-DNoChange"')
 
         if '+int64' in spec:
             args.append('-DXSDK_INDEX_SIZE=64')

```

**Comment by balay** [comment]
Assuming all version 6.1.1 and older need this fix - [ and 6.1.2 and newer will work correctly without this change] - here is the updated patch.
```diff --git a/var/spack/repos/builtin/packages/superlu-dist/package.py b/var/spack/repos/builtin/packages/superlu-dist/package.py
index c49a624b1..cb4994878 100644
--- a/var/spack/repos/builtin/packages/superlu-dist/package.py
+++ b/var/spack/repos/builtin/packages/superlu-dist/package.py
@@ -54,6 +54,10 @@ class SuperluDist(CMakePackage):
             '-DTPL_PARMETIS_INCLUDE_DIRS=%s' % spec['parmetis'].prefix.include
         ]
 
+        if (spec.satisfies('%xl') or spec.satisfies('%xl_r')) and \
+           spec.satisfies('@:6.1.1'):
+            args.append('-DCMAKE_C_FLAGS=-DNoChange')
+
         if '+int64' in spec:
             args.append('-DXSDK_INDEX_SIZE=64')
         else:
```

**Comment by balay** [comment]
I have this change at https://github.com/spack/spack/pull/13702

**Comment by acfisher** [comment]
It works with xl now, thanks all.
